import type { Puzzle } from "./types";
import { REVIEW_HARD_BATCH_C, REVIEW_STANDARD_BATCH_F } from "./generated-puzzles";

const DEFAULT_WORD_EMOJI = "✨";

const WORD_EMOJIS: Record<string, string> = {
  Alarm: "🚨",
  Ball: "⚽",
  Band: "🎸",
  Bench: "🪑",
  Board: "🧩",
  Boil: "♨️",
  Box: "📦",
  Button: "🔘",
  Car: "🚗",
  Card: "🃏",
  Case: "💼",
  Clear: "✨",
  Clock: "🕐",
  Coast: "🏖️",
  Coat: "🧥",
  Crown: "👑",
  Dance: "💃",
  Dog: "🐕",
  Drill: "🛠️",
  Drum: "🥁",
  Elephant: "🐘",
  Escape: "🏃",
  Fairy: "🧚",
  Fire: "🔥",
  Floor: "🪩",
  Food: "🍽️",
  Foot: "🦶",
  Game: "🎮",
  Gate: "🚪",
  Green: "🟩",
  Guard: "💂",
  Hand: "✋",
  Horse: "🐎",
  House: "🏠",
  King: "🤴",
  Life: "🌱",
  Line: "➖",
  Locker: "🔒",
  Man: "👨",
  Memory: "🧠",
  Night: "🌙",
  Owl: "🦉",
  Party: "🎉",
  Plant: "🪴",
  Pocket: "👖",
  Power: "⚡",
  Press: "📰",
  Race: "🏁",
  Rail: "🚆",
  Roll: "🌀",
  Room: "🛋️",
  Sea: "🌊",
  Seat: "💺",
  Service: "🛎️",
  Skin: "🧴",
  Sleeper: "😴",
  Snow: "❄️",
  Step: "👣",
  Stick: "🪵",
  Storm: "⛈️",
  Style: "🎨",
  Suit: "🤵",
  Tail: "🐒",
  Tale: "📖",
  Tea: "🍵",
  Thunder: "🌩️",
  Tide: "🌊",
  Tooth: "🦷",
  Top: "🔝",
  Tower: "🗼",
  Track: "🛤️",
  Tree: "🌳",
  Trunk: "🧳",
  Up: "⬆️",
  Vice: "🗜️",
  Watch: "⌚",
  Water: "💧",
};

function applyWordEmojis(puzzle: Puzzle): Puzzle {
  return {
    ...puzzle,
    solution: puzzle.solution.map((item) => ({
      ...item,
      emoji: item.emoji ?? WORD_EMOJIS[item.word] ?? DEFAULT_WORD_EMOJI,
    })),
  };
}

const GPT_54_HIGH_GENERATION: NonNullable<Puzzle["generation"]> = {
  author: "GitHub Copilot",
  model: "openai/gpt-5.4-high",
  provider: "github-copilot",
  generatedAt: "2026-04-21",
  sourceCommit: "f3d0bd2",
};

const CLAUDE_OPUS_4_GENERATION: NonNullable<Puzzle["generation"]> = {
  author: "GitHub Copilot",
  model: "claude-opus-4",
  provider: "github-copilot",
  generatedAt: "2026-04-21",
  sourceCommit: "c019d64",
};

const PUZZLE_GENERATION_BY_INDEX = new Map<number, NonNullable<Puzzle["generation"]>>([
  [12, GPT_54_HIGH_GENERATION],
  [13, GPT_54_HIGH_GENERATION],
  [14, GPT_54_HIGH_GENERATION],
  [15, GPT_54_HIGH_GENERATION],
  [16, GPT_54_HIGH_GENERATION],
  [17, CLAUDE_OPUS_4_GENERATION],
  [18, CLAUDE_OPUS_4_GENERATION],
  [19, CLAUDE_OPUS_4_GENERATION],
  [20, CLAUDE_OPUS_4_GENERATION],
]);

function applyPuzzleGeneration(puzzle: Puzzle, index: number): Puzzle {
  const generation = PUZZLE_GENERATION_BY_INDEX.get(index);
  return generation ? { ...puzzle, generation } : puzzle;
}

export const PUZZLES: Puzzle[] = [
  {
    solution: [
      { word: "Stand", emoji: "🧍" },
      { word: "Up" },
      { word: "Hill", emoji: "⛰️" },
      { word: "Sit", emoji: "🪑" },
      { word: "Down", emoji: "⬇️" },
      { word: "Town", emoji: "🏘️" },
      { word: "Lie", emoji: "🛌" },
      { word: "Low", emoji: "📉" },
      { word: "Land", emoji: "🏞️" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A standup comic lives or dies by the next punch line." },
      { from: 1, to: 2, clue: "An uphill stretch of road burns the calves fastest." },
      { from: 3, to: 4, clue: "A sit-down dinner settles everyone before the talking starts." },
      { from: 4, to: 5, clue: "Downtown is where the nightlife stacks into its tallest blocks." },
      { from: 6, to: 7, clue: "Lie low until the fuss dies off." },
      { from: 7, to: 8, clue: "Lowland fields flood first when the rivers swell." },
      { from: 0, to: 3, clue: "Stand and sit are the pair every classroom drills all day." },
      { from: 3, to: 6, clue: "Sit a while or lie flat — both are postures a tired body picks." },
      { from: 1, to: 4, clue: "Up and down run every scale, from moods to markets." },
      { from: 4, to: 7, clue: "Keep it on the down low and no one needs to know." },
      { from: 2, to: 5, clue: "A hill town earns its views by making visitors climb for them." },
      { from: 5, to: 8, clue: "Town gives way to open land the moment the pavement ends." },
    ],
  },
  {
    solution: [
      { word: "Car" },
      { word: "Trunk" },
      { word: "Elephant" },
      { word: "Race" },
      { word: "Suit" },
      { word: "Memory" },
      { word: "Track" },
      { word: "Case" },
      { word: "Card" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Cars have trunks." },
      { from: 1, to: 2, clue: "Elephants are famous for theirs." },
      { from: 3, to: 4, clue: "A race suit belongs on a track." },
      { from: 4, to: 5, clue: "Card suits live in memory if you play enough." },
      { from: 6, to: 7, clue: "A case can be tracked." },
      { from: 7, to: 8, clue: "A card case stores the deck." },
      { from: 0, to: 3, clue: "A car race is the obvious pairing." },
      { from: 3, to: 6, clue: "A race track completes the circuit." },
      { from: 1, to: 4, clue: "A trunk can count as a kind of suit or case." },
      { from: 4, to: 7, clue: "A suitcase rolls through the airport." },
      { from: 2, to: 5, clue: "Elephants have the reputation memory wants." },
      { from: 5, to: 8, clue: "A memory card stores the lot." },
    ],
  },
  {
    solution: [
      { word: "Paper", emoji: "📄" },
      { word: "Chain", emoji: "⛓️" },
      { word: "Dog" },
      { word: "Clip", emoji: "📎" },
      { word: "Mail", emoji: "✉️" },
      { word: "Tag", emoji: "🏷️" },
      { word: "Board" },
      { word: "Room" },
      { word: "Service" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A paper chain is a classic classroom decoration." },
      { from: 1, to: 2, clue: "A dog chain keeps a pet from wandering off." },
      { from: 3, to: 4, clue: "A clip can hold a small pile of mail together." },
      { from: 4, to: 5, clue: "A mailing tag travels with the parcel." },
      { from: 6, to: 7, clue: "A boardroom is where the meeting usually starts." },
      { from: 7, to: 8, clue: "Room service brings the tray to your door." },
      { from: 0, to: 3, clue: "A paper clip is the obvious desk pairing." },
      { from: 3, to: 6, clue: "A clipboard gives paper a firm backing." },
      { from: 1, to: 4, clue: "Chain mail is the armored phrase hiding here." },
      { from: 4, to: 7, clue: "A mail room keeps office deliveries sorted." },
      { from: 2, to: 5, clue: "A dog tag hangs from a collar or uniform." },
      { from: 5, to: 8, clue: "A service tag records repair or inspection work." },
    ],
  },
  {
    solution: [
      { word: "Fire" },
      { word: "Alarm" },
      { word: "Button" },
      { word: "Drill" },
      { word: "Press" },
      { word: "Box" },
      { word: "Vice" },
      { word: "Bench" },
      { word: "Seat" },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        clue: "A fire alarm wants your attention immediately.",
      },
      { from: 1, to: 2, clue: "You hit the alarm button in a hurry." },
      { from: 3, to: 4, clue: "A drill press belongs in a workshop." },
      { from: 4, to: 5, clue: "A press box hovers over the field." },
      { from: 6, to: 7, clue: "A bench vice bolts to the workbench." },
      { from: 7, to: 8, clue: "A bench seat runs the width of the row." },
      { from: 0, to: 3, clue: "A fire drill is all practice and no flames." },
      { from: 3, to: 6, clue: "A vice steadies the piece beneath the drill." },
      { from: 1, to: 4, clue: "You press the alarm to trigger it." },
      {
        from: 4,
        to: 7,
        clue: "A bench press does not feel optional halfway through.",
      },
      { from: 2, to: 5, clue: "A button box can store buttons or controls." },
      { from: 5, to: 8, clue: "A box seat sits off to the side." },
    ],
  },
  {
    solution: [
      { word: "Air", emoji: "💨" },
      { word: "Base", emoji: "🏠" },
      { word: "Home", emoji: "🏡" },
      { word: "Head", emoji: "🙂" },
      { word: "Line" },
      { word: "Land", emoji: "🏞️" },
      { word: "Over", emoji: "🔄" },
      { word: "Time", emoji: "⏰" },
      { word: "Mark", emoji: "✏️" },
    ],
    edges: [
      { from: 0, to: 1, clue: "An airbase houses jets and the crews who fly them." },
      { from: 1, to: 2, clue: "A runner heading for home base makes the whole dugout stand." },
      { from: 3, to: 4, clue: "A headline is the first thing a reader sees." },
      { from: 4, to: 5, clue: "A landline still rings in plenty of kitchens." },
      { from: 6, to: 7, clue: "Overtime is what the clock gives when the game refuses to end." },
      { from: 7, to: 8, clue: "To mark time is to drill in place until someone calls the next move." },
      { from: 0, to: 3, clue: "An airhead is the mildest possible insult." },
      { from: 3, to: 6, clue: "Overhead storage is what every airline passenger fights for." },
      { from: 1, to: 4, clue: "A baseline is the ground truth every comparison starts from." },
      { from: 4, to: 7, clue: "A timeline sorts the story into first, next, and last." },
      { from: 2, to: 5, clue: "Homeland is the place a passport finally points back to." },
      { from: 5, to: 8, clue: "A landmark is how people describe where to meet." },
    ],
  },
  {
    solution: [
      { word: "Tea" },
      { word: "Green" },
      { word: "Power" },
      { word: "Tree" },
      { word: "House" },
      { word: "Plant" },
      { word: "Line" },
      { word: "Party" },
      { word: "Food" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Green tea is the gentler cup." },
      { from: 1, to: 2, clue: "Green power comes from cleaner sources." },
      { from: 3, to: 4, clue: "A tree house belongs above ground level." },
      { from: 4, to: 5, clue: "A houseplant lives indoors." },
      {
        from: 6,
        to: 7,
        clue: "A party line once shared a neighborhood phone.",
      },
      { from: 7, to: 8, clue: "Party food disappears first." },
      { from: 0, to: 3, clue: "The tea tree lends its name to the oil." },
      { from: 3, to: 6, clue: "A tree line marks where growth gives up." },
      {
        from: 1,
        to: 4,
        clue: "Greenhouse is the compound hiding in plain sight.",
      },
      { from: 4, to: 7, clue: "A house party gets louder than intended." },
      { from: 2, to: 5, clue: "A power plant makes the grid hum." },
      { from: 5, to: 8, clue: "Plant food keeps the leaves honest." },
    ],
  },
  {
    solution: [
      { word: "Door", emoji: "🚪" },
      { word: "Lock", emoji: "🔒" },
      { word: "Key", emoji: "🔑" },
      { word: "Bell", emoji: "🔔" },
      { word: "Chain", emoji: "⛓️" },
      { word: "Ring", emoji: "💍" },
      { word: "Tower" },
      { word: "Guard" },
      { word: "Tone", emoji: "🎵" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A door lock is the first layer of security." },
      { from: 1, to: 2, clue: "Lock and key are the oldest security pairing in the book." },
      { from: 3, to: 4, clue: "A bell chain gives you something to pull." },
      { from: 4, to: 5, clue: "A chain ring sits at the heart of a bicycle drivetrain." },
      { from: 6, to: 7, clue: "A tower guard watches from the high point." },
      { from: 7, to: 8, clue: "A guarded tone is how people hedge a risky answer." },
      { from: 0, to: 3, clue: "A doorbell announces whoever is outside." },
      { from: 3, to: 6, clue: "A bell tower is built to be heard across town." },
      { from: 1, to: 4, clue: "A lock and chain together secure a gate or locker." },
      { from: 4, to: 7, clue: "A chain guard keeps grease and teeth away from clothing." },
      { from: 2, to: 5, clue: "A keyring keeps the whole set rattling together." },
      { from: 5, to: 8, clue: "A ringtone is the sound your phone picks for callers." },
    ],
  },
  {
    solution: [
      { word: "Tower" },
      { word: "Power" },
      { word: "Horse" },
      { word: "Water" },
      { word: "Plant" },
      { word: "Food" },
      { word: "Gate" },
      { word: "House" },
      { word: "Dog" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A power tower rises over transmission lines." },
      { from: 1, to: 2, clue: "Horsepower measures what the engine can do." },
      { from: 3, to: 4, clue: "A water plant filters what the city drinks." },
      { from: 4, to: 5, clue: "Plant food keeps roots ambitious." },
      { from: 6, to: 7, clue: "A gatehouse keeps the entrance honest." },
      { from: 7, to: 8, clue: "A doghouse is where mistakes get remembered." },
      { from: 0, to: 3, clue: "A water tower is a skyline landmark." },
      {
        from: 3,
        to: 6,
        clue: "Watergate became a word bigger than the building.",
      },
      { from: 1, to: 4, clue: "A power plant supplies the region." },
      { from: 4, to: 7, clue: "A houseplant survives by the window." },
      { from: 2, to: 5, clue: "Horse food is measured by the scoop." },
      { from: 5, to: 8, clue: "Dog food is never marketed to cats." },
    ],
  },
  {
    solution: [
      { word: "Man" },
      { word: "Foot" },
      { word: "Locker" },
      { word: "Snow" },
      { word: "Ball" },
      { word: "Room" },
      { word: "Board" },
      { word: "Game" },
      { word: "Escape" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A footman serves the household." },
      { from: 1, to: 2, clue: "A footlocker keeps kit in one place." },
      { from: 3, to: 4, clue: "A snowball grows if you keep rolling it." },
      { from: 4, to: 5, clue: "A ballroom invites a formal spin." },
      { from: 6, to: 7, clue: "A board game belongs on the table." },
      { from: 7, to: 8, clue: "An escape game works best under pressure." },
      { from: 0, to: 3, clue: "A snowman is assembled in the cold." },
      { from: 3, to: 6, clue: "A snowboard takes the slope sideways." },
      { from: 1, to: 4, clue: "Football is the obvious collision." },
      { from: 4, to: 7, clue: "A ball game can turn with one swing." },
      { from: 2, to: 5, clue: "A locker room is all echoes and benches." },
      { from: 5, to: 8, clue: "An escape room rewards calm minds." },
    ],
  },
  {
    solution: [
      { word: "Sea" },
      { word: "Life" },
      { word: "Style" },
      { word: "Coast" },
      { word: "Line" },
      { word: "Dance" },
      { word: "Clear" },
      { word: "Up" },
      { word: "Step" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Sea life keeps the reef busy." },
      { from: 1, to: 2, clue: "Lifestyle choices add up." },
      { from: 3, to: 4, clue: "A coastline is where maps get interesting." },
      { from: 4, to: 5, clue: "A line dance keeps the formation neat." },
      { from: 6, to: 7, clue: "Clear up the mess before you leave." },
      { from: 7, to: 8, clue: "Step up and take the turn." },
      {
        from: 0,
        to: 3,
        clue: "The seacoast is where land negotiates with water.",
      },
      { from: 3, to: 6, clue: "When the coast is clear, move." },
      { from: 1, to: 4, clue: "A lifeline is not optional when it matters." },
      { from: 4, to: 7, clue: "Line up and keep it orderly." },
      { from: 2, to: 5, clue: "Dance style changes with the decade." },
      { from: 5, to: 8, clue: "A dance step is learned one beat at a time." },
    ],
  },
  {
    solution: [
      { word: "Watch" },
      { word: "Night" },
      { word: "Sleeper" },
      { word: "Dog" },
      { word: "Guard" },
      { word: "Rail" },
      { word: "Sea" },
      { word: "Coast" },
      { word: "Line" },
    ],
    edges: [
      { from: 0, to: 1, clue: "The night watch belongs to the dark hours." },
      { from: 1, to: 2, clue: "A night sleeper takes the overnight route." },
      { from: 3, to: 4, clue: "A guard dog discourages bad ideas." },
      { from: 4, to: 5, clue: "A guard rail keeps the edge negotiable." },
      { from: 6, to: 7, clue: "The seacoast is the border with weather." },
      { from: 7, to: 8, clue: "A coastline is traced, never rushed." },
      { from: 0, to: 3, clue: "A watchdog notices what the room missed." },
      { from: 3, to: 6, clue: "A sea dog has spent time on rough water." },
      { from: 1, to: 4, clue: "A night guard owns the empty building." },
      { from: 4, to: 7, clue: "The coast guard arrives with authority." },
      { from: 2, to: 5, clue: "A rail sleeper lies beneath the track." },
      { from: 5, to: 8, clue: "A rail line runs farther than it seems." },
    ],
  },
  {
    solution: [
      { word: "Hotel", emoji: "🏨" },
      { word: "Bell" },
      { word: "Desk", emoji: "🛎️" },
      { word: "Mail", emoji: "✉️" },
      { word: "Room" },
      { word: "Service" },
      { word: "Box" },
      { word: "Board" },
      { word: "Key" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A hotel bell summons help or announces arrival." },
      { from: 1, to: 2, clue: "A bell sits on the front desk in plenty of lobbies." },
      { from: 3, to: 4, clue: "A mailroom keeps deliveries from getting lost." },
      { from: 4, to: 5, clue: "Room service is one of the classic hotel perks." },
      { from: 6, to: 7, clue: "Boxboard is the stiff card stock cereal packets are made from." },
      { from: 7, to: 8, clue: "A keyboard gets pounded all day in every office." },
      { from: 0, to: 3, clue: "A hotel mail slot catches whatever arrives after check-in." },
      { from: 3, to: 6, clue: "A mailbox is the standard place letters wait." },
      { from: 1, to: 4, clue: "A bellroom was the old name for where hotel bellhops waited for the next call." },
      { from: 4, to: 7, clue: "Room and board is what a rented arrangement promises beyond the bed." },
      { from: 2, to: 5, clue: "A service desk is where questions and problems land first." },
      { from: 5, to: 8, clue: "A service key is the staff version that opens the right doors." },
    ],
  },
  {
    solution: [
      { word: "Guest", emoji: "🧳" },
      { word: "Book", emoji: "📘" },
      { word: "Club", emoji: "🎟️" },
      { word: "Gate" },
      { word: "Keeper", emoji: "🧑‍🌾" },
      { word: "Shop", emoji: "🏪" },
      { word: "House" },
      { word: "Pet", emoji: "🐶" },
      { word: "Food" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A guest book records who came by." },
      { from: 1, to: 2, clue: "A book club picks a title to discuss together." },
      { from: 3, to: 4, clue: "A gatekeeper decides who gets through." },
      { from: 4, to: 5, clue: "A shopkeeper runs the store floor and the till." },
      { from: 6, to: 7, clue: "A house pet lives with people at home." },
      { from: 7, to: 8, clue: "Pet food is sold for cats, dogs, and more." },
      { from: 0, to: 3, clue: "A guest arrives through the gate before reaching the door." },
      { from: 1, to: 4, clue: "A bookkeeper handles accounts and balances." },
      { from: 2, to: 5, clue: "A club shop sells team gear and member items." },
      { from: 3, to: 6, clue: "A gatehouse stands beside the main entrance." },
      { from: 4, to: 7, clue: "A pet keeper cares for animals every day." },
      { from: 5, to: 8, clue: "A shop sells food from produce to pantry basics." },
    ],
  },
  {
    solution: [
      { word: "Cab", emoji: "🚕" },
      { word: "Taxi", emoji: "🚖" },
      { word: "Stand", emoji: "🪧" },
      { word: "Truck", emoji: "🚛" },
      { word: "Driver", emoji: "🧑‍✈️" },
      { word: "Bus", emoji: "🚌" },
      { word: "Delivery", emoji: "📦" },
      { word: "Route", emoji: "🗺️" },
      { word: "Stop", emoji: "🚏" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A taxi cab is the same ride by another name." },
      { from: 1, to: 2, clue: "A taxi stand is where cabs queue for fares." },
      { from: 3, to: 4, clue: "A truck driver moves freight from depot to depot." },
      { from: 4, to: 5, clue: "A bus driver follows the route and the schedule." },
      { from: 6, to: 7, clue: "A delivery route strings many stops into one run." },
      { from: 7, to: 8, clue: "A route is made up of planned stops." },
      { from: 0, to: 3, clue: "The cab is the front section of a truck." },
      { from: 1, to: 4, clue: "A taxi driver works city streets for hire." },
      { from: 2, to: 5, clue: "A stand gives the bus queue a place to gather." },
      { from: 3, to: 6, clue: "A delivery truck drops parcels block by block." },
      { from: 4, to: 7, clue: "A driver follows an assigned route through the city." },
      { from: 5, to: 8, clue: "A bus stop marks where riders board and exit." },
    ],
  },
  {
    solution: [
      { word: "Market", emoji: "🛒" },
      { word: "Town", emoji: "🏘️" },
      { word: "Square", emoji: "◻️" },
      { word: "Food" },
      { word: "Hall", emoji: "🏛️" },
      { word: "Dance" },
      { word: "Street", emoji: "🛣️" },
      { word: "City", emoji: "🌆" },
      { word: "Club", emoji: "🎷" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A town market fills the center on busy days." },
      { from: 1, to: 2, clue: "A town square sits at the civic heart." },
      { from: 3, to: 4, clue: "A food hall gathers many counters under one roof." },
      { from: 4, to: 5, clue: "A dance hall is built for music and movement." },
      { from: 6, to: 7, clue: "A city street stays busy from morning to night." },
      { from: 7, to: 8, clue: "A city club comes alive after dark." },
      { from: 0, to: 3, clue: "A market sells food from produce to prepared meals." },
      { from: 1, to: 4, clue: "Town hall is where local government meets." },
      { from: 2, to: 5, clue: "A square dance is called in sets." },
      { from: 3, to: 6, clue: "Street food is cooked to eat on the go." },
      { from: 4, to: 7, clue: "City hall houses the mayor and city offices." },
      { from: 5, to: 8, clue: "A dance club fills up once the music starts." },
    ],
  },
  {
    solution: [
      { word: "Flower", emoji: "🌸" },
      { word: "Pot", emoji: "🪴" },
      { word: "Holder", emoji: "🧺" },
      { word: "Water" },
      { word: "Bottle", emoji: "🍼" },
      { word: "Brush", emoji: "🪥" },
      { word: "Garden", emoji: "🌿" },
      { word: "Hose", emoji: "🚿" },
      { word: "Rack", emoji: "🗄️" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A flower pot gives roots a home." },
      { from: 1, to: 2, clue: "A plant pot can sit inside a decorative holder." },
      { from: 3, to: 4, clue: "A water bottle goes anywhere the day gets long." },
      { from: 4, to: 5, clue: "A bottle brush is built to clean what your hand cannot reach." },
      { from: 6, to: 7, clue: "A garden hose is the quick answer to thirsty beds." },
      { from: 7, to: 8, clue: "A hose rack keeps the coil from turning into a mess." },
      { from: 0, to: 3, clue: "Water keeps flowers alive and upright." },
      { from: 3, to: 6, clue: "Water turns a dry garden back into growth." },
      { from: 1, to: 4, clue: "A bottle can water a small pot in a pinch." },
      { from: 4, to: 7, clue: "A hose can fill a bottle in seconds." },
      { from: 2, to: 5, clue: "A brush holder keeps sink-side clutter contained." },
      { from: 5, to: 8, clue: "A rack can hold brushes so they dry cleanly." },
    ],
  },
  {
    solution: [
      { word: "Bus", emoji: "🚌" },
      { word: "Driver", emoji: "🧑‍✈️" },
      { word: "Seat" },
      { word: "Station", emoji: "🚉" },
      { word: "Train", emoji: "🚆" },
      { word: "Coach", emoji: "🚞" },
      { word: "Rail" },
      { word: "Track" },
      { word: "Team", emoji: "👥" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A bus driver keeps the route moving." },
      { from: 1, to: 2, clue: "The driver sits in the front seat." },
      { from: 3, to: 4, clue: "A train station is where passengers board." },
      { from: 4, to: 5, clue: "A coach is one car of a train." },
      { from: 6, to: 7, clue: "Rails are laid along the track." },
      { from: 7, to: 8, clue: "A track team trains for running events." },
      { from: 0, to: 3, clue: "A bus station gathers many routes in one place." },
      { from: 1, to: 4, clue: "A train driver controls the engine and brakes." },
      { from: 2, to: 5, clue: "A coach seat folds down for the journey." },
      { from: 3, to: 6, clue: "A rail station serves trains instead of cars." },
      { from: 4, to: 7, clue: "A train runs on track, not on roads." },
      { from: 5, to: 8, clue: "A coach trains the team." },
    ],
  },
  // Puzzle 13 — Star/Sun/Day/Moon/Light/Night/Stone/Head/Over
  {
    solution: [
      { word: "Star", emoji: "⭐" },
      { word: "Sun", emoji: "☀️" },
      { word: "Day", emoji: "🌤️" },
      { word: "Moon", emoji: "🌕" },
      { word: "Light", emoji: "💡" },
      { word: "Night" },
      { word: "Stone", emoji: "🪨" },
      { word: "Head", emoji: "🗣️" },
      { word: "Over", emoji: "🔁" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Both illuminate the sky from above." },
      { from: 1, to: 2, clue: "The first one names this part of the week." },
      { from: 3, to: 4, clue: "One bathes the night in silver." },
      { from: 4, to: 5, clue: "These two sound the same at bedtime." },
      { from: 6, to: 7, clue: "A grave marker keeps the memory." },
      { from: 7, to: 8, clue: "Costs that pile up quietly above you." },
      { from: 0, to: 3, clue: "Both shine after dark." },
      { from: 3, to: 6, clue: "A gem that glows with an inner light." },
      { from: 1, to: 4, clue: "Floods through the window at dawn." },
      { from: 4, to: 7, clue: "One cuts through the dark on the road." },
      { from: 2, to: 5, clue: "They split the clock in half." },
      { from: 5, to: 8, clue: "Everything changes while you sleep." },
    ],
  },
  // Puzzle 14 — Bone/Stone/Work/Tail/Head/Foot/Spin/Pin/Ball
  {
    solution: [
      { word: "Bone", emoji: "🦴" },
      { word: "Stone", emoji: "🪨" },
      { word: "Work", emoji: "🔨" },
      { word: "Tail" },
      { word: "Head", emoji: "🗣️" },
      { word: "Foot" },
      { word: "Spin", emoji: "🌀" },
      { word: "Pin", emoji: "📌" },
      { word: "Ball" },
    ],
    edges: [
      { from: 0, to: 1, clue: "These two rhyme and both feel rock-hard." },
      { from: 1, to: 2, clue: "Masonry that lasts for centuries." },
      { from: 3, to: 4, clue: "Flip a coin to choose between these two." },
      { from: 4, to: 5, clue: "Both are body parts you can count on." },
      { from: 6, to: 7, clue: "These two rhyme — one turns, the other sticks." },
      { from: 7, to: 8, clue: "A machine that bounces off every bumper." },
      { from: 0, to: 3, clue: "It aches after every hard fall." },
      { from: 3, to: 6, clue: "A spiral out of control." },
      { from: 1, to: 4, clue: "A grave marker keeps the memory." },
      { from: 4, to: 7, clue: "Impossibly small — the tip of one." },
      { from: 2, to: 5, clue: "Quick moves win the fight." },
      { from: 5, to: 8, clue: "The most popular sport on the planet." },
    ],
  },
  // Puzzle 15 — Foot/Head/Tail/Work/Stone/Bone/Fire/Wall/Dry
  {
    solution: [
      { word: "Foot" },
      { word: "Head", emoji: "🗣️" },
      { word: "Tail" },
      { word: "Work", emoji: "🔨" },
      { word: "Stone", emoji: "🪨" },
      { word: "Bone", emoji: "🦴" },
      { word: "Fire" },
      { word: "Wall", emoji: "🧱" },
      { word: "Dry", emoji: "🏜️" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Both are body parts — one thinks, the other walks." },
      { from: 1, to: 2, clue: "Flip a coin to choose between these two." },
      { from: 3, to: 4, clue: "Masonry that lasts for centuries." },
      { from: 4, to: 5, clue: "These two rhyme and both feel rock-hard." },
      { from: 6, to: 7, clue: "One blocks the intruders from getting through." },
      { from: 7, to: 8, clue: "One hides the studs in a house." },
      { from: 0, to: 3, clue: "Quick moves win the fight." },
      { from: 3, to: 6, clue: "Lights up the sky with a bang." },
      { from: 1, to: 4, clue: "A grave marker keeps the memory." },
      { from: 4, to: 7, clue: "One blocks the path completely." },
      { from: 2, to: 5, clue: "It aches after every hard fall." },
      { from: 5, to: 8, clue: "Not a drop remains." },
    ],
  },
  // Puzzle 16 — Moon/Light/Night/Stone/Head/Over/Bone/Tail/Coat
  {
    solution: [
      { word: "Moon", emoji: "🌕" },
      { word: "Light", emoji: "💡" },
      { word: "Night" },
      { word: "Stone", emoji: "🪨" },
      { word: "Head", emoji: "🗣️" },
      { word: "Over", emoji: "🔁" },
      { word: "Bone", emoji: "🦴" },
      { word: "Tail" },
      { word: "Coat" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Silver glow that makes everything shimmer." },
      { from: 1, to: 2, clue: "These two sound the same at bedtime." },
      { from: 3, to: 4, clue: "A grave marker keeps the memory." },
      { from: 4, to: 5, clue: "Costs that pile up quietly above you." },
      { from: 6, to: 7, clue: "It aches after every hard fall." },
      { from: 7, to: 8, clue: "The formal choice with long tails." },
      { from: 0, to: 3, clue: "A gem that glows with an inner light." },
      { from: 3, to: 6, clue: "These two rhyme and both feel rock-hard." },
      { from: 1, to: 4, clue: "One cuts through the dark on the road." },
      { from: 4, to: 7, clue: "Flip a coin to choose between these two." },
      { from: 2, to: 5, clue: "Everything changes while you sleep." },
      { from: 5, to: 8, clue: "One braves the weather outside." },
    ],
  },
  ...REVIEW_STANDARD_BATCH_F,
].map((puzzle, index) => applyWordEmojis(applyPuzzleGeneration(puzzle, index)));

const PRACTICE_EXCLUDED_PUZZLE_INDICES = new Set([5, 12]);

export const PRACTICE_PUZZLES: Puzzle[] = [
  ...PUZZLES.filter((_, index) => !PRACTICE_EXCLUDED_PUZZLE_INDICES.has(index)),
];

const BASE_HARD_PRACTICE_PUZZLES: Puzzle[] = [
  {
    solution: [
      { word: "Score", emoji: "🎯" },
      { word: "Board" },
      { word: "Room" },
      { word: "Card" },
      { word: "Game", emoji: "🎮" },
      { word: "Night" },
      { word: "Business", emoji: "💼" },
      { word: "Plan", emoji: "📝" },
      { word: "Flight", emoji: "✈️" },
    ],
    edges: [
      { from: 0, to: 1, clue: "The ledger of who is winning." },
      { from: 1, to: 2, clue: "Where agendas get serious." },
      { from: 3, to: 4, clue: "Deal, then play." },
      { from: 4, to: 5, clue: "Friday ritual with rules and snacks." },
      { from: 6, to: 7, clue: "The pitch deck's bones." },
      { from: 7, to: 8, clue: "Pilots file one before takeoff." },
      { from: 0, to: 3, clue: "Golf's running tally." },
      { from: 3, to: 6, clue: "Traded at the first handshake." },
      { from: 1, to: 4, clue: "Chess or Monopoly fits here." },
      { from: 4, to: 7, clue: "What a coach writes before kickoff." },
      { from: 2, to: 5, clue: "The billing unit at a hotel." },
      { from: 5, to: 8, clue: "The red-eye across the country." },
    ],
  },
  {
    solution: [
      { word: "Bag", emoji: "🛍️" },
      { word: "Tea" },
      { word: "Break", emoji: "⏸️" },
      { word: "Paper", emoji: "📄" },
      { word: "Cup", emoji: "🥤" },
      { word: "Coffee", emoji: "☕" },
      { word: "Plate", emoji: "🍽️" },
      { word: "Cake", emoji: "🍰" },
      { word: "Mug", emoji: "🍺" },
    ],
    edges: [
      { from: 0, to: 1, clue: "What releases the leaves in hot water." },
      { from: 1, to: 2, clue: "The civilized eleven-o'clock pause." },
      { from: 3, to: 4, clue: "Disposable takeaway staple." },
      { from: 4, to: 5, clue: "A black cup, please." },
      { from: 6, to: 7, clue: "The flat dish that catches every slice." },
      { from: 7, to: 8, clue: "Microwave dessert in one vessel." },
      { from: 0, to: 3, clue: "What your groceries arrive in." },
      { from: 3, to: 6, clue: "The picnic version of dinnerware." },
      { from: 1, to: 4, clue: "The saucer's partner." },
      { from: 4, to: 7, clue: "Frosted single-serving." },
      { from: 2, to: 5, clue: "The mid-morning ritual every office honors." },
      { from: 5, to: 8, clue: "Where the hot drink lives." },
    ],
  },
  {
    solution: [
      { word: "Face", emoji: "😐" },
      { word: "Time" },
      { word: "Bomb", emoji: "💣" },
      { word: "Card" },
      { word: "Show", emoji: "🎭" },
      { word: "Dog" },
      { word: "Game" },
      { word: "Point", emoji: "📍" },
      { word: "Guard" },
    ],
    edges: [
      { from: 0, to: 1, clue: "What you check on your wrist between meetings." },
      { from: 1, to: 2, clue: "The ticking cliché in every thriller." },
      { from: 3, to: 4, clue: "The table at the convention with one seller behind it." },
      { from: 4, to: 5, clue: "Best in Breed at the Westminster event." },
      { from: 6, to: 7, clue: "The serve that could end it." },
      { from: 7, to: 8, clue: "Runs the offense from the top of the key." },
      { from: 0, to: 3, clue: "A jack, queen, or king in the deck." },
      { from: 3, to: 6, clue: "Bridge or poker fits here." },
      { from: 1, to: 4, clue: "Cue the announcer: it is now." },
      { from: 4, to: 7, clue: "The moment of a performance everyone remembers." },
      { from: 2, to: 5, clue: "K-9 unit at the airport search." },
      { from: 5, to: 8, clue: "Barks at anyone who approaches the yard." },
    ],
  },
  {
    solution: [
      { word: "Ticket", emoji: "🎫" },
      { word: "Zoo", emoji: "🦁" },
      { word: "Animal", emoji: "🐾" },
      { word: "Gate" },
      { word: "Keeper", emoji: "🧑‍🌾" },
      { word: "Book", emoji: "📘" },
      { word: "Front", emoji: "🏁" },
      { word: "House" },
      { word: "Guest", emoji: "🧳" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Admits one, animals beyond." },
      { from: 1, to: 2, clue: "The exhibit behind the enclosure." },
      { from: 3, to: 4, clue: "Decides who gets through the entrance." },
      { from: 4, to: 5, clue: "Tracks the accounts on the ledger." },
      { from: 6, to: 7, clue: "The lobby side of theater operations." },
      { from: 7, to: 8, clue: "The overnight visitor with a suitcase." },
      { from: 0, to: 3, clue: "Punch-through at entry." },
      { from: 3, to: 6, clue: "The main entrance to the property." },
      { from: 1, to: 4, clue: "Feeds the lions in the morning." },
      { from: 4, to: 7, clue: "Cleans the rooms and makes the beds." },
      { from: 2, to: 5, clue: "The species pictorial on the shelf." },
      { from: 5, to: 8, clue: "Signed on arrival, with a short note." },
    ],
  },
  {
    solution: [
      { word: "River", emoji: "🏞️" },
      { word: "Ferry", emoji: "⛴️" },
      { word: "Boat", emoji: "🚤" },
      { word: "Harbor", emoji: "⚓" },
      { word: "Dock", emoji: "🪝" },
      { word: "Crane", emoji: "🏗️" },
      { word: "Cargo", emoji: "📦" },
      { word: "Ship", emoji: "🚢" },
      { word: "Operator", emoji: "🕹️" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Crossing the current with cars aboard." },
      { from: 1, to: 2, clue: "The car-and-people vessel." },
      { from: 3, to: 4, clue: "Where the tugs tie up." },
      { from: 4, to: 5, clue: "The container lifter on the wharf." },
      { from: 6, to: 7, clue: "Container carrier across the Pacific." },
      { from: 7, to: 8, clue: "Runs the commercial fleet." },
      { from: 0, to: 3, clue: "The Thames and the Tyne each empty into a working one." },
      { from: 3, to: 6, clue: "Inbound containers stacked on the quayside." },
      { from: 1, to: 4, clue: "Terminal for the floating bus." },
      { from: 4, to: 7, clue: "The vessel at rest alongside the quay." },
      { from: 2, to: 5, clue: "Small hull lifted clear of the water." },
      { from: 5, to: 8, clue: "In the high cab above the yard." },
    ],
  },
  ...REVIEW_HARD_BATCH_C,
].map(applyWordEmojis);

export const HARD_PRACTICE_PUZZLES: Puzzle[] = BASE_HARD_PRACTICE_PUZZLES;

export function getPracticePuzzle(id: number): Puzzle | undefined {
  return PRACTICE_PUZZLES[id - 1];
}

export function getHardPracticePuzzle(id: number): Puzzle | undefined {
  return HARD_PRACTICE_PUZZLES[id - 1];
}

export function getPracticePuzzleCount(): number {
  return PRACTICE_PUZZLES.length;
}

export function getHardPracticePuzzleCount(): number {
  return HARD_PRACTICE_PUZZLES.length;
}
