import type { Puzzle } from "./types";

const DEFAULT_WORD_EMOJI = "✨";

const WORD_EMOJIS: Record<string, string> = {
  Alarm: "🚨",
  Ball: "⚽",
  Band: "🎸",
  Bench: "🪑",
  Board: "🧩",
  Boil: "♨️",
  Box: "📦",
  Button: "🔘",
  Car: "🚗",
  Card: "🃏",
  Case: "💼",
  Clear: "✨",
  Clock: "🕐",
  Coast: "🏖️",
  Coat: "🧥",
  Crown: "👑",
  Dance: "💃",
  Dog: "🐕",
  Drill: "🛠️",
  Drum: "🥁",
  Elephant: "🐘",
  Escape: "🏃",
  Fairy: "🧚",
  Fire: "🔥",
  Floor: "🪩",
  Food: "🍽️",
  Foot: "🦶",
  Game: "🎮",
  Gate: "🚪",
  Green: "🟩",
  Guard: "💂",
  Hand: "✋",
  Horse: "🐎",
  House: "🏠",
  King: "🤴",
  Life: "🌱",
  Line: "➖",
  Locker: "🔒",
  Man: "👨",
  Memory: "🧠",
  Night: "🌙",
  Owl: "🦉",
  Party: "🎉",
  Plant: "🪴",
  Pocket: "👖",
  Power: "⚡",
  Press: "📰",
  Race: "🏁",
  Rail: "🚆",
  Roll: "🌀",
  Room: "🛋️",
  Sea: "🌊",
  Seat: "💺",
  Service: "🛎️",
  Skin: "🧴",
  Sleeper: "😴",
  Snow: "❄️",
  Step: "👣",
  Stick: "🪵",
  Storm: "⛈️",
  Style: "🎨",
  Suit: "🤵",
  Tail: "🐒",
  Tale: "📖",
  Tea: "🍵",
  Thunder: "🌩️",
  Tide: "🌊",
  Tooth: "🦷",
  Top: "🔝",
  Tower: "🗼",
  Track: "🛤️",
  Tree: "🌳",
  Trunk: "🧳",
  Up: "⬆️",
  Vice: "🗜️",
  Watch: "⌚",
  Water: "💧",
};

function applyWordEmojis(puzzle: Puzzle): Puzzle {
  return {
    ...puzzle,
    solution: puzzle.solution.map((item) => ({
      ...item,
      emoji: item.emoji ?? WORD_EMOJIS[item.word] ?? DEFAULT_WORD_EMOJI,
    })),
  };
}

export const PUZZLES: Puzzle[] = [
  {
    solution: [
      { word: "Stand", emoji: "🧍" },
      { word: "Up" },
      { word: "Hill", emoji: "⛰️" },
      { word: "Sit", emoji: "🪑" },
      { word: "Down", emoji: "⬇️" },
      { word: "Town", emoji: "🏘️" },
      { word: "Lie", emoji: "🛌" },
      { word: "Low", emoji: "📉" },
      { word: "Land", emoji: "🏞️" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A standup comic lives or dies by the next punch line." },
      { from: 1, to: 2, clue: "An uphill stretch of road burns the calves fastest." },
      { from: 3, to: 4, clue: "A sit-down dinner settles everyone before the talking starts." },
      { from: 4, to: 5, clue: "Downtown is where the nightlife stacks into its tallest blocks." },
      { from: 6, to: 7, clue: "Lie low until the fuss dies off." },
      { from: 7, to: 8, clue: "Lowland fields flood first when the rivers swell." },
      { from: 0, to: 3, clue: "Stand and sit are the pair every classroom drills all day." },
      { from: 3, to: 6, clue: "Sit a while or lie flat — both are postures a tired body picks." },
      { from: 1, to: 4, clue: "Up and down run every scale, from moods to markets." },
      { from: 4, to: 7, clue: "Keep it on the down low and no one needs to know." },
      { from: 2, to: 5, clue: "A hill town earns its views by making visitors climb for them." },
      { from: 5, to: 8, clue: "Town gives way to open land the moment the pavement ends." },
    ],
  },
  {
    solution: [
      { word: "Car" },
      { word: "Trunk" },
      { word: "Elephant" },
      { word: "Race" },
      { word: "Suit" },
      { word: "Memory" },
      { word: "Track" },
      { word: "Case" },
      { word: "Card" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Cars have trunks." },
      { from: 1, to: 2, clue: "Elephants are famous for theirs." },
      { from: 3, to: 4, clue: "A race suit belongs on a track." },
      { from: 4, to: 5, clue: "Card suits live in memory if you play enough." },
      { from: 6, to: 7, clue: "A case can be tracked." },
      { from: 7, to: 8, clue: "A card case stores the deck." },
      { from: 0, to: 3, clue: "A car race is the obvious pairing." },
      { from: 3, to: 6, clue: "A race track completes the circuit." },
      { from: 1, to: 4, clue: "A trunk can count as a kind of suit or case." },
      { from: 4, to: 7, clue: "A suitcase rolls through the airport." },
      { from: 2, to: 5, clue: "Elephants have the reputation memory wants." },
      { from: 5, to: 8, clue: "A memory card stores the lot." },
    ],
  },
  {
    solution: [
      { word: "Paper", emoji: "📄" },
      { word: "Chain", emoji: "⛓️" },
      { word: "Dog" },
      { word: "Clip", emoji: "📎" },
      { word: "Mail", emoji: "✉️" },
      { word: "Tag", emoji: "🏷️" },
      { word: "Board" },
      { word: "Room" },
      { word: "Service" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A paper chain is a classic classroom decoration." },
      { from: 1, to: 2, clue: "A dog chain keeps a pet from wandering off." },
      { from: 3, to: 4, clue: "A clip can hold a small pile of mail together." },
      { from: 4, to: 5, clue: "A mailing tag travels with the parcel." },
      { from: 6, to: 7, clue: "A boardroom is where the meeting usually starts." },
      { from: 7, to: 8, clue: "Room service brings the tray to your door." },
      { from: 0, to: 3, clue: "A paper clip is the obvious desk pairing." },
      { from: 3, to: 6, clue: "A clipboard gives paper a firm backing." },
      { from: 1, to: 4, clue: "Chain mail is the armored phrase hiding here." },
      { from: 4, to: 7, clue: "A mail room keeps office deliveries sorted." },
      { from: 2, to: 5, clue: "A dog tag hangs from a collar or uniform." },
      { from: 5, to: 8, clue: "A service tag records repair or inspection work." },
    ],
  },
  {
    solution: [
      { word: "Fire" },
      { word: "Alarm" },
      { word: "Button" },
      { word: "Drill" },
      { word: "Press" },
      { word: "Box" },
      { word: "Vice" },
      { word: "Bench" },
      { word: "Seat" },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        clue: "A fire alarm wants your attention immediately.",
      },
      { from: 1, to: 2, clue: "You hit the alarm button in a hurry." },
      { from: 3, to: 4, clue: "A drill press belongs in a workshop." },
      { from: 4, to: 5, clue: "A press box hovers over the field." },
      { from: 6, to: 7, clue: "A bench vice bolts to the workbench." },
      { from: 7, to: 8, clue: "A bench seat runs the width of the row." },
      { from: 0, to: 3, clue: "A fire drill is all practice and no flames." },
      { from: 3, to: 6, clue: "A vice steadies the piece beneath the drill." },
      { from: 1, to: 4, clue: "You press the alarm to trigger it." },
      {
        from: 4,
        to: 7,
        clue: "A bench press does not feel optional halfway through.",
      },
      { from: 2, to: 5, clue: "A button box can store buttons or controls." },
      { from: 5, to: 8, clue: "A box seat sits off to the side." },
    ],
  },
  {
    solution: [
      { word: "Apple", emoji: "🍎" },
      { word: "Tree" },
      { word: "House" },
      { word: "Pie", emoji: "🥧" },
      { word: "Dish", emoji: "🍽️" },
      { word: "Soap", emoji: "🧼" },
      { word: "Cider", emoji: "🍎🥤" },
      { word: "Press" },
      { word: "Box" },
    ],
    edges: [
      { from: 0, to: 1, clue: "An apple tree earns its keep every autumn." },
      { from: 1, to: 2, clue: "A tree house is childhood architecture at its best." },
      { from: 3, to: 4, clue: "A pie dish gives the crust its shape." },
      { from: 4, to: 5, clue: "Dish soap belongs exactly where the plates pile up." },
      { from: 6, to: 7, clue: "A cider press turns fruit into the drink." },
      { from: 7, to: 8, clue: "A press box sits above the field or court." },
      { from: 0, to: 3, clue: "Apple pie is the familiar dessert phrase here." },
      { from: 3, to: 6, clue: "Pie and cider are a classic apple-season pairing." },
      { from: 1, to: 4, clue: "A dish of fruit pulled from the tree is a picnic basic." },
      { from: 4, to: 7, clue: "A pressed dish gets squeezed flat, from panini to quesadilla." },
      { from: 2, to: 5, clue: "A bar of soap belongs in every house." },
      { from: 5, to: 8, clue: "A soapbox is the old-fashioned platform for a loud opinion." },
    ],
  },
  {
    solution: [
      { word: "Tea" },
      { word: "Green" },
      { word: "Power" },
      { word: "Tree" },
      { word: "House" },
      { word: "Plant" },
      { word: "Line" },
      { word: "Party" },
      { word: "Food" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Green tea is the gentler cup." },
      { from: 1, to: 2, clue: "Green power comes from cleaner sources." },
      { from: 3, to: 4, clue: "A tree house belongs above ground level." },
      { from: 4, to: 5, clue: "A houseplant lives indoors." },
      {
        from: 6,
        to: 7,
        clue: "A party line once shared a neighborhood phone.",
      },
      { from: 7, to: 8, clue: "Party food disappears first." },
      { from: 0, to: 3, clue: "The tea tree lends its name to the oil." },
      { from: 3, to: 6, clue: "A tree line marks where growth gives up." },
      {
        from: 1,
        to: 4,
        clue: "Greenhouse is the compound hiding in plain sight.",
      },
      { from: 4, to: 7, clue: "A house party gets louder than intended." },
      { from: 2, to: 5, clue: "A power plant makes the grid hum." },
      { from: 5, to: 8, clue: "Plant food keeps the leaves honest." },
    ],
  },
  {
    solution: [
      { word: "Door", emoji: "🚪" },
      { word: "Lock", emoji: "🔒" },
      { word: "Bike", emoji: "🚲" },
      { word: "Bell", emoji: "🔔" },
      { word: "Chain", emoji: "⛓️" },
      { word: "Ring", emoji: "💍" },
      { word: "Tower" },
      { word: "Guard" },
      { word: "Tone", emoji: "🎵" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A door lock is the first layer of security." },
      { from: 1, to: 2, clue: "A bike lock matters anywhere theft is easy." },
      { from: 3, to: 4, clue: "A bell chain gives you something to pull." },
      { from: 4, to: 5, clue: "A chain ring sits at the heart of a bicycle drivetrain." },
      { from: 6, to: 7, clue: "A tower guard watches from the high point." },
      { from: 7, to: 8, clue: "A guard's tone usually tells you whether to come closer or move along." },
      { from: 0, to: 3, clue: "A doorbell announces whoever is outside." },
      { from: 3, to: 6, clue: "A bell tower is built to be heard across town." },
      { from: 1, to: 4, clue: "A lock and chain together secure a gate or locker." },
      { from: 4, to: 7, clue: "A chain guard keeps grease and teeth away from clothing." },
      { from: 2, to: 5, clue: "A bike bell is a small brass ring on the bars." },
      { from: 5, to: 8, clue: "A ringtone is the sound your phone picks for callers." },
    ],
  },
  {
    solution: [
      { word: "Tower" },
      { word: "Power" },
      { word: "Horse" },
      { word: "Water" },
      { word: "Plant" },
      { word: "Food" },
      { word: "Gate" },
      { word: "House" },
      { word: "Dog" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A power tower rises over transmission lines." },
      { from: 1, to: 2, clue: "Horsepower measures what the engine can do." },
      { from: 3, to: 4, clue: "A water plant filters what the city drinks." },
      { from: 4, to: 5, clue: "Plant food keeps roots ambitious." },
      { from: 6, to: 7, clue: "A gatehouse keeps the entrance honest." },
      { from: 7, to: 8, clue: "A doghouse is where mistakes get remembered." },
      { from: 0, to: 3, clue: "A water tower is a skyline landmark." },
      {
        from: 3,
        to: 6,
        clue: "Watergate became a word bigger than the building.",
      },
      { from: 1, to: 4, clue: "A power plant supplies the region." },
      { from: 4, to: 7, clue: "A houseplant survives by the window." },
      { from: 2, to: 5, clue: "Horse food is measured by the scoop." },
      { from: 5, to: 8, clue: "Dog food is never marketed to cats." },
    ],
  },
  {
    solution: [
      { word: "Man" },
      { word: "Foot" },
      { word: "Locker" },
      { word: "Snow" },
      { word: "Ball" },
      { word: "Room" },
      { word: "Board" },
      { word: "Game" },
      { word: "Escape" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A footman serves the household." },
      { from: 1, to: 2, clue: "A footlocker keeps kit in one place." },
      { from: 3, to: 4, clue: "A snowball grows if you keep rolling it." },
      { from: 4, to: 5, clue: "A ballroom invites a formal spin." },
      { from: 6, to: 7, clue: "A board game belongs on the table." },
      { from: 7, to: 8, clue: "An escape game works best under pressure." },
      { from: 0, to: 3, clue: "A snowman is assembled in the cold." },
      { from: 3, to: 6, clue: "A snowboard takes the slope sideways." },
      { from: 1, to: 4, clue: "Football is the obvious collision." },
      { from: 4, to: 7, clue: "A ball game can turn with one swing." },
      { from: 2, to: 5, clue: "A locker room is all echoes and benches." },
      { from: 5, to: 8, clue: "An escape room rewards calm minds." },
    ],
  },
  {
    solution: [
      { word: "Sea" },
      { word: "Life" },
      { word: "Style" },
      { word: "Coast" },
      { word: "Line" },
      { word: "Dance" },
      { word: "Clear" },
      { word: "Up" },
      { word: "Step" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Sea life keeps the reef busy." },
      { from: 1, to: 2, clue: "Lifestyle choices add up." },
      { from: 3, to: 4, clue: "A coastline is where maps get interesting." },
      { from: 4, to: 5, clue: "A line dance keeps the formation neat." },
      { from: 6, to: 7, clue: "Clear up the mess before you leave." },
      { from: 7, to: 8, clue: "Step up and take the turn." },
      {
        from: 0,
        to: 3,
        clue: "The seacoast is where land negotiates with water.",
      },
      { from: 3, to: 6, clue: "When the coast is clear, move." },
      { from: 1, to: 4, clue: "A lifeline is not optional when it matters." },
      { from: 4, to: 7, clue: "Line up and keep it orderly." },
      { from: 2, to: 5, clue: "Dance style changes with the decade." },
      { from: 5, to: 8, clue: "A dance step is learned one beat at a time." },
    ],
  },
  {
    solution: [
      { word: "Watch" },
      { word: "Night" },
      { word: "Sleeper" },
      { word: "Dog" },
      { word: "Guard" },
      { word: "Rail" },
      { word: "Sea" },
      { word: "Coast" },
      { word: "Line" },
    ],
    edges: [
      { from: 0, to: 1, clue: "The night watch belongs to the dark hours." },
      { from: 1, to: 2, clue: "A night sleeper takes the overnight route." },
      { from: 3, to: 4, clue: "A guard dog discourages bad ideas." },
      { from: 4, to: 5, clue: "A guard rail keeps the edge negotiable." },
      { from: 6, to: 7, clue: "The seacoast is the border with weather." },
      { from: 7, to: 8, clue: "A coastline is traced, never rushed." },
      { from: 0, to: 3, clue: "A watchdog notices what the room missed." },
      { from: 3, to: 6, clue: "A sea dog has spent time on rough water." },
      { from: 1, to: 4, clue: "A night guard owns the empty building." },
      { from: 4, to: 7, clue: "The coast guard arrives with authority." },
      { from: 2, to: 5, clue: "A rail sleeper lies beneath the track." },
      { from: 5, to: 8, clue: "A rail line runs farther than it seems." },
    ],
  },
  {
    solution: [
      { word: "Hotel", emoji: "🏨" },
      { word: "Bell", emoji: "🔔" },
      { word: "Desk", emoji: "🛎️" },
      { word: "Mail", emoji: "✉️" },
      { word: "Room" },
      { word: "Service" },
      { word: "Box" },
      { word: "Office", emoji: "🏢" },
      { word: "Key", emoji: "🔑" },
    ],
    edges: [
      { from: 0, to: 1, clue: "A hotel bell summons help or announces arrival." },
      { from: 1, to: 2, clue: "A bell sits on the front desk in plenty of lobbies." },
      { from: 3, to: 4, clue: "A mail room keeps deliveries from getting lost." },
      { from: 4, to: 5, clue: "Room service is one of the classic hotel perks." },
      { from: 6, to: 7, clue: "The box office handles tickets at the theater." },
      { from: 7, to: 8, clue: "An office key belongs to whoever opens up in the morning." },
      { from: 0, to: 3, clue: "Hotels still receive guest mail and parcels." },
      { from: 3, to: 6, clue: "A mailbox is the standard place letters wait." },
      { from: 1, to: 4, clue: "A bell in the room summons staff for help." },
      { from: 4, to: 7, clue: "A hotel room and an office are both rented spaces with a purpose." },
      { from: 2, to: 5, clue: "A service desk is where questions and problems land first." },
      { from: 5, to: 8, clue: "A service key is the staff version that opens the right doors." },
    ],
  },
].map(applyWordEmojis);

export const PRACTICE_PUZZLES: Puzzle[] = PUZZLES;

export const HARD_PRACTICE_PUZZLES: Puzzle[] = [
  {
    solution: [
      { word: "Tea" },
      { word: "Party" },
      { word: "Floor" },
      { word: "Tree" },
      { word: "Line" },
      { word: "Dance" },
      { word: "Top" },
      { word: "Up" },
      { word: "Step" },
    ],
    edges: [
      { from: 0, to: 1, clue: "One is poured; the other is formed." },
      { from: 1, to: 2, clue: "The celebration claims the boards." },
      { from: 3, to: 4, clue: "Altitude trims the forest into a single edge." },
      { from: 4, to: 5, clue: "Alignment becomes choreography." },
      {
        from: 6,
        to: 7,
        clue: "To replenish is to move the upper bound again.",
      },
      { from: 7, to: 8, clue: "Promotion can be only a stride away." },
      {
        from: 0,
        to: 3,
        clue: "The bottle in the medicine cabinet points to this tree.",
      },
      { from: 3, to: 6, clue: "The highest leaves catch the first weather." },
      {
        from: 1,
        to: 4,
        clue: "This phrase can be propaganda or telephone etiquette.",
      },
      { from: 4, to: 7, clue: "Queue first, argue later." },
      { from: 2, to: 5, clue: "The boards wait for the beat." },
      { from: 5, to: 8, clue: "Patterned movement is built from these." },
    ],
  },
  {
    solution: [
      { word: "Tower" },
      { word: "Power" },
      { word: "Horse" },
      { word: "Water" },
      { word: "Plant" },
      { word: "Food" },
      { word: "Gate" },
      { word: "House" },
      { word: "Dog" },
    ],
    edges: [
      { from: 0, to: 1, clue: "Steel lattice and transmission lore." },
      { from: 1, to: 2, clue: "Engines still borrow the animal." },
      { from: 3, to: 4, clue: "Municipal chemistry in plain sight." },
      { from: 4, to: 5, clue: "A scoop from the garden shelf." },
      { from: 6, to: 7, clue: "An entrance with a building attached." },
      { from: 7, to: 8, clue: "Domestic exile after a mistake." },
      { from: 0, to: 3, clue: "The skyline version of stored pressure." },
      {
        from: 3,
        to: 6,
        clue: "A proper noun that escaped into political shorthand.",
      },
      { from: 1, to: 4, clue: "Generation happens here." },
      { from: 4, to: 7, clue: "A potted resident by the window." },
      { from: 2, to: 5, clue: "Stable rations, not metaphorical ones." },
      {
        from: 5,
        to: 8,
        clue: "The bag in the pantry with the wrong mascot for cats.",
      },
    ],
  },
  {
    solution: [
      { word: "Sea" },
      { word: "Life" },
      { word: "Style" },
      { word: "Coast" },
      { word: "Line" },
      { word: "Dance" },
      { word: "Clear" },
      { word: "Up" },
      { word: "Step" },
    ],
    edges: [
      { from: 0, to: 1, clue: "The reef’s census." },
      { from: 1, to: 2, clue: "Habit dressed as identity." },
      { from: 3, to: 4, clue: "A mapmaker’s favorite boundary." },
      { from: 4, to: 5, clue: "Rows become movement." },
      { from: 6, to: 7, clue: "Resolution after disorder." },
      { from: 7, to: 8, clue: "Advancement with posture." },
      { from: 0, to: 3, clue: "Land and saltwater sharing a noun." },
      { from: 3, to: 6, clue: "Only proceed once this idiom is true." },
      { from: 1, to: 4, clue: "A literal rope, then a metaphor." },
      { from: 4, to: 7, clue: "Arrange yourselves." },
      { from: 2, to: 5, clue: "Form expressed as movement." },
      { from: 5, to: 8, clue: "One unit of choreography." },
    ],
  },
  {
    solution: [
      { word: "Watch" },
      { word: "Night" },
      { word: "Sleeper" },
      { word: "Dog" },
      { word: "Guard" },
      { word: "Rail" },
      { word: "Sea" },
      { word: "Coast" },
      { word: "Line" },
    ],
    edges: [
      { from: 0, to: 1, clue: "The shift no sun attends." },
      { from: 1, to: 2, clue: "A berth with departure and arrival attached." },
      { from: 3, to: 4, clue: "Teeth assigned to perimeter duty." },
      { from: 4, to: 5, clue: "Metal persuasion at the edge." },
      { from: 6, to: 7, clue: "Where the charts start getting jagged." },
      { from: 7, to: 8, clue: "Cartography reduced to a single trace." },
      { from: 0, to: 3, clue: "Suspicion with fur." },
      { from: 3, to: 6, clue: "An old sailor in two short words." },
      {
        from: 1,
        to: 4,
        clue: "The key ring and the flashlight belong to this job.",
      },
      { from: 4, to: 7, clue: "The cutters with authority." },
      {
        from: 2,
        to: 5,
        clue: "The timber beneath the sleepers is not what this means.",
      },
      { from: 5, to: 8, clue: "A route of steel and timetables." },
    ],
  },
  {
    solution: [
      { word: "Tea" },
      { word: "Tree" },
      { word: "Line" },
      { word: "House" },
      { word: "Party" },
      { word: "Food" },
      { word: "Green" },
      { word: "Room" },
      { word: "Service" },
    ],
    edges: [
      {
        from: 0,
        to: 1,
        clue: "The bottle in the bathroom cabinet hints at this pairing.",
      },
      { from: 1, to: 2, clue: "Forests surrender to altitude here." },
      { from: 3, to: 4, clue: "A venue disguised as a living room." },
      { from: 4, to: 5, clue: "Finger food has found its crowd." },
      { from: 6, to: 7, clue: "Backstage, but not yet onstage." },
      { from: 7, to: 8, clue: "The knock at the hotel door." },
      { from: 0, to: 3, clue: "A quiet place built around a hot drink." },
      { from: 3, to: 6, clue: "Read the compound backward if you need to." },
      { from: 1, to: 4, clue: "One shared wire, many listeners." },
      { from: 4, to: 7, clue: "The booked space behind the closed door." },
      { from: 2, to: 5, clue: "Lunch makes this queue inevitable." },
      { from: 5, to: 8, clue: "An industry of aprons, invoices, and speed." },
    ],
  },
].map(applyWordEmojis);

const MS_PER_DAY = 1000 * 60 * 60 * 24;
// 2026-04-08 is Daily #1, making 2026-04-10 Daily #3.
const DAILY_PUZZLE_EPOCH_MS = Date.UTC(2026, 3, 8);

function getDailyPuzzleIndex(timestamp = Date.now()): number {
  const daysSincePuzzleEpoch =
    Math.floor(timestamp / MS_PER_DAY) -
    Math.floor(DAILY_PUZZLE_EPOCH_MS / MS_PER_DAY);
  return Math.max(0, daysSincePuzzleEpoch);
}

export function getTodaysPuzzle(): Puzzle {
  const dailyPuzzleIndex = getDailyPuzzleIndex();
  return PUZZLES[dailyPuzzleIndex % PUZZLES.length];
}

export function getTodaysPuzzleInfo(): {
  puzzle: Puzzle;
  puzzleNumber: number;
  cycleIndex: number;
} {
  const dailyPuzzleIndex = getDailyPuzzleIndex();
  return {
    puzzle: PUZZLES[dailyPuzzleIndex % PUZZLES.length],
    puzzleNumber: dailyPuzzleIndex + 1,
    cycleIndex: dailyPuzzleIndex % PUZZLES.length,
  };
}

export function getPracticePuzzle(id: number): Puzzle | undefined {
  return PRACTICE_PUZZLES[id - 1];
}

export function getHardPracticePuzzle(id: number): Puzzle | undefined {
  return HARD_PRACTICE_PUZZLES[id - 1];
}

export function getPracticePuzzleCount(): number {
  return PRACTICE_PUZZLES.length;
}

export function getHardPracticePuzzleCount(): number {
  return HARD_PRACTICE_PUZZLES.length;
}
