import type { PuzzleDraft } from '../../types';

export const PUZZLE_CATALOG_BACKUP_2026_04_01: PuzzleDraft[] = [
	{
		solution: [
			{ word: 'King' },
			{ word: 'Crown' },
			{ word: 'Tooth' },
			{ word: 'Fairy' },
			{ word: 'Tale' },
			{ word: 'Tail' },
			{ word: 'Coat' },
			{ word: 'Pocket' },
			{ word: 'Watch' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Kings wear crowns' },
			{ from: 1, to: 2, clue: 'A crown goes on a tooth' },
			{ from: 3, to: 4, clue: 'Fairies show up in fairy tales' },
			{ from: 4, to: 5, clue: 'Tale becomes tail if it wags' },
			{ from: 6, to: 7, clue: 'Coats are where pockets happen' },
			{ from: 7, to: 8, clue: 'A pocket watch' },
			{ from: 0, to: 3, clue: 'The tooth fairy' },
			{ from: 3, to: 6, clue: 'A fairy-tale coat (fur coat)' },
			{ from: 1, to: 4, clue: 'Crown tale (a tall tale)' },
			{ from: 4, to: 7, clue: 'A tall tale has pockets of truth' },
			{ from: 2, to: 5, clue: 'Tooth and tail end of something' },
			{ from: 5, to: 8, clue: 'A cat watches its tail' },
		],
	},
	{
		solution: [
			{ word: 'Car' },
			{ word: 'Trunk' },
			{ word: 'Elephant' },
			{ word: 'Race' },
			{ word: 'Suit' },
			{ word: 'Memory' },
			{ word: 'Track' },
			{ word: 'Case' },
			{ word: 'Card' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Cars have trunks' },
			{ from: 1, to: 2, clue: 'Elephants are famous for their trunks' },
			{ from: 3, to: 4, clue: 'A race suit' },
			{ from: 4, to: 5, clue: 'A suit from memory (card games)' },
			{ from: 6, to: 7, clue: 'Tracking a case' },
			{ from: 7, to: 8, clue: 'A card case' },
			{ from: 0, to: 3, clue: 'Car race' },
			{ from: 3, to: 6, clue: 'Race track' },
			{ from: 1, to: 4, clue: 'A trunk suit(case)' },
			{ from: 4, to: 7, clue: 'A suit case' },
			{ from: 2, to: 5, clue: 'An elephant never forgets' },
			{ from: 5, to: 8, clue: 'A memory card' },
		],
	},
	{
		solution: [
			{ word: 'Tower' },
			{ word: 'Guard' },
			{ word: 'Dog' },
			{ word: 'Clock' },
			{ word: 'Night' },
			{ word: 'Watch' },
			{ word: 'Hand' },
			{ word: 'Owl' },
			{ word: 'Band' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A tower guard' },
			{ from: 1, to: 2, clue: 'A guard dog' },
			{ from: 3, to: 4, clue: 'A clock strikes at night' },
			{ from: 4, to: 5, clue: 'The night watch' },
			{ from: 6, to: 7, clue: 'To hand-raise an owl' },
			{ from: 7, to: 8, clue: 'An owl band (leg band)' },
			{ from: 0, to: 3, clue: 'A clock tower' },
			{ from: 3, to: 6, clue: 'A clock hand' },
			{ from: 1, to: 4, clue: 'A night guard' },
			{ from: 4, to: 7, clue: 'A night owl' },
			{ from: 2, to: 5, clue: 'A watch dog' },
			{ from: 5, to: 8, clue: 'A watch band' },
		],
	},
];