import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
	author: 'GitHub Copilot',
	model: 'openai/gpt-5.5-high',
	provider: 'github-copilot',
	generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
	return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_HARD_D: PuzzleDraft[] = [
	{
		solution: [
			{ word: 'Cab', emoji: '🚚' },
			{ word: 'Taxi', emoji: '🚕' },
			{ word: 'Stand', emoji: '🪧' },
			{ word: 'Truck', emoji: '🚛' },
			{ word: 'Driver', emoji: '🧑‍✈️' },
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Delivery', emoji: '📦' },
			{ word: 'Route', emoji: '🗺️' },
			{ word: 'Stop', emoji: '🚏' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The curbside hire answers to either name.' },
			{ from: 1, to: 2, clue: 'This queue spot is where fares find the hired car.' },
			{ from: 3, to: 4, clue: 'Freight has a cab up front and this worker behind the wheel.' },
			{ from: 4, to: 5, clue: 'This worker keeps the big scheduled vehicle moving.' },
			{ from: 6, to: 7, clue: 'Parcels follow this planned run from stop to stop.' },
			{ from: 7, to: 8, clue: 'A planned run is built out of these places to pause.' },
			{ from: 0, to: 3, clue: 'The front compartment of the freight vehicle uses the smaller word.' },
			{ from: 1, to: 4, clue: 'The meter matters only because this person is working the taxi.' },
			{ from: 2, to: 5, clue: 'Riders wait here before the scheduled vehicle arrives.' },
			{ from: 3, to: 6, clue: 'The parcel carrier is the vehicle form of the errand.' },
			{ from: 4, to: 7, clue: 'The worker follows the assigned run through town.' },
			{ from: 5, to: 8, clue: 'The scheduled vehicle pauses where riders board.' },
		],
	},
	{
		solution: [
			{ word: 'City', emoji: '🏙️' },
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Stop', emoji: '🚏' },
			{ word: 'Street', emoji: '🛣️' },
			{ word: 'Sign', emoji: '🚸' },
			{ word: 'Traffic', emoji: '🚦' },
			{ word: 'Bike', emoji: '🚲' },
			{ word: 'Lane', emoji: '↔️' },
			{ word: 'Driver', emoji: '🧑‍✈️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The municipal workhorse carries strangers on one timetable.' },
			{ from: 1, to: 2, clue: 'The public vehicle has a marked place to pause.' },
			{ from: 3, to: 4, clue: 'The roadside label tells you which way you are going.' },
			{ from: 4, to: 5, clue: 'This posted instruction controls the moving stream.' },
			{ from: 6, to: 7, clue: 'Two wheels get their protected strip of pavement here.' },
			{ from: 7, to: 8, clue: 'Staying inside one is basic discipline for the person at the wheel.' },
			{ from: 0, to: 3, clue: 'The urban grid is made from many of these roads.' },
			{ from: 1, to: 4, clue: 'The route number appears on this marker for riders.' },
			{ from: 2, to: 5, clue: 'The red octagon forces the moving stream to wait.' },
			{ from: 3, to: 6, clue: 'This two-wheeler is built for pavement rather than trail.' },
			{ from: 4, to: 7, clue: 'A marker can dedicate one strip to turns, buses, or bikes.' },
			{ from: 5, to: 8, clue: 'The person at the wheel must read the flow ahead.' },
		],
	},
	{
		solution: [
			{ word: 'Police', emoji: '👮' },
			{ word: 'Horse', emoji: '🐎' },
			{ word: 'Shoe', emoji: '👞' },
			{ word: 'Stable', emoji: '🏇' },
			{ word: 'Groom', emoji: '🧑‍🌾' },
			{ word: 'Brush', emoji: '🪮' },
			{ word: 'Race', emoji: '🏁' },
			{ word: 'Track', emoji: '🛤️' },
			{ word: 'Rider', emoji: '🏇' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Mounted patrol makes the animal part of the badge.' },
			{ from: 1, to: 2, clue: 'The metal curve protects the hoof.' },
			{ from: 3, to: 4, clue: 'This caretaker works where the horses live.' },
			{ from: 4, to: 5, clue: 'This caretaker reaches for it before a show or ride.' },
			{ from: 6, to: 7, clue: 'Speed needs an oval or strip built for it.' },
			{ from: 7, to: 8, clue: 'The person in the saddle circles this place during training.' },
			{ from: 0, to: 3, clue: 'The mounted unit keeps its animals in this building.' },
			{ from: 1, to: 4, clue: 'The animal depends on this worker for daily care.' },
			{ from: 2, to: 5, clue: 'Leather footwear gets cleaned by this tool.' },
			{ from: 3, to: 6, clue: 'Fast horses live in the kind of barn named for the event.' },
			{ from: 4, to: 7, clue: 'Before the horse reaches the running surface, this worker gets it ready.' },
			{ from: 5, to: 8, clue: 'After the ride, the person in the saddle may use this on the coat.' },
		],
	},
	{
		solution: [
			{ word: 'River', emoji: '🏞️' },
			{ word: 'Ferry', emoji: '⛴️' },
			{ word: 'Boat', emoji: '🚤' },
			{ word: 'Harbor', emoji: '⚓' },
			{ word: 'Dock', emoji: '🪝' },
			{ word: 'Crane', emoji: '🏗️' },
			{ word: 'Cargo', emoji: '📦' },
			{ word: 'Ship', emoji: '🚢' },
			{ word: 'Operator', emoji: '🕹️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The crossing vessel makes short work of the waterway.' },
			{ from: 1, to: 2, clue: 'The scheduled crossing is made by this kind of vessel.' },
			{ from: 3, to: 4, clue: 'The sheltered port gives vessels this place to tie up.' },
			{ from: 4, to: 5, clue: 'The lifting machine works beside the mooring point.' },
			{ from: 6, to: 7, clue: 'Containers travel overseas on this freight vessel.' },
			{ from: 7, to: 8, clue: 'Commercial vessels need this person or company running them.' },
			{ from: 0, to: 3, clue: 'The waterway can widen into this working port.' },
			{ from: 1, to: 4, clue: 'The crossing vessel noses into this place at each landing.' },
			{ from: 2, to: 5, clue: 'The lifting machine can hoist a small vessel from the water.' },
			{ from: 3, to: 6, clue: 'Freight piles up in this port setting.' },
			{ from: 4, to: 7, clue: 'The large vessel lies alongside this place while loading.' },
			{ from: 5, to: 8, clue: 'The hoist moves only because this person controls it.' },
		],
	},
	{
		solution: [
			{ word: 'Market', emoji: '🛒' },
			{ word: 'Town', emoji: '🏘️' },
			{ word: 'Square', emoji: '◻️' },
			{ word: 'Food', emoji: '🍜' },
			{ word: 'Hall', emoji: '🏛️' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Street', emoji: '🛣️' },
			{ word: 'City', emoji: '🌆' },
			{ word: 'Club', emoji: '🎷' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The busy buying place often sits at the center of this community.' },
			{ from: 1, to: 2, clue: 'The civic open space carries the community word first.' },
			{ from: 3, to: 4, clue: 'Many counters share a roof in this eating place.' },
			{ from: 4, to: 5, clue: 'Music and movement are the point of this public room.' },
			{ from: 6, to: 7, clue: 'The road belongs to the urban grid.' },
			{ from: 7, to: 8, clue: 'After dark, the urban word often pairs with this social venue.' },
			{ from: 0, to: 3, clue: 'Produce and prepared meals make this buying place edible.' },
			{ from: 1, to: 4, clue: 'Local government meets under this familiar civic label.' },
			{ from: 2, to: 5, clue: 'Callers and partners make the geometric word move.' },
			{ from: 3, to: 6, clue: 'Food cooked for eating on the go takes this road word.' },
			{ from: 4, to: 7, clue: 'The mayor and offices live in this civic building.' },
			{ from: 5, to: 8, clue: 'The venue fills when the music is for movement.' },
		],
	},
	{
		solution: [
			{ word: 'Transit', emoji: '🚇' },
			{ word: 'Train', emoji: '🚆' },
			{ word: 'Engine', emoji: '🚂' },
			{ word: 'Police', emoji: '👮' },
			{ word: 'Station', emoji: '🚉' },
			{ word: 'Fire', emoji: '🔥' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Alarm', emoji: '🚨' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The commuter system moves by rail here.' },
			{ from: 1, to: 2, clue: 'The pulling unit gives the rail cars their force.' },
			{ from: 3, to: 4, clue: 'The precinct works from this base.' },
			{ from: 4, to: 5, clue: 'The emergency crew and trucks wait here.' },
			{ from: 6, to: 7, clue: 'The backyard shelter belongs to the pet.' },
			{ from: 7, to: 8, clue: 'This warning system protects the home.' },
			{ from: 0, to: 3, clue: 'The officers patrol platforms and trains in this unit.' },
			{ from: 1, to: 4, clue: 'Passengers board the rail vehicle at this place.' },
			{ from: 2, to: 5, clue: 'The emergency truck carries the same power word.' },
			{ from: 3, to: 6, clue: 'The trained animal works with the badge.' },
			{ from: 4, to: 7, clue: 'The building behind a public-service base carries this older phrase.' },
			{ from: 5, to: 8, clue: 'The warning tells everyone the flames may be real.' },
		],
	},
	{
		solution: [
			{ word: 'School', emoji: '🏫' },
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Route', emoji: '🗺️' },
			{ word: 'Desk', emoji: '🪑' },
			{ word: 'Job', emoji: '💼' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Teacher', emoji: '🧑‍🏫' },
			{ word: 'Aide', emoji: '🙋' },
			{ word: 'Help', emoji: '🆘' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Students know the yellow vehicle by this first word.' },
			{ from: 1, to: 2, clue: 'The vehicle follows a planned string of stops.' },
			{ from: 3, to: 4, clue: 'Indoor work often gets this seated label.' },
			{ from: 4, to: 5, clue: 'Work with the public often carries this label.' },
			{ from: 6, to: 7, clue: 'The classroom adult gets support from this helper.' },
			{ from: 7, to: 8, clue: 'The helper exists because someone needs this.' },
			{ from: 0, to: 3, clue: 'The classroom has this work surface.' },
			{ from: 1, to: 4, clue: 'Driving the vehicle can be the paid work.' },
			{ from: 2, to: 5, clue: 'A scheduled run depends on this maintained operation.' },
			{ from: 3, to: 6, clue: 'The instructor still uses this surface for papers and planning.' },
			{ from: 4, to: 7, clue: 'Support work is exactly what this helper does.' },
			{ from: 5, to: 8, clue: 'The support operation answers when people are stuck.' },
		],
	},
	{
		solution: [
			{ word: 'Bag', emoji: '🛍️' },
			{ word: 'Tea', emoji: '🍵' },
			{ word: 'Break', emoji: '⏸️' },
			{ word: 'Paper', emoji: '📄' },
			{ word: 'Cup', emoji: '🥤' },
			{ word: 'Coffee', emoji: '☕' },
			{ word: 'Plate', emoji: '🍽️' },
			{ word: 'Cake', emoji: '🍰' },
			{ word: 'Mug', emoji: '🍺' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The leaves travel in this little pouch.' },
			{ from: 1, to: 2, clue: 'The hot drink gives a pause its name.' },
			{ from: 3, to: 4, clue: 'The disposable vessel is made from the sheet material.' },
			{ from: 4, to: 5, clue: 'The hot drink is often served in this small vessel.' },
			{ from: 6, to: 7, clue: 'Dessert sits on this flat dish before it disappears.' },
			{ from: 7, to: 8, clue: 'The microwave version bakes dessert in the vessel.' },
			{ from: 0, to: 3, clue: 'This carrying container can be made from the sheet material.' },
			{ from: 1, to: 4, clue: 'The hot drink belongs in this vessel.' },
			{ from: 2, to: 5, clue: 'The other hot drink also gives a pause its name.' },
			{ from: 3, to: 6, clue: 'The party dish is disposable when made from this material.' },
			{ from: 4, to: 7, clue: 'The small cake hides inside the vessel word.' },
			{ from: 5, to: 8, clue: 'The hot drink often lives in the handle-bearing vessel.' },
		],
	},
	{
		solution: [
			{ word: 'Score', emoji: '🎯' },
			{ word: 'Board', emoji: '🧩' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Game', emoji: '🎮' },
			{ word: 'Night', emoji: '🌙' },
			{ word: 'Business', emoji: '💼' },
			{ word: 'Plan', emoji: '📝' },
			{ word: 'Flight', emoji: '✈️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The points become public when they hit this display.' },
			{ from: 1, to: 2, clue: 'The meeting space compresses into one familiar word.' },
			{ from: 3, to: 4, clue: 'The little rectangle can be the whole engine of play.' },
			{ from: 4, to: 5, clue: 'A social evening may be named for tabletop play.' },
			{ from: 6, to: 7, clue: 'The company needs this written strategy before the money arrives.' },
			{ from: 7, to: 8, clue: 'The route through the sky is charted here.' },
			{ from: 0, to: 3, clue: 'The little rectangle records points hole by hole or round by round.' },
			{ from: 1, to: 4, clue: 'The tabletop pastime starts with this flat surface.' },
			{ from: 2, to: 5, clue: 'A rented space can be kept through the dark hours.' },
			{ from: 3, to: 6, clue: 'The wallet rectangle introduces a company or worker.' },
			{ from: 4, to: 7, clue: 'Strategy for play shares a phrase with strategy generally.' },
			{ from: 5, to: 8, clue: 'The red-eye is the after-dark version of this trip.' },
		],
	},
	{
		solution: [
			{ word: 'Road', emoji: '🛣️' },
			{ word: 'Trip', emoji: '🧳' },
			{ word: 'Wire', emoji: '🔌' },
			{ word: 'Stop', emoji: '🛑' },
			{ word: 'Sign', emoji: '🪧' },
			{ word: 'Post', emoji: '📍' },
			{ word: 'Night', emoji: '🌙' },
			{ word: 'Flight', emoji: '✈️' },
			{ word: 'Path', emoji: '🛤️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The vacation begins when the route itself becomes the event.' },
			{ from: 1, to: 2, clue: 'A careless foot discovers this stretched hazard.' },
			{ from: 3, to: 4, clue: 'The red octagon is the command in posted form.' },
			{ from: 4, to: 5, clue: 'Directions become useful when fixed to this upright support.' },
			{ from: 6, to: 7, clue: 'The late departure crosses the sky after dark.' },
			{ from: 7, to: 8, clue: 'The route through the air is this planned line.' },
			{ from: 0, to: 3, clue: 'The pause beside the highway breaks the drive.' },
			{ from: 1, to: 4, clue: 'Travelers read these markers to keep the journey on course.' },
			{ from: 2, to: 5, clue: 'The line is often stretched between upright supports.' },
			{ from: 3, to: 6, clue: 'A long journey may require this overnight pause.' },
			{ from: 4, to: 7, clue: 'Airports display departures on these markers.' },
			{ from: 5, to: 8, clue: 'The marker can show which trail or route to follow.' },
		],
	},
	{
		solution: [
			{ word: 'Sun', emoji: '🌞' },
			{ word: 'Screen', emoji: '📺' },
			{ word: 'Door', emoji: '🚪' },
			{ word: 'Moon', emoji: '🌙' },
			{ word: 'Light', emoji: '💡' },
			{ word: 'Bulb', emoji: '💡' },
			{ word: 'Night', emoji: '🌌' },
			{ word: 'Flight', emoji: '✈️' },
			{ word: 'Path', emoji: '🛤️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The protective lotion borrows the bright word.' },
			{ from: 1, to: 2, clue: 'The ventilating entry keeps bugs outside.' },
			{ from: 3, to: 4, clue: 'The pale glow is named for its source.' },
			{ from: 4, to: 5, clue: 'The glass globe produces the glow.' },
			{ from: 6, to: 7, clue: 'The after-dark departure still has wings.' },
			{ from: 7, to: 8, clue: 'Aircraft follow this planned route through the sky.' },
			{ from: 0, to: 3, clue: 'The bright disc and pale disc trade shifts in the sky.' },
			{ from: 1, to: 4, clue: 'The display produces this glow when powered.' },
			{ from: 2, to: 5, clue: 'The porch fixture often places this globe beside the entry.' },
			{ from: 3, to: 6, clue: 'The pale disc is most at home after dark.' },
			{ from: 4, to: 7, clue: 'Runways use this glow to guide aircraft.' },
			{ from: 5, to: 8, clue: 'Small outdoor lamps use these globes along a walkway.' },
		],
	},
	{
		solution: [
			{ word: 'Band', emoji: '🎸' },
			{ word: 'Stand', emoji: '🪑' },
			{ word: 'Microphone', emoji: '🎤' },
			{ word: 'Sheet', emoji: '📄' },
			{ word: 'Music', emoji: '🎵' },
			{ word: 'Note', emoji: '🎶' },
			{ word: 'Guitar', emoji: '🎸' },
			{ word: 'String', emoji: '🧵' },
			{ word: 'Pick', emoji: '⛏️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Performers can play from this raised place.' },
			{ from: 1, to: 2, clue: 'The support keeps the singer from holding the mic.' },
			{ from: 3, to: 4, clue: 'The printed page tells musicians what to play.' },
			{ from: 4, to: 5, clue: 'The tiny pitch mark is one unit of the larger art.' },
			{ from: 6, to: 7, clue: 'The instrument depends on these stretched lengths.' },
			{ from: 7, to: 8, clue: 'The small tool plucks the stretched length.' },
			{ from: 0, to: 3, clue: 'The performers read from these pages when the chart is not memorized.' },
			{ from: 1, to: 4, clue: 'The page holder takes its name from the art it supports.' },
			{ from: 2, to: 5, clue: 'The singer sends this pitch into the mic.' },
			{ from: 3, to: 6, clue: 'The instrument can have its own printed arrangements.' },
			{ from: 4, to: 7, clue: 'The family of bowed instruments takes this material name.' },
			{ from: 5, to: 8, clue: 'A player can pluck out one pitch with this tool.' },
		],
	},
	{
		solution: [
			{ word: 'Hen', emoji: '🐔' },
			{ word: 'Nest', emoji: '🪺' },
			{ word: 'Egg', emoji: '🥚' },
			{ word: 'Bee', emoji: '🐝' },
			{ word: 'Hive', emoji: '🐝🏠' },
			{ word: 'Honey', emoji: '🍯' },
			{ word: 'Cow', emoji: '🐄' },
			{ word: 'Barn', emoji: '🏚️' },
			{ word: 'Milk', emoji: '🥛' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The bird uses this built place for laying.' },
			{ from: 1, to: 2, clue: 'The shell rests in this built place before breakfast.' },
			{ from: 3, to: 4, clue: 'The insect colony lives in this home.' },
			{ from: 4, to: 5, clue: 'The colony home produces the sweet result.' },
			{ from: 6, to: 7, clue: 'The dairy animal often stands in this farm building.' },
			{ from: 7, to: 8, clue: 'The dairy building points directly to the drink.' },
			{ from: 0, to: 3, clue: 'Both are familiar small farm animals.' },
			{ from: 1, to: 4, clue: 'Both words name animal homes.' },
			{ from: 2, to: 5, clue: 'Both can land on the breakfast table.' },
			{ from: 3, to: 6, clue: 'Both can be kept by people on a farm.' },
			{ from: 4, to: 7, clue: 'Both shelter living creatures.' },
			{ from: 5, to: 8, clue: 'The sweetener dissolves nicely in the warm drink.' },
		],
	},
	{
		solution: [
			{ word: 'Voice', emoji: '🗣️' },
			{ word: 'Mail', emoji: '✉️' },
			{ word: 'Box', emoji: '📦' },
			{ word: 'Text', emoji: '💬' },
			{ word: 'Message', emoji: '📨' },
			{ word: 'Board', emoji: '🪧' },
			{ word: 'Note', emoji: '📝' },
			{ word: 'Pad', emoji: '📓' },
			{ word: 'Paper', emoji: '📄' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The spoken recording waits where callers leave it.' },
			{ from: 1, to: 2, clue: 'Letters sit in this container until collected.' },
			{ from: 3, to: 4, clue: 'The short written phone item is exactly this.' },
			{ from: 4, to: 5, clue: 'Public posts gather on this surface.' },
			{ from: 6, to: 7, clue: 'Quick writing gets bundled into this little tablet.' },
			{ from: 7, to: 8, clue: 'The tablet is made from many sheets.' },
			{ from: 0, to: 3, clue: 'Speaking and typing are two channels for the same thought.' },
			{ from: 1, to: 4, clue: 'Letters carry this from sender to reader.' },
			{ from: 2, to: 5, clue: 'This stiff stock is made from the container word and the surface word.' },
			{ from: 3, to: 6, clue: 'The quick written item can be sent by phone.' },
			{ from: 4, to: 7, clue: 'People jot these on the tablet when memory is not enough.' },
			{ from: 5, to: 8, clue: 'This stiff material names board-like sheets.' },
		],
	},
	{
		solution: [
			{ word: 'Paper', emoji: '📄' },
			{ word: 'Chain', emoji: '⛓️' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'Clip', emoji: '📎' },
			{ word: 'Mail', emoji: '✉️' },
			{ word: 'Tag', emoji: '🏷️' },
			{ word: 'Board', emoji: '🪵' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Service', emoji: '🛎️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The classroom decoration links strips of the sheet material.' },
			{ from: 1, to: 2, clue: 'The restraint keeps the pet from wandering.' },
			{ from: 3, to: 4, clue: 'The fastener can hold letters together.' },
			{ from: 4, to: 5, clue: 'The parcel label travels with the letters or package.' },
			{ from: 6, to: 7, clue: 'The meeting space compresses into one word.' },
			{ from: 7, to: 8, clue: 'The tray arrives at the door under this hotel phrase.' },
			{ from: 0, to: 3, clue: 'The desk fastener is named for the sheet material.' },
			{ from: 3, to: 6, clue: 'The writing surface uses the fastener word in front.' },
			{ from: 1, to: 4, clue: 'Armor once made the links carry the delivery word.' },
			{ from: 4, to: 7, clue: 'Office deliveries are sorted in this space.' },
			{ from: 2, to: 5, clue: 'The pet wears this identifier on its collar.' },
			{ from: 5, to: 8, clue: 'The repair record carries this label.' },
		],
	},
].map(withCurrentGeneration);
