import type { Puzzle } from '../types';

const CURRENT_GENERATION: NonNullable<Puzzle['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: Puzzle): Puzzle {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G2: Puzzle[] = [
  {
    solution: [
      { word: 'Seed', emoji: '🌰' },
      { word: 'Sprout', emoji: '🌱' },
      { word: 'Stem', emoji: '🌿' },
      { word: 'Soil', emoji: '🟫' },
      { word: 'Plant', emoji: '🪴' },
      { word: 'Leaf', emoji: '🍃' },
      { word: 'Worm', emoji: '🪱' },
      { word: 'Garden', emoji: '🏡' },
      { word: 'Flower', emoji: '🌸' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A seed grows into a sprout.' },
      { from: 1, to: 2, clue: 'A sprout has a small stem.' },
      { from: 3, to: 4, clue: 'A plant grows in soil.' },
      { from: 4, to: 5, clue: 'A leaf is part of a plant.' },
      { from: 6, to: 7, clue: 'Worms live in garden soil.' },
      { from: 7, to: 8, clue: 'A garden is planted with flowers.' },
      { from: 0, to: 3, clue: 'Seeds are planted in soil.' },
      { from: 3, to: 6, clue: 'A worm burrows through soil.' },
      { from: 1, to: 4, clue: 'A sprout is a young plant.' },
      { from: 4, to: 7, clue: 'A garden contains plants.' },
      { from: 2, to: 5, clue: 'Leaves grow from a plant stem.' },
      { from: 5, to: 8, clue: 'A flower usually has leaves.' },
    ],
  },
  {
    solution: [
      { word: 'Pencil', emoji: '✏️' },
      { word: 'Paper', emoji: '📄' },
      { word: 'Board', emoji: '🧩' },
      { word: 'Desk', emoji: '🪑' },
      { word: 'Book', emoji: '📖' },
      { word: 'Mark', emoji: '✔️' },
      { word: 'Chair', emoji: '💺' },
      { word: 'Student', emoji: '🧑‍🎓' },
      { word: 'Teacher', emoji: '🧑‍🏫' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A pencil writes on paper.' },
      { from: 1, to: 2, clue: 'Paperboard is thick paper used for covers and boxes.' },
      { from: 3, to: 4, clue: 'A book can sit open on a desk.' },
      { from: 4, to: 5, clue: 'A bookmark marks the place in a book.' },
      { from: 6, to: 7, clue: 'A student sits in a chair.' },
      { from: 7, to: 8, clue: 'A teacher teaches a student.' },
      { from: 0, to: 3, clue: 'A pencil belongs on a desk.' },
      { from: 3, to: 6, clue: 'A desk is often paired with a chair.' },
      { from: 1, to: 4, clue: 'A book is made of paper pages.' },
      { from: 4, to: 7, clue: 'A student reads a book.' },
      { from: 2, to: 5, clue: 'A board can hold a written mark.' },
      { from: 5, to: 8, clue: 'A teacher marks a student paper.' },
    ],
  },
  {
    solution: [
      { word: 'Guitar', emoji: '🎸' },
      { word: 'String', emoji: '🧵' },
      { word: 'Bow', emoji: '🏹' },
      { word: 'Amp', emoji: '🔊' },
      { word: 'Bass', emoji: '🎸' },
      { word: 'Violin', emoji: '🎻' },
      { word: 'Speaker', emoji: '🔈' },
      { word: 'Drum', emoji: '🥁' },
      { word: 'Stick', emoji: '🥢' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A guitar has strings.' },
      { from: 1, to: 2, clue: 'A bowstring is the string of a bow.' },
      { from: 3, to: 4, clue: 'A bass amp makes a bass louder.' },
      { from: 4, to: 5, clue: 'Bass and violin are string instruments.' },
      { from: 6, to: 7, clue: 'Speakers can play the sound of drums.' },
      { from: 7, to: 8, clue: 'A drumstick is used to strike a drum.' },
      { from: 0, to: 3, clue: 'A guitar amp makes a guitar louder.' },
      { from: 3, to: 6, clue: 'An amp sends sound to a speaker.' },
      { from: 1, to: 4, clue: 'A string bass is a large upright bass.' },
      { from: 4, to: 7, clue: 'A bass drum is the deep drum in a kit.' },
      { from: 2, to: 5, clue: 'A violin bow is drawn across violin strings.' },
      { from: 5, to: 8, clue: 'A violin bow is a stick strung with hair.' },
    ],
  },
  {
    solution: [
      { word: 'Chef', emoji: '🧑‍🍳' },
      { word: 'Knife', emoji: '🔪' },
      { word: 'Blade', emoji: '🗡️' },
      { word: 'Cook', emoji: '🍳' },
      { word: 'Pan', emoji: '🥘' },
      { word: 'Handle', emoji: '🧰' },
      { word: 'Stove', emoji: '♨️' },
      { word: 'Heat', emoji: '🔥' },
      { word: 'Flame', emoji: '🔥' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A chef uses a knife.' },
      { from: 1, to: 2, clue: 'A blade is the sharp part of a knife.' },
      { from: 3, to: 4, clue: 'A cook uses a pan.' },
      { from: 4, to: 5, clue: 'A pan has a handle.' },
      { from: 6, to: 7, clue: 'A stove produces heat.' },
      { from: 7, to: 8, clue: 'A flame gives off heat.' },
      { from: 0, to: 3, clue: 'A chef is a professional cook.' },
      { from: 3, to: 6, clue: 'A cook works at a stove.' },
      { from: 1, to: 4, clue: 'A knife and a pan are kitchen tools.' },
      { from: 4, to: 7, clue: 'A pan is heated before food cooks.' },
      { from: 2, to: 5, clue: 'A knife blade is joined to a handle.' },
      { from: 5, to: 8, clue: 'A pan handle keeps hands away from the flame.' },
    ],
  },
  {
    solution: [
      { word: 'Stamp', emoji: '🏷️' },
      { word: 'Mail', emoji: '✉️' },
      { word: 'Route', emoji: '🗺️' },
      { word: 'Envelope', emoji: '✉️' },
      { word: 'Letter', emoji: '💌' },
      { word: 'Carrier', emoji: '📬' },
      { word: 'Flap', emoji: '📨' },
      { word: 'Bag', emoji: '👜' },
      { word: 'Satchel', emoji: '💼' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A stamp is placed on mail.' },
      { from: 1, to: 2, clue: 'A mail route is the path used to deliver mail.' },
      { from: 3, to: 4, clue: 'An envelope holds a letter.' },
      { from: 4, to: 5, clue: 'A letter carrier delivers letters.' },
      { from: 6, to: 7, clue: 'A bag can have a flap that folds over the opening.' },
      { from: 7, to: 8, clue: 'A satchel is a kind of bag.' },
      { from: 0, to: 3, clue: 'A stamp is stuck on an envelope.' },
      { from: 3, to: 6, clue: 'An envelope has a flap.' },
      { from: 1, to: 4, clue: 'A letter is a piece of mail.' },
      { from: 4, to: 7, clue: 'A mailbag carries letters.' },
      { from: 2, to: 5, clue: 'A carrier follows a route.' },
      { from: 5, to: 8, clue: 'A carrier can carry a satchel.' },
    ],
  },
  {
    solution: [
      { word: 'Test', emoji: '🧪' },
      { word: 'Tube', emoji: '🧪' },
      { word: 'Rack', emoji: '🧫' },
      { word: 'Lab', emoji: '🔬' },
      { word: 'Safety', emoji: '⚠️' },
      { word: 'Goggles', emoji: '🥽' },
      { word: 'Coat', emoji: '🥼' },
      { word: 'Pocket', emoji: '👝' },
      { word: 'Lens', emoji: '🔍' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A test tube holds small lab samples.' },
      { from: 1, to: 2, clue: 'A tube rack holds test tubes upright.' },
      { from: 3, to: 4, clue: 'Lab safety rules protect people during experiments.' },
      { from: 4, to: 5, clue: 'Safety goggles protect the eyes.' },
      { from: 6, to: 7, clue: 'A coat can have a pocket.' },
      { from: 7, to: 8, clue: 'A pocket magnifier has a small lens.' },
      { from: 0, to: 3, clue: 'A lab test is performed in a lab.' },
      { from: 3, to: 6, clue: 'A lab coat is worn in a lab.' },
      { from: 1, to: 4, clue: 'A test tube is handled under safety rules.' },
      { from: 4, to: 7, clue: 'Safety gear can be kept in a coat pocket.' },
      { from: 2, to: 5, clue: 'Goggles can rest on a rack between uses.' },
      { from: 5, to: 8, clue: 'Goggles have clear lenses.' },
    ],
  },
  {
    solution: [
      { word: 'Paint', emoji: '🎨' },
      { word: 'Brush', emoji: '🖌️' },
      { word: 'Bristle', emoji: '🪥' },
      { word: 'Canvas', emoji: '🖼️' },
      { word: 'Frame', emoji: '🖼️' },
      { word: 'Hook', emoji: '🪝' },
      { word: 'Gallery', emoji: '🏛️' },
      { word: 'Wall', emoji: '🧱' },
      { word: 'Nail', emoji: '🔩' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A paint brush carries paint.' },
      { from: 1, to: 2, clue: 'A bristle is part of a brush.' },
      { from: 3, to: 4, clue: 'A canvas can be set inside a frame.' },
      { from: 4, to: 5, clue: 'A frame can hang from a hook.' },
      { from: 6, to: 7, clue: 'A gallery wall displays art.' },
      { from: 7, to: 8, clue: 'A nail can be driven into a wall.' },
      { from: 0, to: 3, clue: 'Paint goes on a canvas.' },
      { from: 3, to: 6, clue: 'A gallery displays painted canvases.' },
      { from: 1, to: 4, clue: 'A brush can paint the edge of a frame.' },
      { from: 4, to: 7, clue: 'A frame hangs on a wall.' },
      { from: 2, to: 5, clue: 'A brush bristle can catch on a hook.' },
      { from: 5, to: 8, clue: 'A hook can hang from a nail.' },
    ],
  },
  {
    solution: [
      { word: 'Pen', emoji: '🖊️' },
      { word: 'Ink', emoji: '🖋️' },
      { word: 'Cartridge', emoji: '🧃' },
      { word: 'Paper', emoji: '📄' },
      { word: 'Printer', emoji: '🖨️' },
      { word: 'Tray', emoji: '📥' },
      { word: 'Desk', emoji: '🪑' },
      { word: 'Drawer', emoji: '🗄️' },
      { word: 'Handle', emoji: '🧰' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A pen writes with ink.' },
      { from: 1, to: 2, clue: 'An ink cartridge holds replacement ink.' },
      { from: 3, to: 4, clue: 'A printer prints on paper.' },
      { from: 4, to: 5, clue: 'A printer tray holds paper for a printer.' },
      { from: 6, to: 7, clue: 'A desk drawer stores office supplies.' },
      { from: 7, to: 8, clue: 'A drawer has a handle.' },
      { from: 0, to: 3, clue: 'A pen writes on paper.' },
      { from: 3, to: 6, clue: 'Paper often sits on a desk.' },
      { from: 1, to: 4, clue: 'An ink printer uses ink.' },
      { from: 4, to: 7, clue: 'A printer drawer can hold extra paper.' },
      { from: 2, to: 5, clue: 'A cartridge tray holds a printer cartridge.' },
      { from: 5, to: 8, clue: 'A tray can have a handle.' },
    ],
  },
  {
    solution: [
      { word: 'Swing', emoji: '🌳' },
      { word: 'Chain', emoji: '⛓️' },
      { word: 'Link', emoji: '🔗' },
      { word: 'Slide', emoji: '🛝' },
      { word: 'Ladder', emoji: '🪜' },
      { word: 'Rung', emoji: '🪜' },
      { word: 'Sandbox', emoji: '🏖️' },
      { word: 'Sand', emoji: '🏝️' },
      { word: 'Castle', emoji: '🏰' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A swing can hang from a chain.' },
      { from: 1, to: 2, clue: 'A link is one piece of a chain.' },
      { from: 3, to: 4, clue: 'A slide often has a ladder.' },
      { from: 4, to: 5, clue: 'A rung is one step of a ladder.' },
      { from: 6, to: 7, clue: 'A sandbox is filled with sand.' },
      { from: 7, to: 8, clue: 'A sand castle is built from sand.' },
      { from: 0, to: 3, clue: 'A swing and a slide are playground equipment.' },
      { from: 3, to: 6, clue: 'A slide and a sandbox are common playground features.' },
      { from: 1, to: 4, clue: 'A chain ladder is a ladder made from chain links.' },
      { from: 4, to: 7, clue: 'A ladder can stand on sand at a playground work area.' },
      { from: 2, to: 5, clue: 'A chain link and a ladder rung are both single parts of larger structures.' },
      { from: 5, to: 8, clue: 'A castle ladder has rungs for climbing the wall.' },
    ],
  },
  {
    solution: [
      { word: 'Moon', emoji: '🌙' },
      { word: 'Sun', emoji: '☀️' },
      { word: 'Star', emoji: '⭐' },
      { word: 'Earth', emoji: '🌍' },
      { word: 'Planet', emoji: '🪐' },
      { word: 'Orbit', emoji: '⭕' },
      { word: 'Tide', emoji: '🌊' },
      { word: 'Gravity', emoji: '🧲' },
      { word: 'Pull', emoji: '🪝' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Moon and sun are the familiar pair in the sky.' },
      { from: 1, to: 2, clue: 'The sun is a star.' },
      { from: 3, to: 4, clue: 'Earth is a planet.' },
      { from: 4, to: 5, clue: 'A planet travels in an orbit.' },
      { from: 6, to: 7, clue: 'Gravity helps cause ocean tides.' },
      { from: 7, to: 8, clue: 'Gravity is a pulling force.' },
      { from: 0, to: 3, clue: 'The moon orbits Earth.' },
      { from: 3, to: 6, clue: 'Earth has tides in its oceans.' },
      { from: 1, to: 4, clue: 'Planets orbit stars like the sun.' },
      { from: 4, to: 7, clue: 'A planet has gravity.' },
      { from: 2, to: 5, clue: 'A planet can orbit a star.' },
      { from: 5, to: 8, clue: 'Gravity pull keeps an orbit curved.' },
    ],
  },
].map(withCurrentGeneration);
