import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G8: PuzzleDraft[] = [
  {
    title: 'Wool Workbench',
    solution: [
      { word: 'Sheep', emoji: '🐑' },
      { word: 'Wool', emoji: '🧶' },
      { word: 'Sweater', emoji: '🧥' },
      { word: 'Farm', emoji: '🚜' },
      { word: 'Shears', emoji: '✂️' },
      { word: 'Scissors', emoji: '✂️' },
      { word: 'Fence', emoji: '🚧' },
      { word: 'Wire', emoji: '🧵' },
      { word: 'Cutter', emoji: '🛠️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Sheep grow wool.' },
      { from: 1, to: 2, clue: 'A sweater can be made from wool.' },
      { from: 3, to: 4, clue: 'Farm workers use shears on sheep.' },
      { from: 4, to: 5, clue: 'Shears are heavy-duty scissors.' },
      { from: 6, to: 7, clue: 'A fence can be made from wire.' },
      { from: 7, to: 8, clue: 'A wire cutter cuts wire.' },
      { from: 0, to: 3, clue: 'Sheep live on a farm.' },
      { from: 3, to: 6, clue: 'A farm fence keeps animals in place.' },
      { from: 1, to: 4, clue: 'Shears cut wool from sheep.' },
      { from: 4, to: 7, clue: 'Wire shears cut wire.' },
      { from: 2, to: 5, clue: 'Scissors can cut a sweater.' },
      { from: 5, to: 8, clue: 'Scissors are one kind of cutter.' },
    ],
  },
  {
    title: 'Pond Patrol',
    solution: [
      { word: 'Frog', emoji: '🐸' },
      { word: 'Tadpole', emoji: '🫧' },
      { word: 'Pond', emoji: '🏞️' },
      { word: 'Lily', emoji: '🪷' },
      { word: 'Water', emoji: '💧' },
      { word: 'Reed', emoji: '🌾' },
      { word: 'Pad', emoji: '🟩' },
      { word: 'Marsh', emoji: '🌿' },
      { word: 'Heron', emoji: '🪶' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A tadpole grows into a frog.' },
      { from: 1, to: 2, clue: 'A tadpole lives in a pond.' },
      { from: 3, to: 4, clue: 'A water lily grows in water.' },
      { from: 4, to: 5, clue: 'Reeds grow in water.' },
      { from: 6, to: 7, clue: 'Floating pads can cover a marsh surface.' },
      { from: 7, to: 8, clue: 'A heron hunts in a marsh.' },
      { from: 0, to: 3, clue: 'A frog can rest on a lily.' },
      { from: 3, to: 6, clue: 'A lily pad is the leaf of a lily.' },
      { from: 1, to: 4, clue: 'Tadpoles swim through water.' },
      { from: 4, to: 7, clue: 'Marsh water covers wet ground.' },
      { from: 2, to: 5, clue: 'Pond reeds grow along pond edges.' },
      { from: 5, to: 8, clue: 'Herons stand among reeds while hunting.' },
    ],
  },
  {
    title: 'Seating Plan',
    solution: [
      { word: 'Teacher', emoji: '🧑‍🏫' },
      { word: 'Student', emoji: '🧑‍🎓' },
      { word: 'Desk', emoji: '🪑' },
      { word: 'Lesson', emoji: '📘' },
      { word: 'Class', emoji: '🏫' },
      { word: 'Room', emoji: '🚪' },
      { word: 'Plan', emoji: '📝' },
      { word: 'Seating', emoji: '🪑' },
      { word: 'Chart', emoji: '📊' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A teacher teaches a student.' },
      { from: 1, to: 2, clue: 'A student works at a desk.' },
      { from: 3, to: 4, clue: 'A lesson is taught to a class.' },
      { from: 4, to: 5, clue: 'A classroom is a room for a class.' },
      { from: 6, to: 7, clue: 'A seating plan maps who sits where.' },
      { from: 7, to: 8, clue: 'A seating chart shows where people sit.' },
      { from: 0, to: 3, clue: 'A teacher prepares a lesson.' },
      { from: 3, to: 6, clue: 'A lesson plan outlines a lesson.' },
      { from: 1, to: 4, clue: 'A student belongs to a class.' },
      { from: 4, to: 7, clue: 'Class seating describes where students sit for class.' },
      { from: 2, to: 5, clue: 'A desk belongs in a classroom.' },
      { from: 5, to: 8, clue: 'A chart can hang in a classroom.' },
    ],
  },
  {
    title: 'Lab Notes',
    solution: [
      { word: 'Test', emoji: '🧪' },
      { word: 'Tube', emoji: '🧪' },
      { word: 'Rack', emoji: '🧫' },
      { word: 'Sample', emoji: '🔬' },
      { word: 'Lab', emoji: '🔬' },
      { word: 'Coat', emoji: '🥼' },
      { word: 'Slide', emoji: '🔬' },
      { word: 'Lens', emoji: '🔍' },
      { word: 'Pocket', emoji: '👝' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A test tube holds a test sample.' },
      { from: 1, to: 2, clue: 'A tube rack holds tubes upright.' },
      { from: 3, to: 4, clue: 'A lab sample is studied in a lab.' },
      { from: 4, to: 5, clue: 'A lab coat is worn in a lab.' },
      { from: 6, to: 7, clue: 'A lens focuses on a slide.' },
      { from: 7, to: 8, clue: 'A pocket lens is a small magnifier.' },
      { from: 0, to: 3, clue: 'A test uses a sample.' },
      { from: 3, to: 6, clue: 'A sample can be placed on a slide.' },
      { from: 1, to: 4, clue: 'A tube is common lab equipment.' },
      { from: 4, to: 7, clue: 'A lab lens helps inspect tiny details.' },
      { from: 2, to: 5, clue: 'A coat rack holds a coat.' },
      { from: 5, to: 8, clue: 'A coat can have a pocket.' },
    ],
  },
  {
    title: 'Studio Stitch',
    solution: [
      { word: 'Needle', emoji: '🪡' },
      { word: 'Thread', emoji: '🧵' },
      { word: 'Seam', emoji: '🧵' },
      { word: 'Fabric', emoji: '🧶' },
      { word: 'Stitch', emoji: '🪡' },
      { word: 'Patch', emoji: '🧩' },
      { word: 'Scissors', emoji: '✂️' },
      { word: 'Button', emoji: '🔘' },
      { word: 'Hole', emoji: '🕳️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A needle carries thread.' },
      { from: 1, to: 2, clue: 'Thread can close a seam.' },
      { from: 3, to: 4, clue: 'A stitch joins pieces of fabric.' },
      { from: 4, to: 5, clue: 'A stitch can hold a patch.' },
      { from: 6, to: 7, clue: 'Scissors can cut off a button.' },
      { from: 7, to: 8, clue: 'A buttonhole is a hole for a button.' },
      { from: 0, to: 3, clue: 'A needle passes through fabric.' },
      { from: 3, to: 6, clue: 'Scissors cut fabric.' },
      { from: 1, to: 4, clue: 'Thread forms a stitch.' },
      { from: 4, to: 7, clue: 'A stitch can attach a button.' },
      { from: 2, to: 5, clue: 'A patch can cover a torn seam.' },
      { from: 5, to: 8, clue: 'A patch covers a hole.' },
    ],
  },
  {
    title: 'Paint Hang',
    solution: [
      { word: 'Paint', emoji: '🎨' },
      { word: 'Brush', emoji: '🖌️' },
      { word: 'Wire', emoji: '🧵' },
      { word: 'Canvas', emoji: '🖼️' },
      { word: 'Frame', emoji: '🖼️' },
      { word: 'Hook', emoji: '🪝' },
      { word: 'Gallery', emoji: '🏛️' },
      { word: 'Wall', emoji: '🧱' },
      { word: 'Nail', emoji: '🔩' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A paint brush carries paint.' },
      { from: 1, to: 2, clue: 'A wire brush uses stiff wire for scrubbing.' },
      { from: 3, to: 4, clue: 'A canvas can sit inside a frame.' },
      { from: 4, to: 5, clue: 'A frame can hang from a hook.' },
      { from: 6, to: 7, clue: 'A gallery wall displays art.' },
      { from: 7, to: 8, clue: 'A nail can be driven into a wall.' },
      { from: 0, to: 3, clue: 'Paint goes on a canvas.' },
      { from: 3, to: 6, clue: 'A gallery displays painted canvas works.' },
      { from: 1, to: 4, clue: 'A brush can paint a frame.' },
      { from: 4, to: 7, clue: 'A frame hangs on a wall.' },
      { from: 2, to: 5, clue: 'A hook can be bent from wire.' },
      { from: 5, to: 8, clue: 'A hook can hang from a nail.' },
    ],
  },
  {
    title: 'Postage Loop',
    solution: [
      { word: 'Stamp', emoji: '🏷️' },
      { word: 'Postmark', emoji: '📮' },
      { word: 'City', emoji: '🏙️' },
      { word: 'Letter', emoji: '💌' },
      { word: 'Envelope', emoji: '✉️' },
      { word: 'Address', emoji: '🏠' },
      { word: 'Mail', emoji: '📬' },
      { word: 'Carrier', emoji: '📬' },
      { word: 'Route', emoji: '🗺️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A postmark cancels a stamp.' },
      { from: 1, to: 2, clue: 'A postmark often names the city where mail was processed.' },
      { from: 3, to: 4, clue: 'An envelope holds a letter.' },
      { from: 4, to: 5, clue: 'An envelope shows an address.' },
      { from: 6, to: 7, clue: 'A mail carrier delivers mail.' },
      { from: 7, to: 8, clue: 'A carrier follows a route.' },
      { from: 0, to: 3, clue: 'A stamp is placed on a letter.' },
      { from: 3, to: 6, clue: 'A letter is a piece of mail.' },
      { from: 1, to: 4, clue: 'A postmark is printed on an envelope.' },
      { from: 4, to: 7, clue: 'A carrier carries envelopes.' },
      { from: 2, to: 5, clue: 'An address includes a city.' },
      { from: 5, to: 8, clue: 'A route is planned around addresses.' },
    ],
  },
  {
    title: 'Desk Dispatch',
    solution: [
      { word: 'Desk', emoji: '🪑' },
      { word: 'Drawer', emoji: '🗄️' },
      { word: 'Handle', emoji: '🔧' },
      { word: 'Folder', emoji: '📁' },
      { word: 'File', emoji: '📄' },
      { word: 'Label', emoji: '🏷️' },
      { word: 'Paper', emoji: '📄' },
      { word: 'Printer', emoji: '🖨️' },
      { word: 'Tray', emoji: '📥' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A desk drawer slides inside a desk.' },
      { from: 1, to: 2, clue: 'A drawer has a handle.' },
      { from: 3, to: 4, clue: 'A folder holds a file.' },
      { from: 4, to: 5, clue: 'A file label identifies a file.' },
      { from: 6, to: 7, clue: 'A printer prints on paper.' },
      { from: 7, to: 8, clue: 'A printer tray holds paper.' },
      { from: 0, to: 3, clue: 'A folder can sit on a desk.' },
      { from: 3, to: 6, clue: 'A folder can hold paper.' },
      { from: 1, to: 4, clue: 'A file drawer stores files.' },
      { from: 4, to: 7, clue: 'A printer can print a file.' },
      { from: 2, to: 5, clue: "An online handle is a label for a person's account." },
      { from: 5, to: 8, clue: 'A tray label identifies a tray.' },
    ],
  },
  {
    title: 'Dispatch Desk',
    solution: [
      { word: 'Fire', emoji: '🔥' },
      { word: 'Alarm', emoji: '🚨' },
      { word: 'Call', emoji: '📞' },
      { word: 'Station', emoji: '🚉' },
      { word: 'Dispatch', emoji: '📡' },
      { word: 'Operator', emoji: '🎧' },
      { word: 'Police', emoji: '👮' },
      { word: 'Officer', emoji: '👮' },
      { word: 'Desk', emoji: '🪑' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A fire alarm warns of fire.' },
      { from: 1, to: 2, clue: 'An alarm call reports an alarm.' },
      { from: 3, to: 4, clue: 'A dispatch station sends crews to calls.' },
      { from: 4, to: 5, clue: 'A dispatch operator coordinates emergency responses.' },
      { from: 6, to: 7, clue: 'A police officer works for the police.' },
      { from: 7, to: 8, clue: 'A desk officer handles reports from behind a desk.' },
      { from: 0, to: 3, clue: 'A fire station houses firefighters.' },
      { from: 3, to: 6, clue: 'A police station is a base for police.' },
      { from: 1, to: 4, clue: 'An alarm can trigger dispatch.' },
      { from: 4, to: 7, clue: 'Dispatch sends an officer to a call.' },
      { from: 2, to: 5, clue: 'An operator answers a call.' },
      { from: 5, to: 8, clue: 'An operator works at a desk.' },
    ],
  },
  {
    title: 'Route Lights',
    solution: [
      { word: 'Bus', emoji: '🚌' },
      { word: 'Route', emoji: '🗺️' },
      { word: 'Map', emoji: '🗺️' },
      { word: 'Stop', emoji: '🚏' },
      { word: 'Sign', emoji: '🪧' },
      { word: 'Light', emoji: '💡' },
      { word: 'Shelter', emoji: '🏠' },
      { word: 'Street', emoji: '🛣️' },
      { word: 'Lamp', emoji: '💡' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A bus route is followed by a bus.' },
      { from: 1, to: 2, clue: 'A route map shows a route.' },
      { from: 3, to: 4, clue: 'A stop sign marks a required stop.' },
      { from: 4, to: 5, clue: 'A sign light illuminates a sign.' },
      { from: 6, to: 7, clue: 'A street shelter protects people on a street.' },
      { from: 7, to: 8, clue: 'A street lamp lights a street.' },
      { from: 0, to: 3, clue: 'A bus stop is where a bus picks up riders.' },
      { from: 3, to: 6, clue: 'A stop shelter covers a bus stop.' },
      { from: 1, to: 4, clue: 'A route sign names a route.' },
      { from: 4, to: 7, clue: 'A street sign names a street.' },
      { from: 2, to: 5, clue: 'A map light helps someone read a map.' },
      { from: 5, to: 8, clue: 'A lamp gives off light.' },
    ],
  },
].map(withCurrentGeneration);