import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G3: PuzzleDraft[] = [
  {
    solution: [
      { word: 'Horse', emoji: '🐎' },
      { word: 'Shoe', emoji: '👟' },
      { word: 'Loop', emoji: '➰' },
      { word: 'Saddle', emoji: '🏇' },
      { word: 'Strap', emoji: '🎒' },
      { word: 'Belt', emoji: '👖' },
      { word: 'Rider', emoji: '🏇' },
      { word: 'Helmet', emoji: '⛑️' },
      { word: 'Buckle', emoji: '🔗' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A horseshoe protects a horse\'s hoof.' },
      { from: 1, to: 2, clue: 'A shoe loop helps pull a shoe on.' },
      { from: 3, to: 4, clue: 'A saddle strap helps hold a saddle in place.' },
      { from: 4, to: 5, clue: 'A belt is a strap worn around the waist.' },
      { from: 6, to: 7, clue: 'A rider wears a helmet for protection.' },
      { from: 7, to: 8, clue: 'A helmet buckle fastens the helmet strap.' },
      { from: 0, to: 3, clue: 'A saddle is fitted onto a horse for riding.' },
      { from: 3, to: 6, clue: 'A rider sits in a saddle.' },
      { from: 1, to: 4, clue: 'Some shoes fasten with a strap instead of laces.' },
      { from: 4, to: 7, clue: 'A helmet strap keeps a helmet secure.' },
      { from: 2, to: 5, clue: 'A belt loop holds a belt in place.' },
      { from: 5, to: 8, clue: 'A belt buckle fastens a belt.' },
    ],
  },
  {
    solution: [
      { word: 'Sewing', emoji: '🧵' },
      { word: 'Machine', emoji: '🪡' },
      { word: 'Needle', emoji: '🪡' },
      { word: 'Thread', emoji: '🧵' },
      { word: 'Spool', emoji: '🧶' },
      { word: 'Pin', emoji: '📍' },
      { word: 'Yarn', emoji: '🧶' },
      { word: 'Ball', emoji: '⚽' },
      { word: 'Point', emoji: '📍' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A sewing machine stitches fabric quickly.' },
      { from: 1, to: 2, clue: 'A machine needle moves up and down to make stitches.' },
      { from: 3, to: 4, clue: 'Thread is wound around a spool.' },
      { from: 4, to: 5, clue: 'A spool pin holds a spool on a sewing machine.' },
      { from: 6, to: 7, clue: 'Yarn is often sold as a ball.' },
      { from: 7, to: 8, clue: 'A ballpoint pen uses a tiny ball at the point.' },
      { from: 0, to: 3, clue: 'Sewing thread is made for stitching.' },
      { from: 3, to: 6, clue: 'Thread and yarn are both fiber strands.' },
      { from: 1, to: 4, clue: 'A sewing machine uses a spool of thread.' },
      { from: 4, to: 7, clue: 'Spools and balls are both rounded holders for wound material.' },
      { from: 2, to: 5, clue: 'Needles and pins are both sharp sewing tools.' },
      { from: 5, to: 8, clue: 'A pin point is the sharp end of a pin.' },
    ],
  },
  {
    solution: [
      { word: 'Mixing', emoji: '🥣' },
      { word: 'Bowl', emoji: '🥣' },
      { word: 'Game', emoji: '🎮' },
      { word: 'Salad', emoji: '🥗' },
      { word: 'Dressing', emoji: '🧴' },
      { word: 'Room', emoji: '🚪' },
      { word: 'Bar', emoji: '🍸' },
      { word: 'Mirror', emoji: '🪞' },
      { word: 'Door', emoji: '🚪' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A mixing bowl is used for stirring ingredients together.' },
      { from: 1, to: 2, clue: 'A bowl game is a major college football game.' },
      { from: 3, to: 4, clue: 'Salad dressing is poured onto salad.' },
      { from: 4, to: 5, clue: 'A dressing room is where people change clothes.' },
      { from: 6, to: 7, clue: 'A bar mirror often hangs behind a bar.' },
      { from: 7, to: 8, clue: 'A mirrored door has a mirror on the door panel.' },
      { from: 0, to: 3, clue: 'Mixing a salad tosses its ingredients together.' },
      { from: 3, to: 6, clue: 'A salad bar lets people build their own salads.' },
      { from: 1, to: 4, clue: 'A bowl can hold dressing before it is served.' },
      { from: 4, to: 7, clue: 'A dressing mirror is used while getting dressed.' },
      { from: 2, to: 5, clue: 'A game room is set aside for play.' },
      { from: 5, to: 8, clue: 'A room door opens into a room.' },
    ],
  },
  {
    solution: [
      { word: 'Space', emoji: '🚀' },
      { word: 'Ship', emoji: '🚢' },
      { word: 'Wheel', emoji: '⚙️' },
      { word: 'Rocket', emoji: '🚀' },
      { word: 'Fuel', emoji: '⛽' },
      { word: 'Tank', emoji: '🛢️' },
      { word: 'Fire', emoji: '🔥' },
      { word: 'Engine', emoji: '🚒' },
      { word: 'Room', emoji: '🚪' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A spaceship travels through space.' },
      { from: 1, to: 2, clue: 'A ship wheel steers a ship.' },
      { from: 3, to: 4, clue: 'Rocket fuel powers a rocket.' },
      { from: 4, to: 5, clue: 'A fuel tank stores fuel.' },
      { from: 6, to: 7, clue: 'A fire engine responds to fires.' },
      { from: 7, to: 8, clue: 'An engine room houses engines.' },
      { from: 0, to: 3, clue: 'A space rocket is built to leave Earth.' },
      { from: 3, to: 6, clue: 'A rocket produces fire from burning fuel.' },
      { from: 1, to: 4, clue: 'A ship burns fuel to move.' },
      { from: 4, to: 7, clue: 'An engine burns fuel for power.' },
      { from: 2, to: 5, clue: 'A tank uses wheels inside its track system.' },
      { from: 5, to: 8, clue: 'A tank room houses storage tanks.' },
    ],
  },
  {
    solution: [
      { word: 'Flower', emoji: '🌸' },
      { word: 'Pot', emoji: '🪴' },
      { word: 'Holder', emoji: '🧺' },
      { word: 'Soil', emoji: '🌱' },
      { word: 'Plant', emoji: '🪴' },
      { word: 'Stand', emoji: '🧍' },
      { word: 'Water', emoji: '💧' },
      { word: 'Can', emoji: '🥫' },
      { word: 'Base', emoji: '⬛' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A flower pot gives a flower room for roots.' },
      { from: 1, to: 2, clue: 'A pot holder protects hands from a hot pot.' },
      { from: 3, to: 4, clue: 'A plant grows in soil.' },
      { from: 4, to: 5, clue: 'A plant stand raises a plant off the floor.' },
      { from: 6, to: 7, clue: 'A can can hold water for watering plants.' },
      { from: 7, to: 8, clue: 'The base is the bottom part of a can.' },
      { from: 0, to: 3, clue: 'A flower grows from soil.' },
      { from: 3, to: 6, clue: 'Soil holds water for plant roots.' },
      { from: 1, to: 4, clue: 'A potted plant grows in a pot.' },
      { from: 4, to: 7, clue: 'A watering can is used on a plant.' },
      { from: 2, to: 5, clue: 'A holder and a stand both support an object.' },
      { from: 5, to: 8, clue: 'The base supports a stand.' },
    ],
  },
  {
    solution: [
      { word: 'Pasta', emoji: '🍝' },
      { word: 'Sauce', emoji: '🥫' },
      { word: 'Pan', emoji: '🍳' },
      { word: 'Tomato', emoji: '🍅' },
      { word: 'Soup', emoji: '🍲' },
      { word: 'Bowl', emoji: '🥣' },
      { word: 'Chicken', emoji: '🍗' },
      { word: 'Stock', emoji: '🧾' },
      { word: 'Pot', emoji: '🍲' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Pasta sauce is served over pasta.' },
      { from: 1, to: 2, clue: 'A saucepan is a pan for heating sauce or liquids.' },
      { from: 3, to: 4, clue: 'Tomato soup is soup made from tomatoes.' },
      { from: 4, to: 5, clue: 'A soup bowl is made for serving soup.' },
      { from: 6, to: 7, clue: 'Chicken stock is stock made from chicken.' },
      { from: 7, to: 8, clue: 'A stockpot is a large pot for making stock.' },
      { from: 0, to: 3, clue: 'Tomato is a common pasta topping.' },
      { from: 3, to: 6, clue: 'Tomato chicken is a common saucy dish.' },
      { from: 1, to: 4, clue: 'Soup and sauce are both cooked liquids.' },
      { from: 4, to: 7, clue: 'Stock is the base for many soups.' },
      { from: 2, to: 5, clue: 'Pans and bowls are both kitchen vessels.' },
      { from: 5, to: 8, clue: 'Bowls and pots both hold food.' },
    ],
  },
  {
    solution: [
      { word: 'Door', emoji: '🚪' },
      { word: 'Bell', emoji: '🔔' },
      { word: 'Tower', emoji: '🗼' },
      { word: 'Fire', emoji: '🔥' },
      { word: 'Alarm', emoji: '🚨' },
      { word: 'Light', emoji: '💡' },
      { word: 'Station', emoji: '🚉' },
      { word: 'Radio', emoji: '📻' },
      { word: 'Show', emoji: '🎭' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A doorbell rings at the door.' },
      { from: 1, to: 2, clue: 'A bell tower holds bells high above the ground.' },
      { from: 3, to: 4, clue: 'A fire alarm warns people about fire.' },
      { from: 4, to: 5, clue: 'An alarm light flashes when an alarm is triggered.' },
      { from: 6, to: 7, clue: 'A radio station broadcasts radio programs.' },
      { from: 7, to: 8, clue: 'A radio show is a show broadcast on radio.' },
      { from: 0, to: 3, clue: 'A fire door slows the spread of fire.' },
      { from: 3, to: 6, clue: 'A fire station houses firefighters and engines.' },
      { from: 1, to: 4, clue: 'An alarm bell rings to warn people.' },
      { from: 4, to: 7, clue: 'A radio alarm can wake someone with a radio.' },
      { from: 2, to: 5, clue: 'A tower light warns aircraft about a tower.' },
      { from: 5, to: 8, clue: 'A light show uses lights as the main display.' },
    ],
  },
  {
    solution: [
      { word: 'Book', emoji: '📖' },
      { word: 'Club', emoji: '♣️' },
      { word: 'House', emoji: '🏠' },
      { word: 'Board', emoji: '🧩' },
      { word: 'Room', emoji: '🚪' },
      { word: 'Service', emoji: '🛎️' },
      { word: 'Game', emoji: '🎮' },
      { word: 'Escape', emoji: '🏃' },
      { word: 'Route', emoji: '🗺️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A book club meets to discuss books.' },
      { from: 1, to: 2, clue: 'A clubhouse is a house or building used by a club.' },
      { from: 3, to: 4, clue: 'A boardroom is a room for meetings.' },
      { from: 4, to: 5, clue: 'Room service brings food or supplies to a room.' },
      { from: 6, to: 7, clue: 'An escape game is a game built around escaping.' },
      { from: 7, to: 8, clue: 'An escape route is a route used to escape.' },
      { from: 0, to: 3, clue: 'A board book is a sturdy book for young children.' },
      { from: 3, to: 6, clue: 'A board game is played on a board.' },
      { from: 1, to: 4, clue: 'A club room is a room used by a club.' },
      { from: 4, to: 7, clue: 'An escape room is a room full of escape puzzles.' },
      { from: 2, to: 5, clue: 'House service covers cleaning, repairs, or hospitality.' },
      { from: 5, to: 8, clue: 'A service route is the route a worker repeats.' },
    ],
  },
  {
    solution: [
      { word: 'Door', emoji: '🚪' },
      { word: 'Lock', emoji: '🔒' },
      { word: 'Bike', emoji: '🚲' },
      { word: 'Bell', emoji: '🔔' },
      { word: 'Chain', emoji: '⛓️' },
      { word: 'Ring', emoji: '💍' },
      { word: 'Tower', emoji: '🗼' },
      { word: 'Guard', emoji: '💂' },
      { word: 'Tone', emoji: '🎵' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A door lock secures a door.' },
      { from: 1, to: 2, clue: 'A bike lock helps keep a bike from being stolen.' },
      { from: 3, to: 4, clue: 'A bell chain is pulled to ring a bell.' },
      { from: 4, to: 5, clue: 'A chain ring is part of a bicycle drivetrain.' },
      { from: 6, to: 7, clue: 'A tower guard watches from a tower.' },
      { from: 7, to: 8, clue: 'A guard\'s tone can warn someone to stop.' },
      { from: 0, to: 3, clue: 'A doorbell rings at the door.' },
      { from: 3, to: 6, clue: 'A bell tower holds bells high above the ground.' },
      { from: 1, to: 4, clue: 'A lock chain can secure a gate or bike.' },
      { from: 4, to: 7, clue: 'A chain guard covers a moving chain.' },
      { from: 2, to: 5, clue: 'A bike bell makes a ring on the handlebars.' },
      { from: 5, to: 8, clue: 'A ringtone is the tone a phone plays when it rings.' },
    ],
  },
  {
    solution: [
      { word: 'Paper', emoji: '📄' },
      { word: 'Chain', emoji: '⛓️' },
      { word: 'Dog', emoji: '🐕' },
      { word: 'Clip', emoji: '📎' },
      { word: 'Mail', emoji: '✉️' },
      { word: 'Tag', emoji: '🏷️' },
      { word: 'Board', emoji: '🧩' },
      { word: 'Room', emoji: '🚪' },
      { word: 'Service', emoji: '🛎️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A paper chain is made from linked paper strips.' },
      { from: 1, to: 2, clue: 'A dog chain keeps a dog from wandering.' },
      { from: 3, to: 4, clue: 'A clip can hold mail together.' },
      { from: 4, to: 5, clue: 'A mailing tag travels with mail or a parcel.' },
      { from: 6, to: 7, clue: 'A boardroom is a room for meetings.' },
      { from: 7, to: 8, clue: 'Room service brings food or supplies to a room.' },
      { from: 0, to: 3, clue: 'A paper clip holds paper together.' },
      { from: 3, to: 6, clue: 'A clipboard gives paper a stiff board backing.' },
      { from: 1, to: 4, clue: 'Chain mail is armor made from linked metal rings.' },
      { from: 4, to: 7, clue: 'A mail room sorts incoming mail.' },
      { from: 2, to: 5, clue: 'A dog tag hangs from a dog collar.' },
      { from: 5, to: 8, clue: 'A service tag records repair or inspection work.' },
    ],
  },
].map(withCurrentGeneration);
