import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G7: PuzzleDraft[] = [
  {
    title: 'Sound Check',
    solution: [
      { word: 'Voice', emoji: '🎙️' },
      { word: 'Microphone', emoji: '🎤' },
      { word: 'Cable', emoji: '🔌' },
      { word: 'Singer', emoji: '🎤' },
      { word: 'Stage', emoji: '🎭' },
      { word: 'Light', emoji: '💡' },
      { word: 'Guitar', emoji: '🎸' },
      { word: 'Amp', emoji: '🔊' },
      { word: 'Speaker', emoji: '🔈' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A microphone captures a voice.' },
      { from: 1, to: 2, clue: 'A microphone cable carries the signal.' },
      { from: 3, to: 4, clue: 'A singer performs on a stage.' },
      { from: 4, to: 5, clue: 'A stage light shines on performers.' },
      { from: 6, to: 7, clue: 'A guitar amp makes the guitar louder.' },
      { from: 7, to: 8, clue: 'An amp drives sound through a speaker.' },
      { from: 0, to: 3, clue: 'A singer uses a voice to perform.' },
      { from: 3, to: 6, clue: 'A singer may play a guitar onstage.' },
      { from: 1, to: 4, clue: 'A stage microphone is used in live shows.' },
      { from: 4, to: 7, clue: 'A stage amp sits near the performer.' },
      { from: 2, to: 5, clue: 'A lighting cable powers a stage light.' },
      { from: 5, to: 8, clue: 'Lights and speakers are both stage equipment.' },
    ],
  },
  {
    title: 'Game Day Calls',
    solution: [
      { word: 'Player', emoji: '🏃' },
      { word: 'Coach', emoji: '🧢' },
      { word: 'Goal', emoji: '🥅' },
      { word: 'Jersey', emoji: '👕' },
      { word: 'Number', emoji: '🔢' },
      { word: 'Score', emoji: '🏆' },
      { word: 'Whistle', emoji: '📣' },
      { word: 'Call', emoji: '📞' },
      { word: 'Judge', emoji: '⚖️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A coach trains a player.' },
      { from: 1, to: 2, clue: 'A coach sets a goal for the team.' },
      { from: 3, to: 4, clue: 'A jersey number identifies a player.' },
      { from: 4, to: 5, clue: 'A score is recorded as a number.' },
      { from: 6, to: 7, clue: 'A whistle call stops play.' },
      { from: 7, to: 8, clue: 'A judge makes a call.' },
      { from: 0, to: 3, clue: 'A player wears a jersey.' },
      { from: 3, to: 6, clue: 'Jerseys and whistles are both sports gear.' },
      { from: 1, to: 4, clue: 'A coach number identifies a rail coach in a train.' },
      { from: 4, to: 7, clue: 'A call number identifies an item in a library catalog.' },
      { from: 2, to: 5, clue: 'A player scores a goal.' },
      { from: 5, to: 8, clue: 'A judge gives a score.' },
    ],
  },
  {
    title: 'Forecast Shore',
    solution: [
      { word: 'Beach', emoji: '🏖️' },
      { word: 'Umbrella', emoji: '☂️' },
      { word: 'Canopy', emoji: '🎪' },
      { word: 'Sun', emoji: '☀️' },
      { word: 'Screen', emoji: '🧴' },
      { word: 'Shade', emoji: '🌳' },
      { word: 'Rain', emoji: '🌧️' },
      { word: 'Cloud', emoji: '☁️' },
      { word: 'Cover', emoji: '🧢' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A beach umbrella gives shade on the sand.' },
      { from: 1, to: 2, clue: 'An umbrella canopy is the fabric overhead.' },
      { from: 3, to: 4, clue: 'Sunscreen protects skin from the sun.' },
      { from: 4, to: 5, clue: 'A shade screen blocks bright sun.' },
      { from: 6, to: 7, clue: 'Rain clouds bring wet weather.' },
      { from: 7, to: 8, clue: 'Cloud cover hides the sun.' },
      { from: 0, to: 3, clue: 'A sunny beach draws people outside.' },
      { from: 3, to: 6, clue: 'Sun and rain are opposite weather conditions.' },
      { from: 1, to: 4, clue: 'An umbrella screens people from sun or rain.' },
      { from: 4, to: 7, clue: 'Clouds screen the sun from view.' },
      { from: 2, to: 5, clue: 'A canopy creates shade.' },
      { from: 5, to: 8, clue: 'Shade is a kind of cover from sunlight.' },
    ],
  },
  {
    title: 'Campfire Kit',
    solution: [
      { word: 'Tent', emoji: '⛺' },
      { word: 'Pole', emoji: '🪵' },
      { word: 'Stick', emoji: '🦯' },
      { word: 'Lantern', emoji: '🏮' },
      { word: 'Light', emoji: '💡' },
      { word: 'Fire', emoji: '🔥' },
      { word: 'Rope', emoji: '🪢' },
      { word: 'Knot', emoji: '🪢' },
      { word: 'Log', emoji: '🪵' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A tent pole holds a tent upright.' },
      { from: 1, to: 2, clue: 'A pole is a long stick.' },
      { from: 3, to: 4, clue: 'A lantern gives light at camp.' },
      { from: 4, to: 5, clue: 'Firelight is light from a fire.' },
      { from: 6, to: 7, clue: 'A rope is tied with a knot.' },
      { from: 7, to: 8, clue: 'A log can have a knot in its wood.' },
      { from: 0, to: 3, clue: 'A lantern is useful inside a tent.' },
      { from: 3, to: 6, clue: 'A lantern can hang from a rope.' },
      { from: 1, to: 4, clue: 'A light pole holds a lamp above the ground.' },
      { from: 4, to: 7, clue: 'A knot can hold a light in place.' },
      { from: 2, to: 5, clue: 'A fire stick helps start a fire.' },
      { from: 5, to: 8, clue: 'A fire burns logs.' },
    ],
  },
  {
    title: 'Bathroom Loop',
    solution: [
      { word: 'Tooth', emoji: '🦷' },
      { word: 'Brush', emoji: '🪥' },
      { word: 'Holder', emoji: '🧺' },
      { word: 'Soap', emoji: '🧼' },
      { word: 'Dish', emoji: '🍽️' },
      { word: 'Towel', emoji: '🧻' },
      { word: 'Shower', emoji: '🚿' },
      { word: 'Rack', emoji: '🧺' },
      { word: 'Bar', emoji: '➖' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A toothbrush cleans a tooth.' },
      { from: 1, to: 2, clue: 'A brush holder stores the brush upright.' },
      { from: 3, to: 4, clue: 'A soap dish holds a bar of soap.' },
      { from: 4, to: 5, clue: 'A dish towel dries dishes.' },
      { from: 6, to: 7, clue: 'A shower rack holds bath supplies in a shower.' },
      { from: 7, to: 8, clue: 'A rack is built from bars.' },
      { from: 0, to: 3, clue: 'Tooth care and soap are both bathroom basics.' },
      { from: 3, to: 6, clue: 'Shower soap is used while washing.' },
      { from: 1, to: 4, clue: 'A dish brush scrubs dishes.' },
      { from: 4, to: 7, clue: 'A dish rack holds clean dishes as they dry.' },
      { from: 2, to: 5, clue: 'A towel holder keeps a towel within reach.' },
      { from: 5, to: 8, clue: 'A towel bar holds a hand towel.' },
    ],
  },
  {
    title: 'Practice Field',
    solution: [
      { word: 'Bat', emoji: '🏏' },
      { word: 'Handle', emoji: '🔧' },
      { word: 'Grip', emoji: '✊' },
      { word: 'Ball', emoji: '⚾' },
      { word: 'Glove', emoji: '🧤' },
      { word: 'Leather', emoji: '🟫' },
      { word: 'Cap', emoji: '🧢' },
      { word: 'Brim', emoji: '🧢' },
      { word: 'Stitch', emoji: '🧵' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A bat handle is the part a batter holds.' },
      { from: 1, to: 2, clue: 'A handle grip helps the hand hold firmly.' },
      { from: 3, to: 4, clue: 'A ball glove is used to catch the ball.' },
      { from: 4, to: 5, clue: 'A glove can be made of leather.' },
      { from: 6, to: 7, clue: 'A cap brim shades the eyes.' },
      { from: 7, to: 8, clue: 'A stitch can run along the brim of a cap.' },
      { from: 0, to: 3, clue: 'A bat hits a ball.' },
      { from: 3, to: 6, clue: 'A ball cap is worn at the game.' },
      { from: 1, to: 4, clue: 'A glove has openings where the hand grips inside.' },
      { from: 4, to: 7, clue: 'A glove and a brim are both worn gear.' },
      { from: 2, to: 5, clue: 'A leather grip wraps a handle.' },
      { from: 5, to: 8, clue: 'Leather is held together by stitches.' },
    ],
  },
  {
    title: 'Porch Weather',
    solution: [
      { word: 'Storm', emoji: '⛈️' },
      { word: 'Window', emoji: '🪟' },
      { word: 'Pane', emoji: '🪟' },
      { word: 'Rain', emoji: '🌧️' },
      { word: 'Gutter', emoji: '🏠' },
      { word: 'Downspout', emoji: '🛢️' },
      { word: 'Wind', emoji: '💨' },
      { word: 'Chime', emoji: '🎐' },
      { word: 'Porch', emoji: '🏡' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A storm window adds protection against bad weather.' },
      { from: 1, to: 2, clue: 'A window pane is a sheet of glass.' },
      { from: 3, to: 4, clue: 'A rain gutter catches water from the roof.' },
      { from: 4, to: 5, clue: 'A gutter drains into a downspout.' },
      { from: 6, to: 7, clue: 'A wind chime rings in the breeze.' },
      { from: 7, to: 8, clue: 'A porch chime hangs beside a front door.' },
      { from: 0, to: 3, clue: 'A storm can bring rain.' },
      { from: 3, to: 6, clue: 'Wind can drive rain sideways during a storm.' },
      { from: 1, to: 4, clue: 'A gutter above a window carries runoff away from the glass.' },
      { from: 4, to: 7, clue: 'A gutter and a wind chime can both hang from the eaves.' },
      { from: 2, to: 5, clue: 'A downspout carries roof water past window panes.' },
      { from: 5, to: 8, clue: 'A downspout can drain beside a porch.' },
    ],
  },
  {
    title: 'Living Room Set',
    solution: [
      { word: 'Sofa', emoji: '🛋️' },
      { word: 'Cushion', emoji: '🛋️' },
      { word: 'Cover', emoji: '🧺' },
      { word: 'Floor', emoji: '🟫' },
      { word: 'Rug', emoji: '🧶' },
      { word: 'Throw', emoji: '🧣' },
      { word: 'Table', emoji: '🪑' },
      { word: 'Lamp', emoji: '💡' },
      { word: 'Shade', emoji: '🌗' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A sofa cushion makes the sofa comfortable.' },
      { from: 1, to: 2, clue: 'A cushion cover protects a cushion.' },
      { from: 3, to: 4, clue: 'A floor rug covers part of the floor.' },
      { from: 4, to: 5, clue: 'A throw rug is a small rug.' },
      { from: 6, to: 7, clue: 'A table lamp sits on a table.' },
      { from: 7, to: 8, clue: 'A lamp shade softens the lamp light.' },
      { from: 0, to: 3, clue: 'A sofa stands on the floor.' },
      { from: 3, to: 6, clue: 'A table stands on the floor.' },
      { from: 1, to: 4, clue: 'A cushion and rug both add softness to a room.' },
      { from: 4, to: 7, clue: 'A rug and lamp are both living room furnishings.' },
      { from: 2, to: 5, clue: 'A throw can serve as a decorative cover.' },
      { from: 5, to: 8, clue: 'To throw shade is to insult someone.' },
    ],
  },
  {
    title: 'Trail Breakfast',
    solution: [
      { word: 'Camp', emoji: '🏕️' },
      { word: 'Stove', emoji: '🔥' },
      { word: 'Fuel', emoji: '⛽' },
      { word: 'Coffee', emoji: '☕' },
      { word: 'Pot', emoji: '🍲' },
      { word: 'Lid', emoji: '🥘' },
      { word: 'Trail', emoji: '🥾' },
      { word: 'Mix', emoji: '🥣' },
      { word: 'Jar', emoji: '🫙' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A camp stove cooks food outdoors.' },
      { from: 1, to: 2, clue: 'Stove fuel powers a camp stove.' },
      { from: 3, to: 4, clue: 'A coffee pot brews coffee.' },
      { from: 4, to: 5, clue: 'A pot lid covers a pot.' },
      { from: 6, to: 7, clue: 'Trail mix is a snack for hiking.' },
      { from: 7, to: 8, clue: 'A jar can hold a dry snack mix.' },
      { from: 0, to: 3, clue: 'Camp coffee is brewed outdoors.' },
      { from: 3, to: 6, clue: 'Coffee can be packed for a trail.' },
      { from: 1, to: 4, clue: 'A stove heats a pot.' },
      { from: 4, to: 7, clue: 'A pot can hold a dry mix before cooking.' },
      { from: 2, to: 5, clue: 'A fuel lid seals a fuel container.' },
      { from: 5, to: 8, clue: 'A jar lid seals a jar.' },
    ],
  },
  {
    title: 'Sandlot Set',
    solution: [
      { word: 'Beach', emoji: '🏖️' },
      { word: 'Ball', emoji: '🏐' },
      { word: 'Pump', emoji: '💨' },
      { word: 'Sand', emoji: '🏝️' },
      { word: 'Castle', emoji: '🏰' },
      { word: 'Bucket', emoji: '🪣' },
      { word: 'Water', emoji: '💧' },
      { word: 'Tower', emoji: '🗼' },
      { word: 'Cap', emoji: '🧢' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A beach ball is played with on the beach.' },
      { from: 1, to: 2, clue: 'A ball pump inflates a ball.' },
      { from: 3, to: 4, clue: 'A sand castle is built from sand.' },
      { from: 4, to: 5, clue: 'A bucket can mold the towers of a sand castle.' },
      { from: 6, to: 7, clue: 'A water tower stores water.' },
      { from: 7, to: 8, clue: 'A cap is the top piece of a tower.' },
      { from: 0, to: 3, clue: 'A beach is covered with sand.' },
      { from: 3, to: 6, clue: 'Sand and water mix for sturdy castles.' },
      { from: 1, to: 4, clue: 'A ball can knock down a sand castle.' },
      { from: 4, to: 7, clue: 'A castle tower rises from a castle.' },
      { from: 2, to: 5, clue: 'A pump can fill a bucket.' },
      { from: 5, to: 8, clue: 'A cap can snap onto a bucket as its lid.' },
    ],
  },
].map(withCurrentGeneration);
