import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G4: PuzzleDraft[] = [
  {
    solution: [
      { word: 'Sun', emoji: '🌞' },
      { word: 'Flower', emoji: '🌼' },
      { word: 'Pot', emoji: '🪴' },
      { word: 'Rain', emoji: '🌧️' },
      { word: 'Garden', emoji: '🌷' },
      { word: 'Soil', emoji: '🟫' },
      { word: 'Seed', emoji: '🌱' },
      { word: 'Plant', emoji: '🌿' },
      { word: 'Root', emoji: '〰️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A sunflower is a flower named for the sun.' },
      { from: 1, to: 2, clue: 'A flowerpot holds a flower.' },
      { from: 3, to: 4, clue: 'A rain garden is planted to soak up rainwater.' },
      { from: 4, to: 5, clue: 'Garden soil is the soil plants grow in.' },
      { from: 6, to: 7, clue: 'A seed grows into a plant.' },
      { from: 7, to: 8, clue: 'A plant uses its root to take in water.' },
      { from: 0, to: 3, clue: 'Sun and rain both help gardens grow.' },
      { from: 3, to: 6, clue: 'Rain helps a seed sprout.' },
      { from: 1, to: 4, clue: 'A flower garden is planted with flowers.' },
      { from: 4, to: 7, clue: 'A garden is a place where plants grow.' },
      { from: 2, to: 5, clue: 'Potting soil fills a flowerpot.' },
      { from: 5, to: 8, clue: 'Roots grow down into soil.' },
    ],
  },
  {
    solution: [
      { word: 'Mail', emoji: '✉️' },
      { word: 'Post', emoji: '📮' },
      { word: 'Office', emoji: '🏢' },
      { word: 'Letter', emoji: '💌' },
      { word: 'Box', emoji: '📦' },
      { word: 'File', emoji: '📁' },
      { word: 'Paper', emoji: '📄' },
      { word: 'Drawer', emoji: '🗄️' },
      { word: 'Cabinet', emoji: '🗃️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'To post mail is to send it.' },
      { from: 1, to: 2, clue: 'A post office handles letters and parcels.' },
      { from: 3, to: 4, clue: 'A letterbox receives letters.' },
      { from: 4, to: 5, clue: 'A file box stores folders and papers.' },
      { from: 6, to: 7, clue: 'A paper drawer stores printer paper.' },
      { from: 7, to: 8, clue: 'A cabinet can have a drawer.' },
      { from: 0, to: 3, clue: 'A letter is one kind of mail.' },
      { from: 3, to: 6, clue: 'A letter is written on paper.' },
      { from: 1, to: 4, clue: 'A postbox is a box for outgoing mail.' },
      { from: 4, to: 7, clue: 'A drawer is a sliding storage box.' },
      { from: 2, to: 5, clue: 'An office file keeps work documents together.' },
      { from: 5, to: 8, clue: 'A file cabinet stores files.' },
    ],
  },
  {
    solution: [
      { word: 'Soup', emoji: '🍲' },
      { word: 'Spoon', emoji: '🥄' },
      { word: 'Ladle', emoji: '🥄' },
      { word: 'Salad', emoji: '🥗' },
      { word: 'Bowl', emoji: '🥣' },
      { word: 'Fork', emoji: '🍴' },
      { word: 'Bread', emoji: '🍞' },
      { word: 'Plate', emoji: '🍽️' },
      { word: 'Knife', emoji: '🔪' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A soup spoon is made for eating soup.' },
      { from: 1, to: 2, clue: 'A spoon and a ladle are both serving utensils.' },
      { from: 3, to: 4, clue: 'A salad bowl holds salad.' },
      { from: 4, to: 5, clue: 'A fork is used to eat food from a bowl.' },
      { from: 6, to: 7, clue: 'A bread plate holds bread at the table.' },
      { from: 7, to: 8, clue: 'A knife belongs beside the plate in a table setting.' },
      { from: 0, to: 3, clue: 'Soup and salad are common first courses.' },
      { from: 3, to: 6, clue: 'Salad and bread are often served together.' },
      { from: 1, to: 4, clue: 'A spoon rests in a bowl.' },
      { from: 4, to: 7, clue: 'A bowl and a plate are both dishes.' },
      { from: 2, to: 5, clue: 'A ladle and a fork are both kitchen utensils.' },
      { from: 5, to: 8, clue: 'A fork and knife are the classic utensil pair.' },
    ],
  },
  {
    solution: [
      { word: 'City', emoji: '🏙️' },
      { word: 'Bus', emoji: '🚌' },
      { word: 'Stop', emoji: '🚏' },
      { word: 'Street', emoji: '🛣️' },
      { word: 'Sign', emoji: '🪧' },
      { word: 'Traffic', emoji: '🚦' },
      { word: 'Bike', emoji: '🚲' },
      { word: 'Lane', emoji: '↔️' },
      { word: 'Driver', emoji: '🧑‍✈️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A city bus carries riders around town.' },
      { from: 1, to: 2, clue: 'A bus stop marks where passengers wait.' },
      { from: 3, to: 4, clue: 'A street sign names the street.' },
      { from: 4, to: 5, clue: 'Traffic signs tell drivers what to do.' },
      { from: 6, to: 7, clue: 'A bike lane gives cyclists their own space.' },
      { from: 7, to: 8, clue: 'A driver is expected to stay in the correct lane.' },
      { from: 0, to: 3, clue: 'A city street is part of the city grid.' },
      { from: 3, to: 6, clue: 'A street bike is built for paved roads.' },
      { from: 1, to: 4, clue: 'A bus sign shows route numbers or arrivals.' },
      { from: 4, to: 7, clue: 'A lane sign tells drivers which lane to use.' },
      { from: 2, to: 5, clue: 'A stop sign forces traffic to pause.' },
      { from: 5, to: 8, clue: 'A driver watches the traffic ahead.' },
    ],
  },
  {
    solution: [
      { word: 'Band', emoji: '🎸' },
      { word: 'Stand', emoji: '🪑' },
      { word: 'Microphone', emoji: '🎤' },
      { word: 'Sheet', emoji: '📄' },
      { word: 'Music', emoji: '🎵' },
      { word: 'Note', emoji: '🎶' },
      { word: 'Guitar', emoji: '🎸' },
      { word: 'String', emoji: '🧵' },
      { word: 'Pick', emoji: '⛏️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A bandstand is a raised place for a band.' },
      { from: 1, to: 2, clue: 'A microphone stand holds a microphone.' },
      { from: 3, to: 4, clue: 'Sheet music is music printed on paper.' },
      { from: 4, to: 5, clue: 'Notes make up music.' },
      { from: 6, to: 7, clue: 'A guitar has strings.' },
      { from: 7, to: 8, clue: 'A pick plucks a guitar string.' },
      { from: 0, to: 3, clue: 'A band reads from sheets or parts.' },
      { from: 3, to: 6, clue: 'Guitar sheet music is written for guitar.' },
      { from: 1, to: 4, clue: 'A music stand holds sheet music upright.' },
      { from: 4, to: 7, clue: 'String music is music written for string instruments.' },
      { from: 2, to: 5, clue: 'A singer sends notes into a microphone.' },
      { from: 5, to: 8, clue: 'A player can pick out a note.' },
    ],
  },
  {
    solution: [
      { word: 'Wood', emoji: '🪵' },
      { word: 'Saw', emoji: '🪚' },
      { word: 'Blade', emoji: '🔪' },
      { word: 'Nail', emoji: '🔩' },
      { word: 'Hammer', emoji: '🔨' },
      { word: 'Handle', emoji: '🕹️' },
      { word: 'Screw', emoji: '🪛' },
      { word: 'Driver', emoji: '🧑‍✈️' },
      { word: 'Bit', emoji: '🔩' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A saw cuts wood.' },
      { from: 1, to: 2, clue: 'A saw has a blade.' },
      { from: 3, to: 4, clue: 'A hammer drives a nail.' },
      { from: 4, to: 5, clue: 'A hammer has a handle.' },
      { from: 6, to: 7, clue: 'A screwdriver turns a screw.' },
      { from: 7, to: 8, clue: 'A driver bit fits into a driver.' },
      { from: 0, to: 3, clue: 'A nail fastens into wood.' },
      { from: 3, to: 6, clue: 'Nails and screws are both fasteners.' },
      { from: 1, to: 4, clue: 'A saw and a hammer are both hand tools.' },
      { from: 4, to: 7, clue: 'A hammer and a driver are both tools.' },
      { from: 2, to: 5, clue: 'A blade is held by a handle.' },
      { from: 5, to: 8, clue: 'A handle holds the tool while the bit turns.' },
    ],
  },
  {
    solution: [
      { word: 'River', emoji: '🏞️' },
      { word: 'Ferry', emoji: '⛴️' },
      { word: 'Boat', emoji: '🚤' },
      { word: 'Harbor', emoji: '⚓' },
      { word: 'Dock', emoji: '🪝' },
      { word: 'Crane', emoji: '🏗️' },
      { word: 'Cargo', emoji: '📦' },
      { word: 'Ship', emoji: '🚢' },
      { word: 'Operator', emoji: '🕹️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A river ferry carries people across a river.' },
      { from: 1, to: 2, clue: 'A ferry is a boat for passengers or cars.' },
      { from: 3, to: 4, clue: 'A harbor dock is where vessels tie up.' },
      { from: 4, to: 5, clue: 'A dock crane lifts cargo at the dock.' },
      { from: 6, to: 7, clue: 'A cargo ship carries goods.' },
      { from: 7, to: 8, clue: 'A ship operator runs a ship.' },
      { from: 0, to: 3, clue: 'A river can lead into a harbor.' },
      { from: 3, to: 6, clue: 'Cargo moves through a harbor.' },
      { from: 1, to: 4, clue: 'A ferry pulls into a dock.' },
      { from: 4, to: 7, clue: 'A ship rests alongside a dock.' },
      { from: 2, to: 5, clue: 'A crane can lift a boat out of the water.' },
      { from: 5, to: 8, clue: 'A crane operator controls a crane.' },
    ],
  },
  {
    solution: [
      { word: 'Market', emoji: '🛒' },
      { word: 'Town', emoji: '🏘️' },
      { word: 'Square', emoji: '◻️' },
      { word: 'Food', emoji: '🍜' },
      { word: 'Hall', emoji: '🏛️' },
      { word: 'Dance', emoji: '💃' },
      { word: 'Street', emoji: '🛣️' },
      { word: 'City', emoji: '🌆' },
      { word: 'Club', emoji: '🎷' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A town market sells goods for the town.' },
      { from: 1, to: 2, clue: 'A town square is the open center of a town.' },
      { from: 3, to: 4, clue: 'A food hall gathers food stalls under one roof.' },
      { from: 4, to: 5, clue: 'A dance hall is built for dancing.' },
      { from: 6, to: 7, clue: 'A city street runs through a city.' },
      { from: 7, to: 8, clue: 'A city club is a club in the city.' },
      { from: 0, to: 3, clue: 'A food market sells food.' },
      { from: 3, to: 6, clue: 'Street food is food sold on the street.' },
      { from: 1, to: 4, clue: 'Town hall is where local government meets.' },
      { from: 4, to: 7, clue: 'City hall houses city offices.' },
      { from: 2, to: 5, clue: 'A square dance is danced in sets.' },
      { from: 5, to: 8, clue: 'A dance club is a club for dancing.' },
    ],
  },
  {
    solution: [
      { word: 'Chef', emoji: '🧑‍🍳' },
      { word: 'Knife', emoji: '🔪' },
      { word: 'Blade', emoji: '🗡️' },
      { word: 'Cook', emoji: '🍳' },
      { word: 'Pan', emoji: '🥘' },
      { word: 'Handle', emoji: '🧰' },
      { word: 'Stove', emoji: '♨️' },
      { word: 'Heat', emoji: '🔥' },
      { word: 'Flame', emoji: '🔥' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A chef uses a knife.' },
      { from: 1, to: 2, clue: 'A blade is the sharp part of a knife.' },
      { from: 3, to: 4, clue: 'A cook uses a pan.' },
      { from: 4, to: 5, clue: 'A pan has a handle.' },
      { from: 6, to: 7, clue: 'A stove produces heat.' },
      { from: 7, to: 8, clue: 'A flame gives off heat.' },
      { from: 0, to: 3, clue: 'A chef is a professional cook.' },
      { from: 3, to: 6, clue: 'A cook works at a stove.' },
      { from: 1, to: 4, clue: 'A knife and a pan are kitchen tools.' },
      { from: 4, to: 7, clue: 'A pan is heated before food cooks.' },
      { from: 2, to: 5, clue: 'A knife blade is joined to a handle.' },
      { from: 5, to: 8, clue: 'A pan handle keeps hands away from the flame.' },
    ],
  },
  {
    solution: [
      { word: 'Horse', emoji: '🐎' },
      { word: 'Shoe', emoji: '👟' },
      { word: 'Loop', emoji: '➰' },
      { word: 'Saddle', emoji: '🏇' },
      { word: 'Strap', emoji: '🎒' },
      { word: 'Belt', emoji: '👖' },
      { word: 'Rider', emoji: '🏇' },
      { word: 'Helmet', emoji: '⛑️' },
      { word: 'Buckle', emoji: '🔗' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A horseshoe protects a horse hoof.' },
      { from: 1, to: 2, clue: 'A shoe loop helps pull a shoe on.' },
      { from: 3, to: 4, clue: 'A saddle strap helps hold a saddle in place.' },
      { from: 4, to: 5, clue: 'A belt is a strap worn around the waist.' },
      { from: 6, to: 7, clue: 'A rider wears a helmet for protection.' },
      { from: 7, to: 8, clue: 'A helmet buckle fastens the helmet strap.' },
      { from: 0, to: 3, clue: 'A saddle is fitted onto a horse for riding.' },
      { from: 3, to: 6, clue: 'A rider sits in a saddle.' },
      { from: 1, to: 4, clue: 'Some shoes fasten with a strap instead of laces.' },
      { from: 4, to: 7, clue: 'A helmet strap keeps a helmet secure.' },
      { from: 2, to: 5, clue: 'A belt loop holds a belt in place.' },
      { from: 5, to: 8, clue: 'A belt buckle fastens a belt.' },
    ],
  },
].map(withCurrentGeneration);