import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G9: PuzzleDraft[] = [
  {
    title: 'Pipe Dream Team',
    solution: [
      { word: 'Pipe', emoji: '🧱' },
      { word: 'Wrench', emoji: '🔧' },
      { word: 'Handle', emoji: '🕹️' },
      { word: 'Leak', emoji: '💦' },
      { word: 'Plumber', emoji: '🧑‍🔧' },
      { word: 'Glove', emoji: '🧤' },
      { word: 'Faucet', emoji: '🚰' },
      { word: 'Washer', emoji: '⭕' },
      { word: 'Rubber', emoji: '🛞' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A pipe wrench grips and turns pipe.' },
      { from: 1, to: 2, clue: 'A wrench has a handle for leverage.' },
      { from: 3, to: 4, clue: 'A plumber repairs a leak.' },
      { from: 4, to: 5, clue: 'A plumber wears gloves while working.' },
      { from: 6, to: 7, clue: 'A faucet washer helps seal a faucet.' },
      { from: 7, to: 8, clue: 'A washer is often made of rubber.' },
      { from: 0, to: 3, clue: 'A pipe can spring a leak.' },
      { from: 3, to: 6, clue: 'A faucet can leak when its seal fails.' },
      { from: 1, to: 4, clue: 'A plumber uses a wrench.' },
      { from: 4, to: 7, clue: 'A plumber replaces a worn washer.' },
      { from: 2, to: 5, clue: 'A glove helps grip a handle.' },
      { from: 5, to: 8, clue: 'A rubber glove keeps hands dry.' },
    ],
  },
  {
    title: 'Patch Work Order',
    solution: [
      { word: 'Hole', emoji: '🕳️' },
      { word: 'Spackle', emoji: '⬜' },
      { word: 'Putty', emoji: '🧴' },
      { word: 'Drywall', emoji: '🧱' },
      { word: 'Compound', emoji: '🥣' },
      { word: 'Paint', emoji: '🎨' },
      { word: 'Sandpaper', emoji: '🧻' },
      { word: 'Primer', emoji: '🪣' },
      { word: 'Roller', emoji: '🖌️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Spackle fills a small hole.' },
      { from: 1, to: 2, clue: 'Spackle is a putty used for wall repairs.' },
      { from: 3, to: 4, clue: 'Drywall compound covers seams and repairs.' },
      { from: 4, to: 5, clue: 'Paint covers dried compound.' },
      { from: 6, to: 7, clue: 'Sandpaper prepares a surface before primer.' },
      { from: 7, to: 8, clue: 'A roller can apply primer.' },
      { from: 0, to: 3, clue: 'A hole can appear in drywall.' },
      { from: 3, to: 6, clue: 'Sandpaper smooths drywall before finishing.' },
      { from: 1, to: 4, clue: 'Spackle and compound are both wall patching materials.' },
      { from: 4, to: 7, clue: 'Primer seals dried compound before paint.' },
      { from: 2, to: 5, clue: 'Paint covers dried putty.' },
      { from: 5, to: 8, clue: 'A paint roller applies paint.' },
    ],
  },
  {
    title: 'Hem And Measure',
    solution: [
      { word: 'Fabric', emoji: '🧵' },
      { word: 'Thread', emoji: '🧵' },
      { word: 'Needle', emoji: '🪡' },
      { word: 'Shirt', emoji: '👕' },
      { word: 'Stitch', emoji: '🪡' },
      { word: 'Hem', emoji: '📏' },
      { word: 'Button', emoji: '🔘' },
      { word: 'Cuff', emoji: '👔' },
      { word: 'Sleeve', emoji: '💪' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Fabric is woven from thread.' },
      { from: 1, to: 2, clue: 'A needle carries thread through cloth.' },
      { from: 3, to: 4, clue: 'A shirt is held together with stitches.' },
      { from: 4, to: 5, clue: 'Stitches hold a hem in place.' },
      { from: 6, to: 7, clue: 'A cuff button closes a cuff.' },
      { from: 7, to: 8, clue: 'A cuff is the end of a sleeve.' },
      { from: 0, to: 3, clue: 'A shirt is made from fabric.' },
      { from: 3, to: 6, clue: 'A shirt can have a button.' },
      { from: 1, to: 4, clue: 'Thread forms each stitch.' },
      { from: 4, to: 7, clue: 'A cuff is secured with stitching.' },
      { from: 2, to: 5, clue: 'A needle sews a hem.' },
      { from: 5, to: 8, clue: 'A sleeve hem finishes the sleeve edge.' },
    ],
  },
  {
    title: 'Pocket Material',
    solution: [
      { word: 'Cotton', emoji: '🌿' },
      { word: 'Shirt', emoji: '👕' },
      { word: 'Collar', emoji: '👔' },
      { word: 'Denim', emoji: '👖' },
      { word: 'Jeans', emoji: '👖' },
      { word: 'Pocket', emoji: '👖' },
      { word: 'Leather', emoji: '🟫' },
      { word: 'Jacket', emoji: '🧥' },
      { word: 'Zipper', emoji: '🤐' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A cotton shirt is made from cotton.' },
      { from: 1, to: 2, clue: 'A collar is part of a shirt.' },
      { from: 3, to: 4, clue: 'Denim jeans are made from denim.' },
      { from: 4, to: 5, clue: 'Jeans usually have pockets.' },
      { from: 6, to: 7, clue: 'A leather jacket is made from leather.' },
      { from: 7, to: 8, clue: 'A jacket often closes with a zipper.' },
      { from: 0, to: 3, clue: 'Cotton and denim are both clothing fabrics.' },
      { from: 3, to: 6, clue: 'Denim and leather are both durable clothing materials.' },
      { from: 1, to: 4, clue: 'A shirt and jeans are common clothing items.' },
      { from: 4, to: 7, clue: 'Jeans and a jacket make a familiar outfit pair.' },
      { from: 2, to: 5, clue: 'Collars and pockets are both sewn garment parts.' },
      { from: 5, to: 8, clue: 'A zipper pocket closes with a zipper.' },
    ],
  },
  {
    title: 'Culture Dish',
    solution: [
      { word: 'Cell', emoji: '🦠' },
      { word: 'Culture', emoji: '🧫' },
      { word: 'Dish', emoji: '🧫' },
      { word: 'Petri', emoji: '🧫' },
      { word: 'Agar', emoji: '🟡' },
      { word: 'Colony', emoji: '🔬' },
      { word: 'Lab', emoji: '🔬' },
      { word: 'Incubator', emoji: '🌡️' },
      { word: 'Bacteria', emoji: '🦠' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A cell culture grows cells under controlled conditions.' },
      { from: 1, to: 2, clue: 'A culture dish holds a growing culture.' },
      { from: 3, to: 4, clue: 'A Petri dish often contains agar.' },
      { from: 4, to: 5, clue: 'A colony can grow on agar.' },
      { from: 6, to: 7, clue: 'A lab incubator keeps samples warm.' },
      { from: 7, to: 8, clue: 'An incubator keeps bacteria warm while they grow.' },
      { from: 0, to: 3, clue: 'Cells can grow in a Petri dish.' },
      { from: 3, to: 6, clue: 'Petri dishes are used in labs.' },
      { from: 1, to: 4, clue: 'A culture can grow on agar.' },
      { from: 4, to: 7, clue: 'Agar plates are placed in an incubator.' },
      { from: 2, to: 5, clue: 'A colony can spread across a dish.' },
      { from: 5, to: 8, clue: 'A bacterial colony is a visible group of bacteria.' },
    ],
  },
  {
    title: 'Base Solution',
    solution: [
      { word: 'Acid', emoji: '🧪' },
      { word: 'Indicator', emoji: '🟣' },
      { word: 'Drop', emoji: '💧' },
      { word: 'Base', emoji: '⬛' },
      { word: 'Liquid', emoji: '🥤' },
      { word: 'Pipette', emoji: '🧪' },
      { word: 'Solution', emoji: '🧫' },
      { word: 'Beaker', emoji: '⚗️' },
      { word: 'Flask', emoji: '⚗️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'An indicator can reveal whether a sample is acid.' },
      { from: 1, to: 2, clue: 'A drop of indicator is added to a sample.' },
      { from: 3, to: 4, clue: 'A liquid base can react with an acid.' },
      { from: 4, to: 5, clue: 'A pipette transfers liquid in small amounts.' },
      { from: 6, to: 7, clue: 'A beaker can hold a solution.' },
      { from: 7, to: 8, clue: 'Beakers and flasks are both lab glassware.' },
      { from: 0, to: 3, clue: 'Acid and base are chemical opposites.' },
      { from: 3, to: 6, clue: 'A base solution contains a dissolved base.' },
      { from: 1, to: 4, clue: 'A liquid indicator changes color during a test.' },
      { from: 4, to: 7, clue: 'A beaker holds liquid during experiments.' },
      { from: 2, to: 5, clue: 'A pipette releases one drop at a time.' },
      { from: 5, to: 8, clue: 'A pipette can add liquid to a flask.' },
    ],
  },
  {
    title: 'Storm Signal',
    solution: [
      { word: 'Cloud', emoji: '☁️' },
      { word: 'Rain', emoji: '🌧️' },
      { word: 'Patter', emoji: '💧' },
      { word: 'Storm', emoji: '⛈️' },
      { word: 'Thunder', emoji: '🌩️' },
      { word: 'Rumble', emoji: '🔊' },
      { word: 'Lightning', emoji: '⚡' },
      { word: 'Flash', emoji: '📸' },
      { word: 'Bang', emoji: '💥' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Rain falls from a cloud.' },
      { from: 1, to: 2, clue: 'Rain can make a steady patter.' },
      { from: 3, to: 4, clue: 'Thunder often comes with a storm.' },
      { from: 4, to: 5, clue: 'Thunder often arrives as a low rumble.' },
      { from: 6, to: 7, clue: 'A lightning flash lights up the sky.' },
      { from: 7, to: 8, clue: 'A flash-bang pairs a bright flash with a bang.' },
      { from: 0, to: 3, clue: 'A storm cloud can cover the sky.' },
      { from: 3, to: 6, clue: 'A lightning storm produces lightning.' },
      { from: 1, to: 4, clue: 'Rain and thunder often arrive in the same storm.' },
      { from: 4, to: 7, clue: 'Thunder follows the flash of lightning.' },
      { from: 2, to: 5, clue: 'Patter and rumble are both noises.' },
      { from: 5, to: 8, clue: 'Rumbles and bangs are both loud noises.' },
    ],
  },
  {
    title: 'Orbital Tail Light',
    solution: [
      { word: 'Satellite', emoji: '🛰️' },
      { word: 'Orbit', emoji: '⭕' },
      { word: 'Path', emoji: '🛤️' },
      { word: 'Planet', emoji: '🪐' },
      { word: 'Star', emoji: '⭐' },
      { word: 'Trail', emoji: '〰️' },
      { word: 'Crater', emoji: '🕳️' },
      { word: 'Comet', emoji: '☄️' },
      { word: 'Tail', emoji: '💫' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A satellite travels in an orbit.' },
      { from: 1, to: 2, clue: 'An orbit is a curved path.' },
      { from: 3, to: 4, clue: 'A planet can orbit a star.' },
      { from: 4, to: 5, clue: 'A star trail traces a star across the sky.' },
      { from: 6, to: 7, clue: 'A comet impact can make a crater.' },
      { from: 7, to: 8, clue: 'A comet has a tail.' },
      { from: 0, to: 3, clue: 'A planet can have a satellite.' },
      { from: 3, to: 6, clue: 'A planet can have a crater.' },
      { from: 1, to: 4, clue: 'A star can hold planets in orbit.' },
      { from: 4, to: 7, clue: 'A comet can orbit a star.' },
      { from: 2, to: 5, clue: 'A trail is a kind of path.' },
      { from: 5, to: 8, clue: 'To tail someone means to trail them.' },
    ],
  },
  {
    title: 'Dock Lines',
    solution: [
      { word: 'River', emoji: '🏞️' },
      { word: 'Ferry', emoji: '⛴️' },
      { word: 'Boat', emoji: '🚤' },
      { word: 'Harbor', emoji: '⚓' },
      { word: 'Dock', emoji: '🪝' },
      { word: 'Rope', emoji: '🪢' },
      { word: 'Cargo', emoji: '📦' },
      { word: 'Ship', emoji: '🚢' },
      { word: 'Anchor', emoji: '⚓' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A river ferry carries people across a river.' },
      { from: 1, to: 2, clue: 'A ferry is a boat for passengers or cars.' },
      { from: 3, to: 4, clue: 'A harbor dock is where vessels tie up.' },
      { from: 4, to: 5, clue: 'A dock rope secures a vessel.' },
      { from: 6, to: 7, clue: 'A cargo ship carries freight over water.' },
      { from: 7, to: 8, clue: 'A ship anchor holds a ship in place.' },
      { from: 0, to: 3, clue: 'A river can lead into a harbor.' },
      { from: 3, to: 6, clue: 'Cargo moves through a harbor.' },
      { from: 1, to: 4, clue: 'A ferry pulls into a dock.' },
      { from: 4, to: 7, clue: 'A ship rests alongside a dock.' },
      { from: 2, to: 5, clue: 'A boat uses rope for tying off.' },
      { from: 5, to: 8, clue: 'An anchor rope connects a boat to its anchor.' },
    ],
  },
  {
    title: 'Canal Cleat',
    solution: [
      { word: 'Canal', emoji: '🚤' },
      { word: 'Lock', emoji: '🔒' },
      { word: 'Gate', emoji: '🚪' },
      { word: 'Barge', emoji: '🚢' },
      { word: 'Tug', emoji: '🚤' },
      { word: 'Rope', emoji: '🪢' },
      { word: 'Harbor', emoji: '⚓' },
      { word: 'Dock', emoji: '🪝' },
      { word: 'Cleat', emoji: '⚓' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A canal lock raises or lowers boats in a canal.' },
      { from: 1, to: 2, clue: 'A lock gate opens and closes the lock chamber.' },
      { from: 3, to: 4, clue: 'A tug pushes or pulls a barge.' },
      { from: 4, to: 5, clue: 'A tug uses a rope to pull another vessel.' },
      { from: 6, to: 7, clue: 'A harbor dock receives boats in a harbor.' },
      { from: 7, to: 8, clue: 'A dock cleat holds a tied line.' },
      { from: 0, to: 3, clue: 'A barge can travel along a canal.' },
      { from: 3, to: 6, clue: 'A barge can carry cargo through a harbor.' },
      { from: 1, to: 4, clue: 'A tug can guide a vessel through a lock.' },
      { from: 4, to: 7, clue: 'A tug can dock a larger vessel.' },
      { from: 2, to: 5, clue: 'A rope can hold a gate closed.' },
      { from: 5, to: 8, clue: 'A rope can be wrapped around a cleat.' },
    ],
  },
].map(withCurrentGeneration);