import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
	author: 'GitHub Copilot',
	model: 'openai/gpt-5.5-high',
	provider: 'github-copilot',
	generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
	return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G1: PuzzleDraft[] = [
	{
		solution: [
			{ word: 'Caterpillar', emoji: '🐛' },
			{ word: 'Leaf', emoji: '🍃' },
			{ word: 'Vein', emoji: '🪴' },
			{ word: 'Butterfly', emoji: '🦋' },
			{ word: 'Flower', emoji: '🌸' },
			{ word: 'Petal', emoji: '🌼' },
			{ word: 'Bee', emoji: '🐝' },
			{ word: 'Nectar', emoji: '🍯' },
			{ word: 'Pollen', emoji: '🌾' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A caterpillar eats leaves as it grows.' },
			{ from: 1, to: 2, clue: 'A leaf has veins running through it.' },
			{ from: 3, to: 4, clue: 'A butterfly visits a flower for food.' },
			{ from: 4, to: 5, clue: 'A petal is part of a flower.' },
			{ from: 6, to: 7, clue: 'A bee gathers nectar from blossoms.' },
			{ from: 7, to: 8, clue: 'Nectar and pollen are both gathered from flowers.' },
			{ from: 0, to: 3, clue: 'A caterpillar becomes a butterfly.' },
			{ from: 3, to: 6, clue: 'Butterflies and bees are both pollinating insects.' },
			{ from: 1, to: 4, clue: 'Leaves and flowers are parts of a plant.' },
			{ from: 4, to: 7, clue: 'Flowers produce nectar.' },
			{ from: 2, to: 5, clue: 'Veins and petals are visible plant structures.' },
			{ from: 5, to: 8, clue: 'Pollen often rests on a flower petal.' },
		],
	},
	{
		solution: [
			{ word: 'Bread', emoji: '🍞' },
			{ word: 'Crumb', emoji: '🍞' },
			{ word: 'Trail', emoji: '🥾' },
			{ word: 'Butter', emoji: '🧈' },
			{ word: 'Knife', emoji: '🔪' },
			{ word: 'Edge', emoji: '📐' },
			{ word: 'Steak', emoji: '🥩' },
			{ word: 'Sauce', emoji: '🥫' },
			{ word: 'Pan', emoji: '🍳' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Breadcrumbs are small pieces of bread.' },
			{ from: 1, to: 2, clue: 'A crumb trail marks a path with crumbs.' },
			{ from: 3, to: 4, clue: 'A butter knife spreads butter.' },
			{ from: 4, to: 5, clue: 'A knife edge is the sharp side of a knife.' },
			{ from: 6, to: 7, clue: 'Steak sauce is served with steak.' },
			{ from: 7, to: 8, clue: 'A saucepan is a pan for heating sauce.' },
			{ from: 0, to: 3, clue: 'Bread and butter are a classic pair.' },
			{ from: 3, to: 6, clue: 'Butter can be melted over steak.' },
			{ from: 1, to: 4, clue: 'A knife can scrape crumbs from a board or plate.' },
			{ from: 4, to: 7, clue: 'A knife can spread sauce.' },
			{ from: 2, to: 5, clue: 'A trail edge is the side of a walking trail.' },
			{ from: 5, to: 8, clue: 'A pan edge is the rim around a pan.' },
		],
	},
	{
		solution: [
			{ word: 'Canal', emoji: '🚤' },
			{ word: 'Ferry', emoji: '⛴️' },
			{ word: 'Boat', emoji: '🚤' },
			{ word: 'Harbor', emoji: '⚓' },
			{ word: 'Dock', emoji: '🪝' },
			{ word: 'Crane', emoji: '🏗️' },
			{ word: 'Cargo', emoji: '📦' },
			{ word: 'Ship', emoji: '🚢' },
			{ word: 'Operator', emoji: '🕹️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A canal ferry carries people across a canal.' },
			{ from: 1, to: 2, clue: 'A ferry is a boat built for passengers or cars.' },
			{ from: 3, to: 4, clue: 'A harbor dock is where vessels tie up.' },
			{ from: 4, to: 5, clue: 'A dock crane lifts heavy cargo.' },
			{ from: 6, to: 7, clue: 'A cargo ship carries containers overseas.' },
			{ from: 7, to: 8, clue: 'A ship operator runs commercial vessels.' },
			{ from: 0, to: 3, clue: 'A canal can connect inland water to a harbor.' },
			{ from: 3, to: 6, clue: 'Cargo moves through the harbor in huge volumes.' },
			{ from: 1, to: 4, clue: 'A ferry pulls into the dock at each stop.' },
			{ from: 4, to: 7, clue: 'A ship lies alongside a dock while loading.' },
			{ from: 2, to: 5, clue: 'A crane can lift a small boat out of the water.' },
			{ from: 5, to: 8, clue: 'A crane operator controls the hoist.' },
		],
	},
	{
		solution: [
			{ word: 'Farmers', emoji: '🧑‍🌾' },
			{ word: 'Market', emoji: '🛒' },
			{ word: 'Square', emoji: '◻️' },
			{ word: 'Food', emoji: '🍜' },
			{ word: 'Hall', emoji: '🏛️' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Street', emoji: '🛣️' },
			{ word: 'City', emoji: '🌆' },
			{ word: 'Club', emoji: '🎷' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A farmers market sells produce from local farmers.' },
			{ from: 1, to: 2, clue: 'A market square is an open public market space.' },
			{ from: 3, to: 4, clue: 'A food hall gathers many counters under one roof.' },
			{ from: 4, to: 5, clue: 'A dance hall is built for music and movement.' },
			{ from: 6, to: 7, clue: 'A city street stays busy from morning to night.' },
			{ from: 7, to: 8, clue: 'A city club comes alive after dark.' },
			{ from: 0, to: 3, clue: 'Farmers grow the food sold at market.' },
			{ from: 3, to: 6, clue: 'Street food is cooked to eat on the go.' },
			{ from: 1, to: 4, clue: 'A market hall holds vendor stalls indoors.' },
			{ from: 4, to: 7, clue: 'City hall houses the mayor and city offices.' },
			{ from: 2, to: 5, clue: 'A square dance is called in sets.' },
			{ from: 5, to: 8, clue: 'A dance club fills up once the music starts.' },
		],
	},
	{
		solution: [
			{ word: 'City', emoji: '🏙️' },
			{ word: 'Shuttle', emoji: '🚐' },
			{ word: 'Stop', emoji: '🚏' },
			{ word: 'Street', emoji: '🛣️' },
			{ word: 'Sign', emoji: '🚸' },
			{ word: 'Traffic', emoji: '🚦' },
			{ word: 'Bike', emoji: '🚲' },
			{ word: 'Lane', emoji: '↔️' },
			{ word: 'Driver', emoji: '🧑‍✈️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A city shuttle carries riders around town.' },
			{ from: 1, to: 2, clue: 'A shuttle stop marks where the shuttle picks up riders.' },
			{ from: 3, to: 4, clue: 'A street sign tells you where you are.' },
			{ from: 4, to: 5, clue: 'Traffic signs control how vehicles move.' },
			{ from: 6, to: 7, clue: 'A bike lane gives cyclists dedicated space.' },
			{ from: 7, to: 8, clue: 'A driver is expected to stay in the correct lane.' },
			{ from: 0, to: 3, clue: 'A city street is part of daily urban life.' },
			{ from: 3, to: 6, clue: 'A street bike is built for paved roads.' },
			{ from: 1, to: 4, clue: 'A shuttle sign shows route numbers or arrival information.' },
			{ from: 4, to: 7, clue: 'A lane sign tells drivers which way they may go.' },
			{ from: 2, to: 5, clue: 'A traffic stop pulls a driver over.' },
			{ from: 5, to: 8, clue: 'A driver has to read the traffic ahead.' },
		],
	},
	{
		solution: [
			{ word: 'Clock', emoji: '🕒' },
			{ word: 'Radio', emoji: '📻' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Alarm', emoji: '🚨' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Fire', emoji: '🔥' },
			{ word: 'Power', emoji: '⚡' },
			{ word: 'House', emoji: '🏠' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A clock radio is a bedside clock with a radio.' },
			{ from: 1, to: 2, clue: 'A radio show is broadcast by radio.' },
			{ from: 3, to: 4, clue: 'An alarm line is a channel used for emergency alarms.' },
			{ from: 4, to: 5, clue: 'A line dance keeps dancers in formation.' },
			{ from: 6, to: 7, clue: 'Firepower is the force of weapons or engines.' },
			{ from: 7, to: 8, clue: 'A powerhouse is a source of great power.' },
			{ from: 0, to: 3, clue: 'An alarm clock wakes people up.' },
			{ from: 3, to: 6, clue: 'A fire alarm warns people to leave.' },
			{ from: 1, to: 4, clue: 'A radio line connects callers or stations.' },
			{ from: 4, to: 7, clue: 'A power line carries electricity.' },
			{ from: 2, to: 5, clue: 'A show dance is choreographed for an audience.' },
			{ from: 5, to: 8, clue: 'House dance is a club dance style.' },
		],
	},
	{
		solution: [
			{ word: 'Cab', emoji: '🚚' },
			{ word: 'Taxi', emoji: '🚕' },
			{ word: 'Stand', emoji: '🪧' },
			{ word: 'Van', emoji: '🚐' },
			{ word: 'Driver', emoji: '🧑‍✈️' },
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Delivery', emoji: '📦' },
			{ word: 'Route', emoji: '🗺️' },
			{ word: 'Stop', emoji: '🚏' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A taxi cab is hailed at the curb.' },
			{ from: 1, to: 2, clue: 'A taxi stand is where cabs queue for fares.' },
			{ from: 3, to: 4, clue: 'A van driver moves passengers or parcels through town.' },
			{ from: 4, to: 5, clue: 'A bus driver follows the route and the schedule.' },
			{ from: 6, to: 7, clue: 'A delivery route strings many stops into one run.' },
			{ from: 7, to: 8, clue: 'A route is made up of planned stops.' },
			{ from: 0, to: 3, clue: 'A cab and a van can both carry passengers for hire.' },
			{ from: 3, to: 6, clue: 'A delivery van drops parcels block by block.' },
			{ from: 1, to: 4, clue: 'A taxi driver works the city streets for hire.' },
			{ from: 4, to: 7, clue: 'A driver follows an assigned route through the city.' },
			{ from: 2, to: 5, clue: 'A bus stand gives riders a place to wait.' },
			{ from: 5, to: 8, clue: 'A bus stop marks where riders board and exit.' },
		],
	},
	{
		solution: [
			{ word: 'Band', emoji: '🎸' },
			{ word: 'Stand', emoji: '🪑' },
			{ word: 'Microphone', emoji: '🎤' },
			{ word: 'Sheet', emoji: '📄' },
			{ word: 'Music', emoji: '🎵' },
			{ word: 'Note', emoji: '🎶' },
			{ word: 'Violin', emoji: '🎻' },
			{ word: 'String', emoji: '🧵' },
			{ word: 'Bow', emoji: '🏹' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A bandstand is built for performers.' },
			{ from: 1, to: 2, clue: 'A microphone stand holds the mic.' },
			{ from: 3, to: 4, clue: 'Sheet music is printed on the page.' },
			{ from: 4, to: 5, clue: 'Notes make up music.' },
			{ from: 6, to: 7, clue: 'Violins use strings.' },
			{ from: 7, to: 8, clue: 'A bowstring is the string on a bow.' },
			{ from: 0, to: 3, clue: 'A band reads from sheets or parts.' },
			{ from: 3, to: 6, clue: 'Violin sheet music is sold in books.' },
			{ from: 1, to: 4, clue: 'A music stand holds the pages up.' },
			{ from: 4, to: 7, clue: 'String music is a familiar section title.' },
			{ from: 2, to: 5, clue: 'Singers hit notes into a microphone.' },
			{ from: 5, to: 8, clue: 'A violin bow can play a note.' },
		],
	},
	{
		solution: [
			{ word: 'Subway', emoji: '🚇' },
			{ word: 'Train', emoji: '🚆' },
			{ word: 'Engine', emoji: '🚂' },
			{ word: 'Police', emoji: '👮' },
			{ word: 'Station', emoji: '🚉' },
			{ word: 'Fire', emoji: '🔥' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Alarm', emoji: '🚨' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Subway trains move commuters through the city.' },
			{ from: 1, to: 2, clue: 'A train engine pulls the cars behind it.' },
			{ from: 3, to: 4, clue: 'A police station is the base for a precinct.' },
			{ from: 4, to: 5, clue: 'A fire station houses engines and crews.' },
			{ from: 6, to: 7, clue: 'A doghouse gives a pet shelter outside.' },
			{ from: 7, to: 8, clue: 'A house alarm warns of danger or intrusion.' },
			{ from: 0, to: 3, clue: 'Subway police patrol stations and platforms.' },
			{ from: 3, to: 6, clue: 'A police dog helps track suspects and scents.' },
			{ from: 1, to: 4, clue: 'A train station is where the journey begins.' },
			{ from: 4, to: 7, clue: 'A station house is the building behind the badge.' },
			{ from: 2, to: 5, clue: 'A fire engine is built to answer emergencies.' },
			{ from: 5, to: 8, clue: 'A fire alarm tells everyone to get out.' },
		],
	},
	{
		solution: [
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Rabbit', emoji: '🐇' },
			{ word: 'Pet', emoji: '🐾' },
			{ word: 'Food', emoji: '🍲' },
			{ word: 'Bowl', emoji: '🥣' },
			{ word: 'Bird', emoji: '🐦' },
			{ word: 'Cage', emoji: '🐦🏠' },
			{ word: 'Seed', emoji: '🌾' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A doghouse shelters a dog.' },
			{ from: 1, to: 2, clue: 'A house rabbit lives indoors as a pet.' },
			{ from: 3, to: 4, clue: 'Pet food fills the cupboard.' },
			{ from: 4, to: 5, clue: 'Food goes in the bowl.' },
			{ from: 6, to: 7, clue: 'A cage holds a bird.' },
			{ from: 7, to: 8, clue: 'Seed belongs in a feeder or cage tray.' },
			{ from: 0, to: 3, clue: 'Dogs are common pets.' },
			{ from: 3, to: 6, clue: 'Birds can be pets too.' },
			{ from: 1, to: 4, clue: 'Food is kept in the house.' },
			{ from: 4, to: 7, clue: 'Caged birds still need food.' },
			{ from: 2, to: 5, clue: 'Rabbits can eat pellets or greens from bowls.' },
			{ from: 5, to: 8, clue: 'A bowl can hold seed.' },
		],
	},
].map(withCurrentGeneration);
