import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G6: PuzzleDraft[] = [
  {
    title: 'Flour Power Lunch',
    solution: [
      { word: 'Flour', emoji: '🌾' },
      { word: 'Dough', emoji: '🥣' },
      { word: 'Butter', emoji: '🧈' },
      { word: 'Bread', emoji: '🍞' },
      { word: 'Slice', emoji: '🔪' },
      { word: 'Knife', emoji: '🔪' },
      { word: 'Plate', emoji: '🍽️' },
      { word: 'Dish', emoji: '🍽️' },
      { word: 'Towel', emoji: '🧻' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Dough is made from flour.' },
      { from: 1, to: 2, clue: 'Butter can be mixed into dough.' },
      { from: 3, to: 4, clue: 'A slice can be cut from a loaf of bread.' },
      { from: 4, to: 5, clue: 'A knife cuts a slice.' },
      { from: 6, to: 7, clue: 'A plate is a flat dish.' },
      { from: 7, to: 8, clue: 'A dish towel dries dishes.' },
      { from: 0, to: 3, clue: 'Bread is baked from flour.' },
      { from: 1, to: 4, clue: 'Dough can be divided into slices before baking.' },
      { from: 2, to: 5, clue: 'A butter knife spreads butter.' },
      { from: 3, to: 6, clue: 'A bread plate is used for serving bread.' },
      { from: 4, to: 7, clue: 'A dish can hold several slices.' },
      { from: 5, to: 8, clue: 'A towel wipes a clean knife dry.' },
    ],
  },
  {
    title: 'Sink Side Story',
    solution: [
      { word: 'Sink', emoji: '🚰' },
      { word: 'Faucet', emoji: '🚰' },
      { word: 'Handle', emoji: '🔧' },
      { word: 'Soap', emoji: '🧼' },
      { word: 'Sponge', emoji: '🧽' },
      { word: 'Scrubber', emoji: '🧽' },
      { word: 'Dish', emoji: '🍽️' },
      { word: 'Rack', emoji: '🗄️' },
      { word: 'Towel', emoji: '🧻' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A faucet is mounted over a sink.' },
      { from: 1, to: 2, clue: 'A faucet has a handle for turning water on.' },
      { from: 3, to: 4, clue: 'Soap goes on a sponge for washing.' },
      { from: 4, to: 5, clue: 'A scrubber is a tougher kind of sponge.' },
      { from: 6, to: 7, clue: 'A dish rack holds dishes while they dry.' },
      { from: 7, to: 8, clue: 'A towel rack holds a towel.' },
      { from: 0, to: 3, clue: 'Soap is kept by a sink for handwashing.' },
      { from: 1, to: 4, clue: 'A sponge is rinsed under a faucet.' },
      { from: 2, to: 5, clue: 'A scrubber can have a handle for gripping.' },
      { from: 3, to: 6, clue: 'A soap dish holds a bar of soap.' },
      { from: 4, to: 7, clue: 'A sponge rack lets a wet sponge drain.' },
      { from: 5, to: 8, clue: 'A towel wipes away the mess after scrubbing.' },
    ],
  },
  {
    title: 'Coffee Break Cake',
    solution: [
      { word: 'Coffee', emoji: '☕' },
      { word: 'Bean', emoji: '🫘' },
      { word: 'Bowl', emoji: '🥣' },
      { word: 'Mug', emoji: '☕' },
      { word: 'Spoon', emoji: '🥄' },
      { word: 'Tea', emoji: '🍵' },
      { word: 'Saucer', emoji: '🍽️' },
      { word: 'Cup', emoji: '☕' },
      { word: 'Cake', emoji: '🍰' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A coffee bean is roasted to make coffee.' },
      { from: 1, to: 2, clue: 'A bowl can hold beans.' },
      { from: 3, to: 4, clue: 'A spoon stirs a drink in a mug.' },
      { from: 4, to: 5, clue: 'A teaspoon is a small spoon for tea.' },
      { from: 6, to: 7, clue: 'A cup and saucer are a classic pair.' },
      { from: 7, to: 8, clue: 'A cupcake is a small cake.' },
      { from: 0, to: 3, clue: 'A coffee mug holds coffee.' },
      { from: 1, to: 4, clue: 'A spoon can scoop beans.' },
      { from: 2, to: 5, clue: 'A tea bowl is used for serving tea.' },
      { from: 3, to: 6, clue: 'A saucer can sit under a mug.' },
      { from: 4, to: 7, clue: 'A spoon stirs a drink in a cup.' },
      { from: 5, to: 8, clue: 'A tea cake is served with tea.' },
    ],
  },
  {
    title: 'Lunchbox Logic',
    solution: [
      { word: 'Sandwich', emoji: '🥪' },
      { word: 'Bread', emoji: '🍞' },
      { word: 'Box', emoji: '📦' },
      { word: 'Cheese', emoji: '🧀' },
      { word: 'Milk', emoji: '🥛' },
      { word: 'Carton', emoji: '🥛' },
      { word: 'Apple', emoji: '🍎' },
      { word: 'Smoothie', emoji: '🥤' },
      { word: 'Straw', emoji: '🥤' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A sandwich is made with bread.' },
      { from: 1, to: 2, clue: 'A bread box stores bread.' },
      { from: 3, to: 4, clue: 'Cheese is made from milk.' },
      { from: 4, to: 5, clue: 'A milk carton holds milk.' },
      { from: 6, to: 7, clue: 'An apple smoothie can be made from apples.' },
      { from: 7, to: 8, clue: 'A straw is used to drink a smoothie.' },
      { from: 0, to: 3, clue: 'A cheese sandwich has cheese inside.' },
      { from: 1, to: 4, clue: 'Milk bread is a soft bread made with milk.' },
      { from: 2, to: 5, clue: 'A carton is a paperboard box for food or drink.' },
      { from: 3, to: 6, clue: 'Apple slices and cheese are a common snack pairing.' },
      { from: 4, to: 7, clue: 'A smoothie can be made with milk.' },
      { from: 5, to: 8, clue: 'A drink carton often comes with a straw.' },
    ],
  },
  {
    title: 'Lead Between Lines',
    solution: [
      { word: 'Pencil', emoji: '✏️' },
      { word: 'Lead', emoji: '✏️' },
      { word: 'Point', emoji: '📍' },
      { word: 'Notebook', emoji: '📓' },
      { word: 'Paper', emoji: '📄' },
      { word: 'Graph', emoji: '📈' },
      { word: 'Pen', emoji: '🖊️' },
      { word: 'Ink', emoji: '🖋️' },
      { word: 'Line', emoji: '➖' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A pencil has lead for writing.' },
      { from: 1, to: 2, clue: 'Pencil lead makes a sharp point.' },
      { from: 3, to: 4, clue: 'A notebook is filled with paper.' },
      { from: 4, to: 5, clue: 'Graph paper is printed for drawing graphs.' },
      { from: 6, to: 7, clue: 'A pen writes with ink.' },
      { from: 7, to: 8, clue: 'Ink can draw a line.' },
      { from: 0, to: 3, clue: 'A pencil is used in a notebook.' },
      { from: 1, to: 4, clue: 'Lead leaves marks on paper.' },
      { from: 2, to: 5, clue: 'A point can be plotted on a graph.' },
      { from: 3, to: 6, clue: 'A pen is used in a notebook.' },
      { from: 4, to: 7, clue: 'Ink marks paper.' },
      { from: 5, to: 8, clue: 'A line graph displays data with lines.' },
    ],
  },
  {
    title: 'Shelf Control',
    solution: [
      { word: 'Library', emoji: '🏛️' },
      { word: 'Card', emoji: '🪪' },
      { word: 'Catalog', emoji: '🗂️' },
      { word: 'Book', emoji: '📖' },
      { word: 'Shelf', emoji: '🪵' },
      { word: 'Label', emoji: '🏷️' },
      { word: 'Volume', emoji: '📚' },
      { word: 'Spine', emoji: '📚' },
      { word: 'Title', emoji: '🏷️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A library card lets a borrower use a library.' },
      { from: 1, to: 2, clue: 'A card catalog organizes library cards.' },
      { from: 3, to: 4, clue: 'A bookshelf holds books.' },
      { from: 4, to: 5, clue: 'A shelf label identifies what belongs on a shelf.' },
      { from: 6, to: 7, clue: 'A volume has a spine.' },
      { from: 7, to: 8, clue: 'A spine title is printed on a book spine.' },
      { from: 0, to: 3, clue: 'A library stores books.' },
      { from: 1, to: 4, clue: 'A shelf card records the item range assigned to a shelf.' },
      { from: 2, to: 5, clue: 'A catalog label helps identify a cataloged item.' },
      { from: 3, to: 6, clue: 'A volume is a bound book.' },
      { from: 4, to: 7, clue: 'A book spine faces outward on a shelf.' },
      { from: 5, to: 8, clue: 'A label can show a title.' },
    ],
  },
  {
    title: 'Garden Bedtime',
    solution: [
      { word: 'Seed', emoji: '🌱' },
      { word: 'Soil', emoji: '🟫' },
      { word: 'Compost', emoji: '🍂' },
      { word: 'Trowel', emoji: '🛠️' },
      { word: 'Garden', emoji: '🌷' },
      { word: 'Bed', emoji: '🛏️' },
      { word: 'Hose', emoji: '💦' },
      { word: 'Water', emoji: '💧' },
      { word: 'Flower', emoji: '🌸' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A seed grows in soil.' },
      { from: 1, to: 2, clue: 'Compost enriches soil.' },
      { from: 3, to: 4, clue: 'A garden trowel is used for digging in a garden.' },
      { from: 4, to: 5, clue: 'A garden bed is a planted area.' },
      { from: 6, to: 7, clue: 'A hose carries water.' },
      { from: 7, to: 8, clue: 'Water helps a flower grow.' },
      { from: 0, to: 3, clue: 'A trowel can plant a seed.' },
      { from: 1, to: 4, clue: 'Garden soil is soil used for planting.' },
      { from: 2, to: 5, clue: 'Compost can be spread over a garden bed.' },
      { from: 3, to: 6, clue: 'A trowel and a hose are both garden tools.' },
      { from: 4, to: 7, clue: 'A garden needs water.' },
      { from: 5, to: 8, clue: 'A flower bed is planted with flowers.' },
    ],
  },
  {
    title: 'Lawn Order',
    solution: [
      { word: 'Lawn', emoji: '🌱' },
      { word: 'Mower', emoji: '🚜' },
      { word: 'Bag', emoji: '🛍️' },
      { word: 'Grass', emoji: '🌿' },
      { word: 'Clipping', emoji: '✂️' },
      { word: 'Pile', emoji: '🧺' },
      { word: 'Rake', emoji: '🧹' },
      { word: 'Leaf', emoji: '🍂' },
      { word: 'Mulch', emoji: '🟫' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A lawn mower cuts a lawn.' },
      { from: 1, to: 2, clue: 'A mower bag collects clippings.' },
      { from: 3, to: 4, clue: 'A grass clipping is a cut piece of grass.' },
      { from: 4, to: 5, clue: 'Clippings can collect in a pile.' },
      { from: 6, to: 7, clue: 'A rake gathers leaves.' },
      { from: 7, to: 8, clue: 'Leaves can break down into mulch.' },
      { from: 0, to: 3, clue: 'A lawn is covered with grass.' },
      { from: 1, to: 4, clue: 'A mower creates clippings.' },
      { from: 2, to: 5, clue: 'A bag can hold a pile of yard waste.' },
      { from: 3, to: 6, clue: 'A rake can gather loose grass.' },
      { from: 4, to: 7, clue: 'Clippings and leaves are both yard waste.' },
      { from: 5, to: 8, clue: 'A mulch pile stores mulch.' },
    ],
  },
  {
    title: 'Route Awakening',
    solution: [
      { word: 'Bus', emoji: '🚌' },
      { word: 'Route', emoji: '🗺️' },
      { word: 'Sign', emoji: '🪧' },
      { word: 'Station', emoji: '🚉' },
      { word: 'Stop', emoji: '🛑' },
      { word: 'Pole', emoji: '🪧' },
      { word: 'Crosswalk', emoji: '🚶' },
      { word: 'Light', emoji: '🚦' },
      { word: 'Beacon', emoji: '🚨' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A bus route lists where a bus travels.' },
      { from: 1, to: 2, clue: 'A route sign shows a route number or name.' },
      { from: 3, to: 4, clue: 'A station stop is a scheduled stop at a station.' },
      { from: 4, to: 5, clue: 'A stop pole holds the sign at a transit stop.' },
      { from: 6, to: 7, clue: 'A crosswalk light tells pedestrians when to cross.' },
      { from: 7, to: 8, clue: 'A beacon is a warning light.' },
      { from: 0, to: 3, clue: 'A bus station serves buses.' },
      { from: 1, to: 4, clue: 'A route includes a sequence of stops.' },
      { from: 2, to: 5, clue: 'A sign is mounted on a pole.' },
      { from: 3, to: 6, clue: 'A station crosswalk lets pedestrians reach the station safely.' },
      { from: 4, to: 7, clue: 'A stop light tells traffic to stop.' },
      { from: 5, to: 8, clue: 'A beacon can be mounted on a pole.' },
    ],
  },
  {
    title: 'Curb Appeal',
    solution: [
      { word: 'Taxi', emoji: '🚕' },
      { word: 'Driver', emoji: '🧑‍✈️' },
      { word: 'Meter', emoji: '⏲️' },
      { word: 'Cab', emoji: '🚕' },
      { word: 'Stand', emoji: '🚏' },
      { word: 'Sign', emoji: '🪧' },
      { word: 'Curb', emoji: '🧱' },
      { word: 'Sidewalk', emoji: '🚶' },
      { word: 'Ramp', emoji: '♿' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A taxi driver drives a taxi.' },
      { from: 1, to: 2, clue: 'A driver uses the meter to calculate the fare.' },
      { from: 3, to: 4, clue: 'A cab stand is a place where cabs wait.' },
      { from: 4, to: 5, clue: 'A stand sign marks where the stand begins.' },
      { from: 6, to: 7, clue: 'A curb borders a sidewalk.' },
      { from: 7, to: 8, clue: 'A sidewalk ramp slopes from the sidewalk.' },
      { from: 0, to: 3, clue: 'Taxi and cab are common words for the same vehicle.' },
      { from: 1, to: 4, clue: 'A driver waits at a stand for passengers.' },
      { from: 2, to: 5, clue: 'A meter sign displays meter rates or time limits.' },
      { from: 3, to: 6, clue: 'A cab pulls up to the curb.' },
      { from: 4, to: 7, clue: 'A sidewalk stand is a small booth set up on a sidewalk.' },
      { from: 5, to: 8, clue: 'A ramp sign points to an accessible ramp.' },
    ],
  },
].map(withCurrentGeneration);
