import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
	author: 'GitHub Copilot',
	model: 'openai/gpt-5.5-high',
	provider: 'github-copilot',
	generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
	return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_HARD_F: PuzzleDraft[] = [
	{
		title: 'Coffee Cake Shuffle',
		solution: [
			{ word: 'Bag', emoji: '🛍️' },
			{ word: 'Coffee', emoji: '🫘' },
			{ word: 'Break', emoji: '⏸️' },
			{ word: 'Paper', emoji: '📄' },
			{ word: 'Cup', emoji: '🥤' },
			{ word: 'Tea', emoji: '🍵' },
			{ word: 'Plate', emoji: '🍽️' },
			{ word: 'Cake', emoji: '🍰' },
			{ word: 'Mug', emoji: '☕' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A bag can package coffee before brewing.' },
			{ from: 1, to: 2, clue: 'A coffee break is the workday pause.' },
			{ from: 3, to: 4, clue: 'A paper cup is the disposable vessel.' },
			{ from: 4, to: 5, clue: 'A teacup is a cup for tea.' },
			{ from: 6, to: 7, clue: 'A cake plate carries the slice.' },
			{ from: 7, to: 8, clue: 'A mug cake bakes in the vessel.' },
			{ from: 0, to: 3, clue: 'A paper bag is the foldable carrier.' },
			{ from: 1, to: 4, clue: 'A coffee cup holds the hot drink.' },
			{ from: 2, to: 5, clue: 'A tea break is the other hot pause.' },
			{ from: 3, to: 6, clue: 'A paper plate is the disposable dish.' },
			{ from: 4, to: 7, clue: 'A cupcake names the cake by its little cup.' },
			{ from: 5, to: 8, clue: 'A tea mug is the sturdy hot-drink vessel.' },
		],
	},
	{
		title: 'Shade Flight Path',
		solution: [
			{ word: 'Sun', emoji: '🌞' },
			{ word: 'Shade', emoji: '⛱️' },
			{ word: 'Lamp', emoji: '🪔' },
			{ word: 'Moon', emoji: '🌙' },
			{ word: 'Light', emoji: '🔆' },
			{ word: 'Bulb', emoji: '💡' },
			{ word: 'Night', emoji: '🌌' },
			{ word: 'Flight', emoji: '✈️' },
			{ word: 'Path', emoji: '🛤️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A sunshade blocks the sun.' },
			{ from: 1, to: 2, clue: 'A lampshade softens a lamp.' },
			{ from: 3, to: 4, clue: 'Moonlight is light reflected from the moon.' },
			{ from: 4, to: 5, clue: 'A light bulb makes the glow.' },
			{ from: 6, to: 7, clue: 'A night flight leaves after dark.' },
			{ from: 7, to: 8, clue: 'A flight path is the planned line through air.' },
			{ from: 0, to: 3, clue: 'Sun and moon are the classic sky pair.' },
			{ from: 1, to: 4, clue: 'Shade is what cuts down light.' },
			{ from: 2, to: 5, clue: 'A lamp needs a bulb to shine.' },
			{ from: 3, to: 6, clue: 'The moon is most visible in the night sky.' },
			{ from: 4, to: 7, clue: 'Aircraft lights make a flight visible.' },
			{ from: 5, to: 8, clue: 'Flower bulbs can line a garden path.' },
		],
	},
	{
		title: 'Nest Hive Breakfast',
		solution: [
			{ word: 'Bird', emoji: '🐦' },
			{ word: 'Nest', emoji: '🪺' },
			{ word: 'Egg', emoji: '🥚' },
			{ word: 'Bee', emoji: '🐝' },
			{ word: 'Hive', emoji: '🐝🏠' },
			{ word: 'Honey', emoji: '🍯' },
			{ word: 'Cow', emoji: '🐄' },
			{ word: 'Barn', emoji: '🏚️' },
			{ word: 'Milk', emoji: '🥛' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A bird builds a nest.' },
			{ from: 1, to: 2, clue: 'A nest holds the egg.' },
			{ from: 3, to: 4, clue: 'A bee lives in a hive.' },
			{ from: 4, to: 5, clue: 'A hive stores honey.' },
			{ from: 6, to: 7, clue: 'A cow stands in a barn.' },
			{ from: 7, to: 8, clue: 'A milk barn is a dairy building for collecting milk.' },
			{ from: 0, to: 3, clue: 'Birds and bees are the familiar nature-talk pair.' },
			{ from: 1, to: 4, clue: 'Nest and hive are animal homes.' },
			{ from: 2, to: 5, clue: 'Egg and honey both land at breakfast.' },
			{ from: 3, to: 6, clue: 'Bee and cow are familiar farm creatures.' },
			{ from: 4, to: 7, clue: 'Hive and barn both shelter working animals.' },
			{ from: 5, to: 8, clue: 'Honey sweetens warm milk.' },
		],
	},
	{
		title: 'Message Board Memo',
		solution: [
			{ word: 'Voice', emoji: '🗣️' },
			{ word: 'Mail', emoji: '✉️' },
			{ word: 'Box', emoji: '📦' },
			{ word: 'Text', emoji: '💬' },
			{ word: 'Message', emoji: '📨' },
			{ word: 'Card', emoji: '💌' },
			{ word: 'Note', emoji: '📝' },
			{ word: 'Board', emoji: '🪧' },
			{ word: 'Paper', emoji: '📄' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Voicemail is mail left by voice.' },
			{ from: 1, to: 2, clue: 'A mailbox holds the mail.' },
			{ from: 3, to: 4, clue: 'A text message is the short written item.' },
			{ from: 4, to: 5, clue: 'A card can carry a short message.' },
			{ from: 6, to: 7, clue: 'A board can hold a pinned note.' },
			{ from: 7, to: 8, clue: 'Paperboard is stiff paper.' },
			{ from: 0, to: 3, clue: 'Voice and text are message channels.' },
			{ from: 1, to: 4, clue: 'Mail carries a message.' },
			{ from: 2, to: 5, clue: 'A card box stores cards.' },
			{ from: 3, to: 6, clue: 'A note can be written as text.' },
			{ from: 4, to: 7, clue: 'A message board collects public posts.' },
			{ from: 5, to: 8, clue: 'A card is usually made of paper.' },
		],
	},
	{
		title: 'Garage Hook Loop',
		solution: [
			{ word: 'Garage', emoji: '🏠' },
			{ word: 'Tool', emoji: '🛠️' },
			{ word: 'Belt', emoji: '👖' },
			{ word: 'Door', emoji: '🚪' },
			{ word: 'Hook', emoji: '🪝' },
			{ word: 'Loop', emoji: '➰' },
			{ word: 'Latch', emoji: '🔒' },
			{ word: 'Lock', emoji: '🔐' },
			{ word: 'Chain', emoji: '⛓️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Garage tools live near the workbench.' },
			{ from: 1, to: 2, clue: 'A tool belt carries hand tools.' },
			{ from: 3, to: 4, clue: 'A door hook fastens or hangs on a door.' },
			{ from: 4, to: 5, clue: 'Hook and loop fasteners press together.' },
			{ from: 6, to: 7, clue: 'A latch lock keeps a gate shut.' },
			{ from: 7, to: 8, clue: 'A chain lock secures a bike or gate.' },
			{ from: 0, to: 3, clue: 'A garage door opens to the storage bay.' },
			{ from: 1, to: 4, clue: 'A tool hook keeps one tool on the wall.' },
			{ from: 2, to: 5, clue: 'A belt loop holds the belt.' },
			{ from: 3, to: 6, clue: 'A door latch catches the door.' },
			{ from: 4, to: 7, clue: 'A hook lock uses a hooked bolt.' },
			{ from: 5, to: 8, clue: 'A chain is made from linked loops.' },
		],
	},
	{
		title: 'Gate Signal Lane',
		solution: [
			{ word: 'Air', emoji: '✈️' },
			{ word: 'Port', emoji: '⚓' },
			{ word: 'Road', emoji: '🚗' },
			{ word: 'Fare', emoji: '💵' },
			{ word: 'Gate', emoji: '🚪' },
			{ word: 'Toll', emoji: '🪙' },
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Signal', emoji: '🚦' },
			{ word: 'Lane', emoji: '🛣️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'An airport is the port for air travel.' },
			{ from: 1, to: 2, clue: 'A port road carries traffic into a port.' },
			{ from: 3, to: 4, clue: 'A fare gate opens after payment.' },
			{ from: 4, to: 5, clue: 'A toll gate controls paid entry.' },
			{ from: 6, to: 7, clue: 'A bus signal gives buses priority.' },
			{ from: 7, to: 8, clue: 'A lane signal opens or closes a lane.' },
			{ from: 0, to: 3, clue: 'Airfare is the price of flying.' },
			{ from: 1, to: 4, clue: 'A port gate controls port entry.' },
			{ from: 2, to: 5, clue: 'A toll road charges drivers to use the road.' },
			{ from: 3, to: 6, clue: 'A bus fare is the price of the ride.' },
			{ from: 4, to: 7, clue: 'A gate signal warns that a gate is moving.' },
			{ from: 5, to: 8, clue: 'A toll lane is where drivers pay.' },
		],
	},
	{
		title: 'Glue Gun Strip',
		solution: [
			{ word: 'Wood', emoji: '🪵' },
			{ word: 'Glue', emoji: '🧴' },
			{ word: 'Tube', emoji: '🧪' },
			{ word: 'Nail', emoji: '🔩' },
			{ word: 'Gun', emoji: '🛠️' },
			{ word: 'Paint', emoji: '🎨' },
			{ word: 'Point', emoji: '📍' },
			{ word: 'Staple', emoji: '📎' },
			{ word: 'Strip', emoji: '📏' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Wood glue bonds wood.' },
			{ from: 1, to: 2, clue: 'Glue often comes in a squeeze tube.' },
			{ from: 3, to: 4, clue: 'A nail gun drives nails.' },
			{ from: 4, to: 5, clue: 'A paint gun sprays paint.' },
			{ from: 6, to: 7, clue: 'A staple has sharp points.' },
			{ from: 7, to: 8, clue: 'A staple strip is a row of staples.' },
			{ from: 0, to: 3, clue: 'A nail fastens into wood.' },
			{ from: 1, to: 4, clue: 'A glue gun heats glue.' },
			{ from: 2, to: 5, clue: 'Paint can come in a tube.' },
			{ from: 3, to: 6, clue: 'The point is the sharp end of a nail.' },
			{ from: 4, to: 7, clue: 'A staple gun drives staples.' },
			{ from: 5, to: 8, clue: 'A paint strip is a sample card of color bands.' },
		],
	},
	{
		title: 'Cloud Storm Mix',
		solution: [
			{ word: 'Cloud', emoji: '☁️' },
			{ word: 'Thunder', emoji: '🔊' },
			{ word: 'Shower', emoji: '🌦️' },
			{ word: 'Hail', emoji: '🧊' },
			{ word: 'Storm', emoji: '⛈️' },
			{ word: 'Rain', emoji: '🌧️' },
			{ word: 'Pellet', emoji: '⚪' },
			{ word: 'Snow', emoji: '❄️' },
			{ word: 'Sleet', emoji: '🌨️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A thundercloud carries thunder.' },
			{ from: 1, to: 2, clue: 'A thundershower mixes thunder with a shower.' },
			{ from: 3, to: 4, clue: 'A hailstorm drops hail.' },
			{ from: 4, to: 5, clue: 'A rainstorm is a storm with rain.' },
			{ from: 6, to: 7, clue: 'Snow pellets are small grains of snow.' },
			{ from: 7, to: 8, clue: 'Snow and sleet are frozen precipitation.' },
			{ from: 0, to: 3, clue: 'Hail falls from a cloud.' },
			{ from: 1, to: 4, clue: 'A thunderstorm is a storm with thunder.' },
			{ from: 2, to: 5, clue: 'A rain shower is a short fall of rain.' },
			{ from: 3, to: 6, clue: 'Hail pellets are small balls of hail.' },
			{ from: 4, to: 7, clue: 'A snowstorm is a storm with snow.' },
			{ from: 5, to: 8, clue: 'Sleet is frozen rain.' },
		],
	},
	{
		title: 'Parcel File Cabinet',
		solution: [
			{ word: 'Parcel', emoji: '🎁' },
			{ word: 'Post', emoji: '📮' },
			{ word: 'Office', emoji: '🏢' },
			{ word: 'Letter', emoji: '✉️' },
			{ word: 'Box', emoji: '📦' },
			{ word: 'Shelf', emoji: '📚' },
			{ word: 'Paper', emoji: '📄' },
			{ word: 'File', emoji: '📁' },
			{ word: 'Cabinet', emoji: '🗄️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Parcel post carries parcels.' },
			{ from: 1, to: 2, clue: 'A post office handles the post.' },
			{ from: 3, to: 4, clue: 'A letterbox receives letters.' },
			{ from: 4, to: 5, clue: 'A storage box can sit on a shelf.' },
			{ from: 6, to: 7, clue: 'A file stores paper documents.' },
			{ from: 7, to: 8, clue: 'A file cabinet stores files.' },
			{ from: 0, to: 3, clue: 'Parcel and letter both travel by mail.' },
			{ from: 1, to: 4, clue: 'A postbox collects outgoing post.' },
			{ from: 2, to: 5, clue: 'An office shelf stores office supplies.' },
			{ from: 3, to: 6, clue: 'Letter paper is paper for a letter.' },
			{ from: 4, to: 7, clue: 'A file box stores files.' },
			{ from: 5, to: 8, clue: 'A cabinet can have an adjustable shelf.' },
		],
	},
	{
		title: 'Operator Track Team',
		solution: [
			{ word: 'Bus', emoji: '🚌' },
			{ word: 'Operator', emoji: '🕹️' },
			{ word: 'Seat', emoji: '💺' },
			{ word: 'Station', emoji: '🚉' },
			{ word: 'Train', emoji: '🚆' },
			{ word: 'Coach', emoji: '🧑‍🏫' },
			{ word: 'Rail', emoji: '🚊' },
			{ word: 'Track', emoji: '🛤️' },
			{ word: 'Team', emoji: '👥' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A bus operator runs the bus.' },
			{ from: 1, to: 2, clue: 'The operator seat faces the controls.' },
			{ from: 3, to: 4, clue: 'A train station serves trains.' },
			{ from: 4, to: 5, clue: 'A train coach is a passenger car.' },
			{ from: 6, to: 7, clue: 'A rail track carries trains.' },
			{ from: 7, to: 8, clue: 'A track team runs track events.' },
			{ from: 0, to: 3, clue: 'A bus station serves buses.' },
			{ from: 1, to: 4, clue: 'A train operator runs the train.' },
			{ from: 2, to: 5, clue: 'A coach seat is one place to sit.' },
			{ from: 3, to: 6, clue: 'A rail station serves rail travel.' },
			{ from: 4, to: 7, clue: 'A train track carries the train.' },
			{ from: 5, to: 8, clue: 'A coach leads the team.' },
		],
	},
].map(withCurrentGeneration);