import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
	author: 'GitHub Copilot',
	model: 'openai/gpt-5.5-high',
	provider: 'github-copilot',
	generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
	return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_HARD_E: PuzzleDraft[] = [
	{
		title: 'Terminal Claim Check',
		solution: [
			{ word: 'Airport', emoji: '🛫' },
			{ word: 'Terminal', emoji: '🏢' },
			{ word: 'Gate', emoji: '🚪' },
			{ word: 'Baggage', emoji: '🧳' },
			{ word: 'Claim', emoji: '🎟️' },
			{ word: 'Ticket', emoji: '🎫' },
			{ word: 'Carousel', emoji: '🎠' },
			{ word: 'Belt', emoji: '🧷' },
			{ word: 'Seat', emoji: '💺' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Flights begin inside this passenger building.' },
			{ from: 1, to: 2, clue: 'The passenger building funnels travelers to this numbered exit.' },
			{ from: 3, to: 4, clue: 'Checked bags reappear under this airport phrase.' },
			{ from: 4, to: 5, clue: 'Together they name the receipt used to retrieve stored property.' },
			{ from: 6, to: 7, clue: 'The rotating pickup machine runs on this loop.' },
			{ from: 7, to: 8, clue: 'The buckle belongs across this assigned place.' },
			{ from: 0, to: 3, clue: 'The travel hub is built around moving these checked items.' },
			{ from: 1, to: 4, clue: 'The pickup area usually sits inside the passenger building.' },
			{ from: 2, to: 5, clue: 'The agent checks this paper or phone pass before boarding.' },
			{ from: 3, to: 6, clue: 'Checked items circle on this pickup machine.' },
			{ from: 4, to: 7, clue: 'The pickup area uses this moving conveyor.' },
			{ from: 5, to: 8, clue: 'The pass names where the traveler sits.' },
		],
	},
	{
		title: 'Bench Bit Driver',
		solution: [
			{ word: 'Board', emoji: '🪵' },
			{ word: 'Saw', emoji: '🪚' },
			{ word: 'Blade', emoji: '🔪' },
			{ word: 'Hole', emoji: '🕳️' },
			{ word: 'Drill', emoji: '🛠️' },
			{ word: 'Handle', emoji: '🧰' },
			{ word: 'Screw', emoji: '🪛' },
			{ word: 'Bit', emoji: '⚙️' },
			{ word: 'Driver', emoji: '🪛' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The cutting tool earns its keep on the plank.' },
			{ from: 1, to: 2, clue: 'The teeth are on this cutting edge.' },
			{ from: 3, to: 4, clue: 'The rotating tool makes this opening.' },
			{ from: 4, to: 5, clue: 'The power tool is steadied by this grip.' },
			{ from: 6, to: 7, clue: 'The fastener head accepts this small metal tip.' },
			{ from: 7, to: 8, clue: 'The turning tool holds this replaceable tip.' },
			{ from: 0, to: 3, clue: 'The opening can be bored through this plank.' },
			{ from: 1, to: 4, clue: 'Both are basic bench tools, one cutting and one boring.' },
			{ from: 2, to: 5, clue: 'A cutting edge is safer when held by this grip.' },
			{ from: 3, to: 6, clue: 'Together they name the opening made for a threaded fastener.' },
			{ from: 4, to: 7, clue: 'The rotating tool spins this replaceable tip.' },
			{ from: 5, to: 8, clue: 'The turning tool is controlled from this grip.' },
		],
	},
	{
		title: 'Bread Board Jam',
		solution: [
			{ word: 'Board', emoji: '🧀' },
			{ word: 'Bread', emoji: '🍞' },
			{ word: 'Jam', emoji: '🍓' },
			{ word: 'Knife', emoji: '🔪' },
			{ word: 'Toast', emoji: '🍞' },
			{ word: 'Butter', emoji: '🧈' },
			{ word: 'Fork', emoji: '🍴' },
			{ word: 'Plate', emoji: '🍽️' },
			{ word: 'Dish', emoji: '🍽️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Together they name the cutting surface for a loaf.' },
			{ from: 1, to: 2, clue: 'The slice takes this fruit spread.' },
			{ from: 3, to: 4, clue: 'The browned slice is cut or spread with this tool.' },
			{ from: 4, to: 5, clue: 'The browned slice takes this dairy spread.' },
			{ from: 6, to: 7, clue: 'The table utensil rests beside this flat dish.' },
			{ from: 7, to: 8, clue: 'Both words can name the vessel food is served on.' },
			{ from: 0, to: 3, clue: 'The cutting surface pairs naturally with this sharp tool.' },
			{ from: 1, to: 4, clue: 'Heat turns the slice into the browned version.' },
			{ from: 2, to: 5, clue: 'Both are common breakfast spreads.' },
			{ from: 3, to: 6, clue: 'Together they name the matched utensils set at dinner.' },
			{ from: 4, to: 7, clue: 'The browned slice is served on this flat dish.' },
			{ from: 5, to: 8, clue: 'Together they name the small covered vessel kept on a table.' },
		],
	},
	{
		title: 'Track Signal Gate',
		solution: [
			{ word: 'Train', emoji: '🚆' },
			{ word: 'Track', emoji: '🛤️' },
			{ word: 'Signal', emoji: '🚦' },
			{ word: 'Station', emoji: '🚉' },
			{ word: 'Platform', emoji: '🚉' },
			{ word: 'Light', emoji: '💡' },
			{ word: 'Ticket', emoji: '🎫' },
			{ word: 'Gate', emoji: '🚪' },
			{ word: 'Rail', emoji: '🚆' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The rail vehicle needs this fixed path.' },
			{ from: 1, to: 2, clue: 'The fixed path is governed by this colored command.' },
			{ from: 3, to: 4, clue: 'Passengers wait beside the rails on this raised edge.' },
			{ from: 4, to: 5, clue: 'The waiting edge needs this glow after dark.' },
			{ from: 6, to: 7, clue: 'The pass opens this controlled entrance.' },
			{ from: 7, to: 8, clue: 'The barrier drops where the line crosses the road.' },
			{ from: 0, to: 3, clue: 'The rail vehicle stops at this passenger place.' },
			{ from: 1, to: 4, clue: 'The waiting edge sits alongside the fixed path.' },
			{ from: 2, to: 5, clue: 'The command is shown by this glow.' },
			{ from: 3, to: 6, clue: 'The passenger place sells this pass.' },
			{ from: 4, to: 7, clue: 'The raised waiting edge often begins behind this entrance.' },
			{ from: 5, to: 8, clue: 'Together they name a street-running urban transit system.' },
		],
	},
	{
		title: 'Cold Front Cover',
		solution: [
			{ word: 'Cold', emoji: '🥶' },
			{ word: 'Front', emoji: '🌬️' },
			{ word: 'Door', emoji: '🚪' },
			{ word: 'Storm', emoji: '⛈️' },
			{ word: 'Cloud', emoji: '☁️' },
			{ word: 'Cover', emoji: '☂️' },
			{ word: 'Rain', emoji: '🌧️' },
			{ word: 'Drop', emoji: '💧' },
			{ word: 'Cloth', emoji: '🧽' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The air boundary brings the temperature down.' },
			{ from: 1, to: 2, clue: 'The main entrance uses the same facing word.' },
			{ from: 3, to: 4, clue: 'The dark mass announces bad weather.' },
			{ from: 4, to: 5, clue: 'The sky layer can blanket everything below.' },
			{ from: 6, to: 7, clue: 'One bead of the shower carries the wet word.' },
			{ from: 7, to: 8, clue: 'Painters spread this sheet before the drips fall.' },
			{ from: 0, to: 3, clue: 'The hard weather often arrives with falling temperatures.' },
			{ from: 1, to: 4, clue: 'The moving weather boundary builds the gray mass.' },
			{ from: 2, to: 5, clue: 'An entry can sit under this shelter.' },
			{ from: 3, to: 6, clue: 'The bad weather often turns into this falling water.' },
			{ from: 4, to: 7, clue: 'The gray mass releases one wet bead at a time.' },
			{ from: 5, to: 8, clue: 'A protective sheet is exactly this kind of fabric.' },
		],
	},
	{
		title: 'Gauge Pressure Ride',
		solution: [
			{ word: 'Rain', emoji: '🌧️' },
			{ word: 'Gauge', emoji: '📏' },
			{ word: 'Needle', emoji: '🪡' },
			{ word: 'Pressure', emoji: '🌡️' },
			{ word: 'Valve', emoji: '⚙️' },
			{ word: 'Stem', emoji: '🌱' },
			{ word: 'Bike', emoji: '🚲' },
			{ word: 'Pump', emoji: '⛽' },
			{ word: 'Tire', emoji: '🛞' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The little instrument measures how much fell.' },
			{ from: 1, to: 2, clue: 'The dial points with this thin marker.' },
			{ from: 3, to: 4, clue: 'The safety fitting opens when the force climbs too high.' },
			{ from: 4, to: 5, clue: 'Air enters through this small protruding part.' },
			{ from: 6, to: 7, clue: 'The two-wheeler needs this tool after a soft ride.' },
			{ from: 7, to: 8, clue: 'The tool restores air to the rubber ring.' },
			{ from: 0, to: 3, clue: 'Weather reports track both wet totals and air force.' },
			{ from: 1, to: 4, clue: 'The measuring dial often screws onto this fitting.' },
			{ from: 2, to: 5, clue: 'The pointer is fixed to this small shaft.' },
			{ from: 3, to: 6, clue: 'The two-wheeler rides badly when this number is low.' },
			{ from: 4, to: 7, clue: 'The inflation tool locks onto this fitting.' },
			{ from: 5, to: 8, clue: 'The rubber ring exposes this small air inlet.' },
		],
	},
	{
		title: 'Signal Box Beat',
		solution: [
			{ word: 'Radio', emoji: '📻' },
			{ word: 'Wave', emoji: '🌊' },
			{ word: 'Signal', emoji: '📶' },
			{ word: 'Guitar', emoji: '🎸' },
			{ word: 'Amp', emoji: '🔊' },
			{ word: 'Speaker', emoji: '🔈' },
			{ word: 'Drum', emoji: '🥁' },
			{ word: 'Beat', emoji: '🎵' },
			{ word: 'Box', emoji: '📦' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Broadcast sound rides this invisible oscillation.' },
			{ from: 1, to: 2, clue: 'The oscillation carries the transmitted message.' },
			{ from: 3, to: 4, clue: 'The electric instrument gets loud through this box.' },
			{ from: 4, to: 5, clue: 'The amplifier sends sound through this cone.' },
			{ from: 6, to: 7, clue: 'The percussion instrument supplies this pulse.' },
			{ from: 7, to: 8, clue: 'The mouth-made percussion style joins these words.' },
			{ from: 0, to: 3, clue: 'Both can drive a song through the room.' },
			{ from: 1, to: 4, clue: 'The amplifier makes the waveform larger.' },
			{ from: 2, to: 5, clue: 'The sound unit turns the electrical message audible.' },
			{ from: 3, to: 6, clue: 'Both are core band instruments.' },
			{ from: 4, to: 7, clue: 'The amplifier carries the rhythmic pulse to the crowd.' },
			{ from: 5, to: 8, clue: 'The sound unit often lives inside this cabinet.' },
		],
	},
	{
		title: 'Scorecard Playbook',
		solution: [
			{ word: 'Score', emoji: '🎯' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Trick', emoji: '🪄' },
			{ word: 'Board', emoji: '🧩' },
			{ word: 'Game', emoji: '🎮' },
			{ word: 'Play', emoji: '▶️' },
			{ word: 'Clock', emoji: '🕒' },
			{ word: 'Time', emoji: '⏰' },
			{ word: 'Book', emoji: '📖' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Points are logged on this little record.' },
			{ from: 1, to: 2, clue: 'The little rectangle makes the magician look impossible.' },
			{ from: 3, to: 4, clue: 'The tabletop pastime starts on this flat surface.' },
			{ from: 4, to: 5, clue: 'Interaction is the live part of the contest.' },
			{ from: 6, to: 7, clue: 'The device exists to show this measured quantity.' },
			{ from: 7, to: 8, clue: 'Payroll can keep hours in this old record.' },
			{ from: 0, to: 3, clue: 'The public points display joins these words.' },
			{ from: 1, to: 4, clue: 'The shuffled deck becomes the whole contest.' },
			{ from: 2, to: 5, clue: 'Together they name a deceptive call designed to fool the defense.' },
			{ from: 3, to: 6, clue: 'Timed tabletop games may put this device beside the surface.' },
			{ from: 4, to: 7, clue: 'The contest begins when this moment is called.' },
			{ from: 5, to: 8, clue: 'The coach keeps scripted moves here.' },
		],
	},
	{
		title: 'Route Guidepost',
		solution: [
			{ word: 'Road', emoji: '🛣️' },
			{ word: 'Trip', emoji: '🧳' },
			{ word: 'Plan', emoji: '📝' },
			{ word: 'Map', emoji: '🗺️' },
			{ word: 'Route', emoji: '↪️' },
			{ word: 'Guide', emoji: '🧭' },
			{ word: 'Trail', emoji: '🥾' },
			{ word: 'Marker', emoji: '📍' },
			{ word: 'Post', emoji: '📮' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The drive becomes the vacation under this phrase.' },
			{ from: 1, to: 2, clue: 'The journey behaves better after this outline exists.' },
			{ from: 3, to: 4, clue: 'The paper or app shows this chosen path.' },
			{ from: 4, to: 5, clue: 'The chosen path can be explained by this navigator.' },
			{ from: 6, to: 7, clue: 'The hiking path is confirmed by this sign.' },
			{ from: 7, to: 8, clue: 'The sign needs this upright support.' },
			{ from: 0, to: 3, clue: 'The route drawing tells the driver where the pavement goes.' },
			{ from: 1, to: 4, clue: 'The journey follows this chosen line.' },
			{ from: 2, to: 5, clue: 'The navigator turns the outline into usable steps.' },
			{ from: 3, to: 6, clue: 'Together they name the diagram hikers use to follow a path.' },
			{ from: 4, to: 7, clue: 'The chosen line is confirmed by signs along it.' },
			{ from: 5, to: 8, clue: 'The upright sign gives directions in one word.' },
		],
	},
	{
		title: 'Bell Desk Gate',
		solution: [
			{ word: 'Hotel', emoji: '🏨' },
			{ word: 'Bell', emoji: '🛎️' },
			{ word: 'Desk', emoji: '🧾' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Agent', emoji: '🧑‍💼' },
			{ word: 'Key', emoji: '🔑' },
			{ word: 'Door', emoji: '🚪' },
			{ word: 'Gate', emoji: '🚪' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'The lobby chime summons help in this place.' },
			{ from: 1, to: 2, clue: 'The lobby station keeps the call button close.' },
			{ from: 3, to: 4, clue: 'The tray arrives upstairs under this phrase.' },
			{ from: 4, to: 5, clue: 'The support worker answers requests under this phrase.' },
			{ from: 6, to: 7, clue: 'The opener belongs in this entryway.' },
			{ from: 7, to: 8, clue: 'Both are controlled entrances.' },
			{ from: 0, to: 3, clue: 'The lodging sells this private space by the night.' },
			{ from: 1, to: 4, clue: 'Guest help once arrived after this lobby signal.' },
			{ from: 2, to: 5, clue: 'Together they name the worker at the front counter.' },
			{ from: 3, to: 6, clue: 'The private space needs this opener.' },
			{ from: 4, to: 7, clue: 'Together they name a staff entrance used away from guests.' },
			{ from: 5, to: 8, clue: 'Together they name the worker who manages an entrance.' },
		],
	},
].map(withCurrentGeneration);