import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G10: PuzzleDraft[] = [
  {
    title: 'Vitals Loop',
    solution: [
      { word: 'Heart', emoji: '❤️' },
      { word: 'Rate', emoji: '📈' },
      { word: 'Monitor', emoji: '🖥️' },
      { word: 'Blood', emoji: '🩸' },
      { word: 'Pressure', emoji: '🧭' },
      { word: 'Cuff', emoji: '🩺' },
      { word: 'Pulse', emoji: '💓' },
      { word: 'Nurse', emoji: '🧑‍⚕️' },
      { word: 'Chart', emoji: '📋' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Heart rate is the number of heartbeats per minute.' },
      { from: 1, to: 2, clue: 'A rate monitor displays a measured rate.' },
      { from: 3, to: 4, clue: 'Blood pressure measures the force of blood flow.' },
      { from: 4, to: 5, clue: 'A pressure cuff wraps around the arm for a pressure reading.' },
      { from: 6, to: 7, clue: 'A nurse checks a patient\'s pulse.' },
      { from: 7, to: 8, clue: 'A nurse updates a medical chart.' },
      { from: 0, to: 3, clue: 'The heart pumps blood through the body.' },
      { from: 3, to: 6, clue: 'A pulse is created by blood moving through arteries.' },
      { from: 1, to: 4, clue: 'Rate and pressure are both vital-sign readings.' },
      { from: 4, to: 7, clue: 'A nurse takes a patient\'s pressure.' },
      { from: 2, to: 5, clue: 'A blood pressure monitor connects to a cuff.' },
      { from: 5, to: 8, clue: 'A cuff reading is recorded on a chart.' },
    ],
  },
  {
    title: 'Bakery Bench',
    solution: [
      { word: 'Flour', emoji: '🌾' },
      { word: 'Sifter', emoji: '🧺' },
      { word: 'Bowl', emoji: '🥣' },
      { word: 'Bread', emoji: '🍞' },
      { word: 'Dough', emoji: '🥖' },
      { word: 'Pan', emoji: '🍳' },
      { word: 'Cake', emoji: '🍰' },
      { word: 'Cutter', emoji: '🔪' },
      { word: 'Handle', emoji: '🖐️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A flour sifter breaks up clumps in flour.' },
      { from: 1, to: 2, clue: 'A sifter is held over a bowl.' },
      { from: 3, to: 4, clue: 'Bread dough rises before baking.' },
      { from: 4, to: 5, clue: 'Dough is placed in a pan to bake.' },
      { from: 6, to: 7, clue: 'A cake cutter divides cake into neat pieces.' },
      { from: 7, to: 8, clue: 'A cutter has a handle.' },
      { from: 0, to: 3, clue: 'Bread is made from flour.' },
      { from: 3, to: 6, clue: 'Bread and cake are both baked goods.' },
      { from: 1, to: 4, clue: 'A sifter adds fine flour into dough.' },
      { from: 4, to: 7, clue: 'A dough cutter portions dough.' },
      { from: 2, to: 5, clue: 'A bowl and a pan are both kitchen vessels.' },
      { from: 5, to: 8, clue: 'A pan has a handle.' },
    ],
  },
  {
    title: 'Game Table',
    solution: [
      { word: 'Puzzle', emoji: '🧩' },
      { word: 'Piece', emoji: '🧩' },
      { word: 'Fit', emoji: '✅' },
      { word: 'Board', emoji: '🎲' },
      { word: 'Game', emoji: '🎮' },
      { word: 'Tile', emoji: '🔲' },
      { word: 'Card', emoji: '🃏' },
      { word: 'Deck', emoji: '🂠' },
      { word: 'Hand', emoji: '✋' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A puzzle piece is one part of a puzzle.' },
      { from: 1, to: 2, clue: 'A piece must fit into its correct place.' },
      { from: 3, to: 4, clue: 'A board game is played on a board.' },
      { from: 4, to: 5, clue: 'A game tile is a movable piece in many games.' },
      { from: 6, to: 7, clue: 'A card deck contains playing cards.' },
      { from: 7, to: 8, clue: 'A deck is dealt into a player\'s hand.' },
      { from: 0, to: 3, clue: 'A puzzle board holds a puzzle while it is assembled.' },
      { from: 3, to: 6, clue: 'Board games and card games are tabletop games.' },
      { from: 1, to: 4, clue: 'A game piece marks a player\'s position.' },
      { from: 4, to: 7, clue: 'A game deck supplies cards for a game.' },
      { from: 2, to: 5, clue: 'A tile has to fit into its space.' },
      { from: 5, to: 8, clue: 'A hand can place a tile during play.' },
    ],
  },
  {
    title: 'Pet Supply Run',
    solution: [
      { word: 'Dog', emoji: '🐕' },
      { word: 'Collar', emoji: '🏷️' },
      { word: 'Leash', emoji: '🦮' },
      { word: 'Pet', emoji: '🐾' },
      { word: 'Tag', emoji: '🏷️' },
      { word: 'Clip', emoji: '🖇️' },
      { word: 'Cat', emoji: '🐈' },
      { word: 'Bell', emoji: '🔔' },
      { word: 'Ring', emoji: '⭕' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A dog collar fits around a dog\'s neck.' },
      { from: 1, to: 2, clue: 'A leash clips onto a collar.' },
      { from: 3, to: 4, clue: 'A pet tag identifies a pet.' },
      { from: 4, to: 5, clue: 'A tag clip fastens a tag.' },
      { from: 6, to: 7, clue: 'A cat bell is a small bell worn by a cat.' },
      { from: 7, to: 8, clue: 'A bell rings.' },
      { from: 0, to: 3, clue: 'A dog is a common pet.' },
      { from: 3, to: 6, clue: 'A cat is a common pet.' },
      { from: 1, to: 4, clue: 'A collar tag hangs from a collar.' },
      { from: 4, to: 7, clue: 'Tags and bells are both small hanging accessories.' },
      { from: 2, to: 5, clue: 'A leash clip attaches a leash.' },
      { from: 5, to: 8, clue: 'A clip can fasten onto a ring.' },
    ],
  },
  {
    title: 'Measure Twice',
    solution: [
      { word: 'Tape', emoji: '📏' },
      { word: 'Measure', emoji: '📐' },
      { word: 'Mark', emoji: '✏️' },
      { word: 'Ruler', emoji: '📏' },
      { word: 'Line', emoji: '➖' },
      { word: 'Level', emoji: '🫧' },
      { word: 'Scale', emoji: '⚖️' },
      { word: 'Weight', emoji: '🏋️' },
      { word: 'Gauge', emoji: '⏲️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A tape measure measures distance.' },
      { from: 1, to: 2, clue: 'A mark records where a measured length lands.' },
      { from: 3, to: 4, clue: 'A ruler draws a straight line.' },
      { from: 4, to: 5, clue: 'A line level checks whether a line is horizontal.' },
      { from: 6, to: 7, clue: 'A scale measures weight.' },
      { from: 7, to: 8, clue: 'A gauge can show how heavy a load is.' },
      { from: 0, to: 3, clue: 'Tape and a ruler are both measuring tools.' },
      { from: 3, to: 6, clue: 'A ruler has a printed scale.' },
      { from: 1, to: 4, clue: 'A line can be measured for length.' },
      { from: 4, to: 7, clue: 'Line weight describes how heavy a drawn line appears.' },
      { from: 2, to: 5, clue: 'A level mark shows a true horizontal height.' },
      { from: 5, to: 8, clue: 'A gauge can show whether a surface is level.' },
    ],
  },
  {
    title: 'First-Aid Kitchen',
    solution: [
      { word: 'Knife', emoji: '🔪' },
      { word: 'Cut', emoji: '🩹' },
      { word: 'Bandage', emoji: '🩹' },
      { word: 'Stove', emoji: '🔥' },
      { word: 'Burn', emoji: '♨️' },
      { word: 'Cream', emoji: '🧴' },
      { word: 'Kitchen', emoji: '🍽️' },
      { word: 'Aid', emoji: '➕' },
      { word: 'Mixer', emoji: '🥣' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A knife can cause a cut.' },
      { from: 1, to: 2, clue: 'A bandage covers a cut.' },
      { from: 3, to: 4, clue: 'A hot stove can cause a burn.' },
      { from: 4, to: 5, clue: 'Burn cream soothes a burn.' },
      { from: 6, to: 7, clue: 'KitchenAid is a well-known kitchen-appliance brand.' },
      { from: 7, to: 8, clue: 'A mixer aids cooks by combining ingredients.' },
      { from: 0, to: 3, clue: 'A knife and a stove are both kitchen tools.' },
      { from: 3, to: 6, clue: 'A stove belongs in a kitchen.' },
      { from: 1, to: 4, clue: 'A cut and a burn are both injuries.' },
      { from: 4, to: 7, clue: 'First aid treats a burn.' },
      { from: 2, to: 5, clue: 'Bandages and burn cream are both applied to injuries.' },
      { from: 5, to: 8, clue: 'A mixer can whip cream.' },
    ],
  },
  {
    title: 'Simmer Circle',
    solution: [
      { word: 'Tomato', emoji: '🍅' },
      { word: 'Sauce', emoji: '🥫' },
      { word: 'Pan', emoji: '🍳' },
      { word: 'Pasta', emoji: '🍝' },
      { word: 'Pot', emoji: '🍯' },
      { word: 'Boil', emoji: '♨️' },
      { word: 'Soup', emoji: '🍲' },
      { word: 'Stock', emoji: '🥣' },
      { word: 'Water', emoji: '💧' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Tomato sauce is made from tomatoes.' },
      { from: 1, to: 2, clue: 'A saucepan is a pan for heating sauce.' },
      { from: 3, to: 4, clue: 'A pasta pot is used for cooking pasta.' },
      { from: 4, to: 5, clue: 'A pot can bring liquid to a boil.' },
      { from: 6, to: 7, clue: 'Soup stock forms the base of soup.' },
      { from: 7, to: 8, clue: 'Stock is often made with water.' },
      { from: 0, to: 3, clue: 'Tomato is a common pasta ingredient.' },
      { from: 3, to: 6, clue: 'Pasta can be added to soup.' },
      { from: 1, to: 4, clue: 'A saucepot is a pot for sauce.' },
      { from: 4, to: 7, clue: 'A stockpot is a pot for making stock.' },
      { from: 2, to: 5, clue: 'A pan can bring sauce to a boil.' },
      { from: 5, to: 8, clue: 'Water boils when it gets hot enough.' },
    ],
  },
  {
    title: 'Scoreboard Shuffle',
    solution: [
      { word: 'Chess', emoji: '♟️' },
      { word: 'Board', emoji: '🧩' },
      { word: 'Game', emoji: '🎮' },
      { word: 'Card', emoji: '🃏' },
      { word: 'Score', emoji: '🔢' },
      { word: 'Sheet', emoji: '📄' },
      { word: 'Dice', emoji: '🎲' },
      { word: 'Roll', emoji: '🎲' },
      { word: 'Move', emoji: '➡️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A chess board is used for chess.' },
      { from: 1, to: 2, clue: 'A board game is played on a board.' },
      { from: 3, to: 4, clue: 'A scorecard records a player\'s score.' },
      { from: 4, to: 5, clue: 'A score sheet records scores.' },
      { from: 6, to: 7, clue: 'A dice roll is one throw of dice.' },
      { from: 7, to: 8, clue: 'A roll can determine a move.' },
      { from: 0, to: 3, clue: 'Chess and cards are both tabletop games.' },
      { from: 3, to: 6, clue: 'Cards and dice are both tabletop game equipment.' },
      { from: 1, to: 4, clue: 'A scoreboard displays the score.' },
      { from: 4, to: 7, clue: 'A dice roll produces a score in many dice games.' },
      { from: 2, to: 5, clue: 'A game sheet records details of a game.' },
      { from: 5, to: 8, clue: 'A sheet can list moves one by one.' },
    ],
  },
  {
    title: 'Barn Chores',
    solution: [
      { word: 'Cow', emoji: '🐄' },
      { word: 'Bell', emoji: '🔔' },
      { word: 'Rope', emoji: '🪢' },
      { word: 'Barn', emoji: '🏚️' },
      { word: 'Door', emoji: '🚪' },
      { word: 'Handle', emoji: '🖐️' },
      { word: 'Gate', emoji: '🚪' },
      { word: 'Hinge', emoji: '🚪' },
      { word: 'Screw', emoji: '🔩' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A cowbell is a bell worn by a cow.' },
      { from: 1, to: 2, clue: 'A bell rope is pulled to ring a bell.' },
      { from: 3, to: 4, clue: 'A barn door closes a barn.' },
      { from: 4, to: 5, clue: 'A door handle opens a door.' },
      { from: 6, to: 7, clue: 'A gate hinge lets a gate swing.' },
      { from: 7, to: 8, clue: 'A hinge screw fastens a hinge.' },
      { from: 0, to: 3, clue: 'A cow can live in a barn.' },
      { from: 3, to: 6, clue: 'A barn gate controls entry to a barn.' },
      { from: 1, to: 4, clue: 'A doorbell is a bell at a door.' },
      { from: 4, to: 7, clue: 'A door hinge lets a door swing.' },
      { from: 2, to: 5, clue: 'A rope handle is a handle made from rope.' },
      { from: 5, to: 8, clue: 'A handle screw secures a handle.' },
    ],
  },
  {
    title: 'Workshop Marks',
    solution: [
      { word: 'Hammer', emoji: '🔨' },
      { word: 'Nail', emoji: '📌' },
      { word: 'Head', emoji: '🔩' },
      { word: 'Tool', emoji: '🧰' },
      { word: 'Box', emoji: '📦' },
      { word: 'Driver', emoji: '🪛' },
      { word: 'Tape', emoji: '📏' },
      { word: 'Measure', emoji: '📐' },
      { word: 'Mark', emoji: '✏️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A hammer drives a nail.' },
      { from: 1, to: 2, clue: 'A nail head is the flat top of a nail.' },
      { from: 3, to: 4, clue: 'A toolbox holds tools.' },
      { from: 4, to: 5, clue: 'A driver bit is stored in a box.' },
      { from: 6, to: 7, clue: 'A tape measure measures distance.' },
      { from: 7, to: 8, clue: 'A mark records where a measurement lands.' },
      { from: 0, to: 3, clue: 'A hammer is a tool.' },
      { from: 3, to: 6, clue: 'Tape is a common tool in a toolbox.' },
      { from: 1, to: 4, clue: 'A box can hold nails.' },
      { from: 4, to: 7, clue: 'A box can be measured before cutting.' },
      { from: 2, to: 5, clue: 'A driver has a head that fits a fastener.' },
      { from: 5, to: 8, clue: 'A driver bit can leave a mark on soft material.' },
    ],
  },
].map(withCurrentGeneration);