import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
  author: 'GitHub Copilot',
  model: 'openai/gpt-5.5-high',
  provider: 'github-copilot',
  generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
  return { ...puzzle, generation: CURRENT_GENERATION };
}

export const APRIL_25_STANDARD_G5: PuzzleDraft[] = [
  {
    solution: [
      { word: 'Stone', emoji: '🪨' },
      { word: 'Wall', emoji: '🧱' },
      { word: 'Tile', emoji: '🔲' },
      { word: 'Mason', emoji: '👷' },
      { word: 'Trowel', emoji: '🧰' },
      { word: 'Grout', emoji: '🧴' },
      { word: 'Chisel', emoji: '🔨' },
      { word: 'Plaster', emoji: '⬜' },
      { word: 'Float', emoji: '🛠️' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A stone wall is built from stacked stone.' },
      { from: 1, to: 2, clue: 'Wall tile covers and protects a wall.' },
      { from: 3, to: 4, clue: 'A mason uses a trowel to spread material.' },
      { from: 4, to: 5, clue: 'A trowel spreads grout between tiles.' },
      { from: 6, to: 7, clue: 'A chisel can remove old plaster from a surface.' },
      { from: 7, to: 8, clue: 'A plaster float smooths fresh plaster.' },
      { from: 0, to: 3, clue: 'A stonemason shapes and lays stone.' },
      { from: 3, to: 6, clue: 'A mason may use a chisel to shape stone.' },
      { from: 1, to: 4, clue: 'A trowel spreads plaster or mortar on a wall.' },
      { from: 4, to: 7, clue: 'A trowel is used to apply plaster.' },
      { from: 2, to: 5, clue: 'Grout fills the seams between tiles.' },
      { from: 5, to: 8, clue: 'A grout float presses grout into tile joints.' },
    ],
  },
  {
    solution: [
      { word: 'Blood', emoji: '🩸' },
      { word: 'Pressure', emoji: '📈' },
      { word: 'Gauge', emoji: '⏲️' },
      { word: 'Arm', emoji: '💪' },
      { word: 'Cuff', emoji: '🩺' },
      { word: 'Pump', emoji: '💨' },
      { word: 'Pulse', emoji: '💓' },
      { word: 'Nurse', emoji: '🧑‍⚕️' },
      { word: 'Station', emoji: '🏥' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Blood pressure measures the force of blood flow.' },
      { from: 1, to: 2, clue: 'A pressure gauge shows the pressure reading.' },
      { from: 3, to: 4, clue: 'A blood pressure cuff wraps around the arm.' },
      { from: 4, to: 5, clue: 'The cuff pump inflates the cuff.' },
      { from: 6, to: 7, clue: 'A nurse checks a patient\'s pulse.' },
      { from: 7, to: 8, clue: 'A nurse station is the work area for nurses.' },
      { from: 0, to: 3, clue: 'Blood is often drawn from an arm.' },
      { from: 3, to: 6, clue: 'A pulse can be felt in the arm.' },
      { from: 1, to: 4, clue: 'A pressure cuff is used for blood pressure checks.' },
      { from: 4, to: 7, clue: 'A nurse places the cuff before taking a reading.' },
      { from: 2, to: 5, clue: 'A pump can have a gauge to show pressure.' },
      { from: 5, to: 8, clue: 'A pump station uses pumps to move fluid.' },
    ],
  },
  {
    solution: [
      { word: 'Flour', emoji: '🌾' },
      { word: 'Dough', emoji: '🥣' },
      { word: 'Pizza', emoji: '🍕' },
      { word: 'Bread', emoji: '🍞' },
      { word: 'Loaf', emoji: '🍞' },
      { word: 'Pan', emoji: '🍳' },
      { word: 'Butter', emoji: '🧈' },
      { word: 'Knife', emoji: '🔪' },
      { word: 'Handle', emoji: '🔧' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Dough is made from flour.' },
      { from: 1, to: 2, clue: 'Pizza dough forms the base of a pizza.' },
      { from: 3, to: 4, clue: 'A loaf is a shaped piece of bread.' },
      { from: 4, to: 5, clue: 'A loaf pan gives bread its shape.' },
      { from: 6, to: 7, clue: 'A butter knife spreads butter.' },
      { from: 7, to: 8, clue: 'A knife has a handle for gripping.' },
      { from: 0, to: 3, clue: 'Bread is baked from flour.' },
      { from: 3, to: 6, clue: 'Bread and butter are a classic pair.' },
      { from: 1, to: 4, clue: 'Dough can be shaped into a loaf.' },
      { from: 4, to: 7, clue: 'A bread knife slices a loaf.' },
      { from: 2, to: 5, clue: 'A pizza pan holds a pizza in the oven.' },
      { from: 5, to: 8, clue: 'A pan has a handle for lifting it.' },
    ],
  },
  {
    solution: [
      { word: 'River', emoji: '🏞️' },
      { word: 'Ferry', emoji: '⛴️' },
      { word: 'Boat', emoji: '🚤' },
      { word: 'Harbor', emoji: '⚓' },
      { word: 'Dock', emoji: '🪝' },
      { word: 'Crane', emoji: '🏗️' },
      { word: 'Cargo', emoji: '📦' },
      { word: 'Ship', emoji: '🚢' },
      { word: 'Operator', emoji: '🎮' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A river ferry carries people across a river.' },
      { from: 1, to: 2, clue: 'A ferry is a boat built for passengers or cars.' },
      { from: 3, to: 4, clue: 'A harbor dock is where vessels tie up.' },
      { from: 4, to: 5, clue: 'A dock crane lifts heavy cargo.' },
      { from: 6, to: 7, clue: 'A cargo ship carries freight over water.' },
      { from: 7, to: 8, clue: 'A ship operator runs commercial vessels.' },
      { from: 0, to: 3, clue: 'A river can lead into a working harbor.' },
      { from: 3, to: 6, clue: 'Cargo moves through a harbor in large volumes.' },
      { from: 1, to: 4, clue: 'A ferry pulls into a dock at each stop.' },
      { from: 4, to: 7, clue: 'A ship lies alongside a dock while loading.' },
      { from: 2, to: 5, clue: 'A crane can lift a boat out of the water.' },
      { from: 5, to: 8, clue: 'A crane operator controls the hoist.' },
    ],
  },
  {
    solution: [
      { word: 'Market', emoji: '🛒' },
      { word: 'Town', emoji: '🏘️' },
      { word: 'Square', emoji: '◻️' },
      { word: 'Food' },
      { word: 'Hall', emoji: '🏛️' },
      { word: 'Dance' },
      { word: 'Street', emoji: '🛣️' },
      { word: 'City', emoji: '🌆' },
      { word: 'Club', emoji: '🎷' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A market town is known for its regular market.' },
      { from: 1, to: 2, clue: 'A town square is the civic center of a town.' },
      { from: 3, to: 4, clue: 'A food hall gathers many food counters indoors.' },
      { from: 4, to: 5, clue: 'A dance hall is a venue for dancing.' },
      { from: 6, to: 7, clue: 'A city street carries urban traffic and pedestrians.' },
      { from: 7, to: 8, clue: 'A city club is a private or social club in a city.' },
      { from: 0, to: 3, clue: 'A food market sells produce, bread, and prepared meals.' },
      { from: 3, to: 6, clue: 'Street food is cooked to eat on the go.' },
      { from: 1, to: 4, clue: 'Town hall is where local government meets.' },
      { from: 4, to: 7, clue: 'City hall houses city offices.' },
      { from: 2, to: 5, clue: 'A square dance is called in sets.' },
      { from: 5, to: 8, clue: 'A dance club fills up when the music starts.' },
    ],
  },
  {
    solution: [
      { word: 'Transit', emoji: '🚇' },
      { word: 'Train', emoji: '🚆' },
      { word: 'Engine', emoji: '🚒' },
      { word: 'Police', emoji: '👮' },
      { word: 'Station', emoji: '🚉' },
      { word: 'Fire' },
      { word: 'Dog' },
      { word: 'House' },
      { word: 'Alarm' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Transit trains move commuters through a city.' },
      { from: 1, to: 2, clue: 'A train engine pulls the cars behind it.' },
      { from: 3, to: 4, clue: 'A police station is the base for police officers.' },
      { from: 4, to: 5, clue: 'A fire station houses engines and crews.' },
      { from: 6, to: 7, clue: 'A doghouse shelters a dog.' },
      { from: 7, to: 8, clue: 'A house alarm warns of danger or intrusion.' },
      { from: 0, to: 3, clue: 'Transit police patrol stations and platforms.' },
      { from: 3, to: 6, clue: 'A police dog helps track suspects and scents.' },
      { from: 1, to: 4, clue: 'A train station is where passengers board trains.' },
      { from: 4, to: 7, clue: 'A station house is the building for a police or fire station.' },
      { from: 2, to: 5, clue: 'A fire engine is built to answer emergencies.' },
      { from: 5, to: 8, clue: 'A fire alarm tells everyone to get out.' },
    ],
  },
  {
    solution: [
      { word: 'Bus', emoji: '🚌' },
      { word: 'Driver', emoji: '🧑‍✈️' },
      { word: 'Seat' },
      { word: 'Station', emoji: '🚉' },
      { word: 'Train', emoji: '🚆' },
      { word: 'Coach', emoji: '🚞' },
      { word: 'Rail' },
      { word: 'Track' },
      { word: 'Team', emoji: '👥' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A bus driver keeps the route moving.' },
      { from: 1, to: 2, clue: 'The driver sits in the front seat.' },
      { from: 3, to: 4, clue: 'A train station is where passengers board trains.' },
      { from: 4, to: 5, clue: 'A coach is one car of a train.' },
      { from: 6, to: 7, clue: 'Rail is laid along the track.' },
      { from: 7, to: 8, clue: 'A track team trains for running events.' },
      { from: 0, to: 3, clue: 'A bus station gathers many bus routes.' },
      { from: 3, to: 6, clue: 'A rail station serves trains instead of cars.' },
      { from: 1, to: 4, clue: 'A train driver controls the engine and brakes.' },
      { from: 4, to: 7, clue: 'A train runs on track, not on roads.' },
      { from: 2, to: 5, clue: 'A coach seat folds down for the journey.' },
      { from: 5, to: 8, clue: 'A coach trains the team.' },
    ],
  },
  {
    solution: [
      { word: 'School', emoji: '🏫' },
      { word: 'Bus', emoji: '🚌' },
      { word: 'Route', emoji: '🗺️' },
      { word: 'Desk', emoji: '🪑' },
      { word: 'Job', emoji: '💼' },
      { word: 'Service' },
      { word: 'Teacher', emoji: '🧑‍🏫' },
      { word: 'Aide', emoji: '🙋' },
      { word: 'Help', emoji: '🆘' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'A school bus picks students up each morning.' },
      { from: 1, to: 2, clue: 'A bus route lists the planned stops in order.' },
      { from: 3, to: 4, clue: 'A desk job keeps you working indoors.' },
      { from: 4, to: 5, clue: 'A service job often means helping customers.' },
      { from: 6, to: 7, clue: 'A teacher\'s aide supports the classroom.' },
      { from: 7, to: 8, clue: 'An aide is there to help when needed.' },
      { from: 0, to: 3, clue: 'A school desk is part of a classroom.' },
      { from: 3, to: 6, clue: 'A teacher works from a desk during the school day.' },
      { from: 1, to: 4, clue: 'Driving a bus can be a city job.' },
      { from: 4, to: 7, clue: 'Being an aide is a support job.' },
      { from: 2, to: 5, clue: 'Route service depends on fixed timing and stops.' },
      { from: 5, to: 8, clue: 'A help service answers questions when people get stuck.' },
    ],
  },
  {
    solution: [
      { word: 'Hen', emoji: '🐔' },
      { word: 'Nest', emoji: '🪺' },
      { word: 'Egg', emoji: '🥚' },
      { word: 'Bee', emoji: '🐝' },
      { word: 'Hive', emoji: '🐝' },
      { word: 'Honey', emoji: '🍯' },
      { word: 'Cow', emoji: '🐄' },
      { word: 'Barn', emoji: '🏚️' },
      { word: 'Milk', emoji: '🥛' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Hens lay eggs in nests.' },
      { from: 1, to: 2, clue: 'Eggs rest safely in a nest.' },
      { from: 3, to: 4, clue: 'Bees live together in a hive.' },
      { from: 4, to: 5, clue: 'A hive produces honey.' },
      { from: 6, to: 7, clue: 'Cows are kept in a barn.' },
      { from: 7, to: 8, clue: 'A dairy barn is built for producing milk.' },
      { from: 0, to: 3, clue: 'Hens and bees are both farm creatures.' },
      { from: 3, to: 6, clue: 'Bees and cows can both be kept on farms.' },
      { from: 1, to: 4, clue: 'A nest and a hive are animal homes.' },
      { from: 4, to: 7, clue: 'A hive and a barn both shelter animals.' },
      { from: 2, to: 5, clue: 'Egg and honey can both be breakfast ingredients.' },
      { from: 5, to: 8, clue: 'Honey can sweeten warm milk.' },
    ],
  },
  {
    solution: [
      { word: 'Voice', emoji: '🗣️' },
      { word: 'Mail', emoji: '✉️' },
      { word: 'Box' },
      { word: 'Text', emoji: '💬' },
      { word: 'Message', emoji: '📨' },
      { word: 'Board' },
      { word: 'Note', emoji: '📝' },
      { word: 'Pad', emoji: '📓' },
      { word: 'Paper', emoji: '📄' },
    ],
    edges: [
      { from: 0, to: 1, clue: 'Voicemail stores spoken messages.' },
      { from: 1, to: 2, clue: 'A mailbox holds the mail.' },
      { from: 3, to: 4, clue: 'A text message arrives on a phone.' },
      { from: 4, to: 5, clue: 'A message board displays public messages.' },
      { from: 6, to: 7, clue: 'A notepad is made for quick notes.' },
      { from: 7, to: 8, clue: 'A paper pad sits on a desk.' },
      { from: 0, to: 3, clue: 'Voice and text are two ways to communicate.' },
      { from: 3, to: 6, clue: 'A quick note can be sent as a text.' },
      { from: 1, to: 4, clue: 'Mail carries messages.' },
      { from: 4, to: 7, clue: 'People jot messages on a pad.' },
      { from: 2, to: 5, clue: 'Boxboard is a kind of paper stock.' },
      { from: 5, to: 8, clue: 'Paperboard is another name for board-like paper.' },
    ],
  },
].map(withCurrentGeneration);
