import type { Puzzle } from '../types';

import { HARD_BATCH_A } from './hard-batch-a';
import { HARD_BATCH_B } from './hard-batch-b';
import { STANDARD_BATCH_A } from './standard-batch-a';
import { STANDARD_BATCH_D } from './standard-batch-d';
import { STANDARD_BATCH_E } from './standard-batch-e';

export { REVIEW_HARD_BATCH_C, REVIEW_STANDARD_BATCH_F } from './practice-review-batch-f';

export const STANDARD_BATCH_EXTRA: Puzzle[] = [
	{
		solution: [
			{ word: 'Night', emoji: '🌙' },
			{ word: 'Life', emoji: '🌱' },
			{ word: 'Style', emoji: '🧥' },
			{ word: 'Watch', emoji: '⌚' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Dance', emoji: '💃' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Nightlife starts when the sun is gone.' },
			{ from: 1, to: 2, clue: 'Lifestyle describes a way of living.' },
			{ from: 3, to: 4, clue: 'A watch party gathers around the same screen.' },
			{ from: 4, to: 5, clue: 'A party line can be political or telephone-based.' },
			{ from: 6, to: 7, clue: 'A doghouse is where the apology usually starts.' },
			{ from: 7, to: 8, clue: 'House dance is a club style built for the floor.' },
			{ from: 0, to: 3, clue: 'A night watch patrols the quiet hours.' },
			{ from: 1, to: 4, clue: 'A lively guest can be the life of the party.' },
			{ from: 2, to: 5, clue: 'A style line groups related looks in one collection.' },
			{ from: 3, to: 6, clue: 'A watchdog notices trouble early.' },
			{ from: 4, to: 7, clue: 'A house party runs on borrowed chairs and loud music.' },
			{ from: 5, to: 8, clue: 'A line dance keeps everybody in formation.' },
		],
	},
	{
		solution: [
			{ word: 'Track', emoji: '🛤️' },
			{ word: 'Race', emoji: '🏁' },
			{ word: 'Day', emoji: '☀️' },
			{ word: 'Record', emoji: '🎙️' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Court', emoji: '🏛️' },
			{ word: 'Player', emoji: '🎮' },
			{ word: 'Game', emoji: '🎲' },
			{ word: 'Order', emoji: '📋' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A race track is built for speed.' },
			{ from: 1, to: 2, clue: 'Race day puts the whole grandstand on alert.' },
			{ from: 3, to: 4, clue: 'A record card logs results or performance.' },
			{ from: 4, to: 5, clue: 'A court card is a king, queen, or jack.' },
			{ from: 6, to: 7, clue: 'A player takes part in the game.' },
			{ from: 7, to: 8, clue: 'Game order decides who goes first.' },
			{ from: 0, to: 3, clue: 'Track record is the phrase for past performance.' },
			{ from: 1, to: 4, clue: 'A race card lists the day\'s events.' },
			{ from: 2, to: 5, clue: 'Everyone wants their day in court.' },
			{ from: 3, to: 6, clue: 'A record player spins vinyl.' },
			{ from: 4, to: 7, clue: 'A card game starts with a shuffle.' },
			{ from: 5, to: 8, clue: 'A court order carries legal force.' },
		],
	},
	{
		solution: [
			{ word: 'Face', emoji: '😀' },
			{ word: 'Time', emoji: '⏰' },
			{ word: 'Bomb', emoji: '💣' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Dog', emoji: '🐕' },
			{ word: 'Game', emoji: '🎲' },
			{ word: 'Point', emoji: '📍' },
			{ word: 'Guard', emoji: '💂' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Face time can mean an in-person moment or a call.' },
			{ from: 1, to: 2, clue: 'A time bomb is trouble with a clock on it.' },
			{ from: 3, to: 4, clue: 'A card show draws collectors and dealers.' },
			{ from: 4, to: 5, clue: 'A show dog is bred and trained for the ring.' },
			{ from: 6, to: 7, clue: 'Game point can end the set.' },
			{ from: 7, to: 8, clue: 'A point guard runs the offense.' },
			{ from: 0, to: 3, clue: 'A face card is a king, queen, or jack.' },
			{ from: 1, to: 4, clue: 'Showtime is when the curtains stop waiting.' },
			{ from: 2, to: 5, clue: 'A bomb dog is trained to detect explosives.' },
			{ from: 3, to: 6, clue: 'A card game lives or dies by the shuffle.' },
			{ from: 4, to: 7, clue: 'The point of a show is the moment everyone remembers.' },
			{ from: 5, to: 8, clue: 'A guard dog is hired with teeth included.' },
		],
	},
	{
		solution: [
			{ word: 'Book', emoji: '📖' },
			{ word: 'Club', emoji: '♣️' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Board', emoji: '🧩' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Game', emoji: '🎮' },
			{ word: 'Escape', emoji: '🏃' },
			{ word: 'Route', emoji: '🗺️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A book club meets to discuss the month\'s pick.' },
			{ from: 1, to: 2, clue: 'A clubhouse gives members a place to gather.' },
			{ from: 3, to: 4, clue: 'A boardroom is where agendas get serious.' },
			{ from: 4, to: 5, clue: 'Room service brings the tray upstairs.' },
			{ from: 6, to: 7, clue: 'An escape game works best when the clock is loud.' },
			{ from: 7, to: 8, clue: 'An escape route is marked for emergencies.' },
			{ from: 0, to: 3, clue: 'A board book is made for small hands.' },
			{ from: 1, to: 4, clue: 'A club room is reserved for members or meetings.' },
			{ from: 2, to: 5, clue: 'House service covers cleaning, repairs, or hospitality.' },
			{ from: 3, to: 6, clue: 'A board game belongs on the table.' },
			{ from: 4, to: 7, clue: 'An escape room locks the puzzle in around you.' },
			{ from: 5, to: 8, clue: 'A service route is the run a driver repeats.' },
		],
	},
	{
		solution: [
			{ word: 'Green', emoji: '🟩' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Party', emoji: '🎉' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Food', emoji: '🍽️' },
			{ word: 'School', emoji: '🏫' },
			{ word: 'Public', emoji: '🏛️' },
			{ word: 'Market', emoji: '🛒' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A green room waits just offstage.' },
			{ from: 1, to: 2, clue: 'A party room is booked for the noisy part of the evening.' },
			{ from: 3, to: 4, clue: 'House service keeps a hotel or large home running.' },
			{ from: 4, to: 5, clue: 'Food service is the business of cooking and serving meals.' },
			{ from: 6, to: 7, clue: 'A public school is state-funded and open to the community.' },
			{ from: 7, to: 8, clue: 'A public market gathers many stalls in one place.' },
			{ from: 0, to: 3, clue: 'A greenhouse traps warmth for growing plants.' },
			{ from: 1, to: 4, clue: 'Room service arrives with a tray and a knock.' },
			{ from: 2, to: 5, clue: 'Party food disappears before dinner ever settles in.' },
			{ from: 3, to: 6, clue: 'A schoolhouse is the classic one-room classroom term.' },
			{ from: 4, to: 7, clue: 'Public service is work done for the broader community.' },
			{ from: 5, to: 8, clue: 'A food market sells produce, bread, and prepared bites.' },
		],
	},
	{
		solution: [
			{ word: 'Court', emoji: '⚖️' },
			{ word: 'Night', emoji: '🌙' },
			{ word: 'School', emoji: '🏫' },
			{ word: 'Traffic', emoji: '🚦' },
			{ word: 'Light', emoji: '💡' },
			{ word: 'House', emoji: '🏠' },
			{ word: 'Signal', emoji: '📶' },
			{ word: 'Green', emoji: '🟩' },
			{ word: 'Tea', emoji: '🍵' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A night court handles cases after ordinary hours.' },
			{ from: 1, to: 2, clue: 'Night school runs after the workday.' },
			{ from: 3, to: 4, clue: 'A traffic light controls the intersection.' },
			{ from: 4, to: 5, clue: 'A lighthouse warns ships off trouble.' },
			{ from: 6, to: 7, clue: 'A green signal means go.' },
			{ from: 7, to: 8, clue: 'Green tea is the gentler cup.' },
			{ from: 0, to: 3, clue: 'Traffic court handles driving violations.' },
			{ from: 1, to: 4, clue: 'A night light makes dark rooms easier to cross.' },
			{ from: 2, to: 5, clue: 'A schoolhouse is the classic term for a school building.' },
			{ from: 3, to: 6, clue: 'A traffic signal is the formal term for the light at the junction.' },
			{ from: 4, to: 7, clue: 'A green light means permission to proceed.' },
			{ from: 5, to: 8, clue: 'A tea house promises a slower hour.' },
		],
	},
	{
		solution: [
			{ word: 'Clock', emoji: '🕒' },
			{ word: 'Radio', emoji: '📻' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Alarm', emoji: '🚨' },
			{ word: 'Line', emoji: '➖' },
			{ word: 'Dance', emoji: '💃' },
			{ word: 'Fire', emoji: '🔥' },
			{ word: 'Power', emoji: '⚡' },
			{ word: 'House', emoji: '🏠' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A clock radio is a bedside classic.' },
			{ from: 1, to: 2, clue: 'A radio show lives on voices and timing.' },
			{ from: 3, to: 4, clue: 'An alarm line is a number or channel meant for emergencies.' },
			{ from: 4, to: 5, clue: 'A line dance keeps the row in step.' },
			{ from: 6, to: 7, clue: 'Firepower is force measured the destructive way.' },
			{ from: 7, to: 8, clue: 'A powerhouse dominates the field.' },
			{ from: 0, to: 3, clue: 'An alarm clock is how many mornings begin.' },
			{ from: 1, to: 4, clue: 'A radio line opens the phones to callers.' },
			{ from: 2, to: 5, clue: 'A show dance is choreographed for an audience.' },
			{ from: 3, to: 6, clue: 'A fire alarm clears the building in a hurry.' },
			{ from: 4, to: 7, clue: 'A power line carries electricity across distance.' },
			{ from: 5, to: 8, clue: 'House dance is a club style built for the floor.' },
		],
	},
];

export const MERGED_STANDARD_PUZZLES: Puzzle[] = [
	...STANDARD_BATCH_A,
	...STANDARD_BATCH_D,
	...STANDARD_BATCH_E,
	...STANDARD_BATCH_EXTRA,
];

export const MERGED_HARD_PUZZLES: Puzzle[] = [
	...HARD_BATCH_A,
	HARD_BATCH_B[0],
	HARD_BATCH_B[3],
	HARD_BATCH_B[4],
	HARD_BATCH_B[7],
	HARD_BATCH_B[9],
];