import type { PuzzleDraft } from '../types';

const CURRENT_GENERATION: NonNullable<PuzzleDraft['generation']> = {
	author: 'GitHub Copilot',
	model: 'openai/gpt-5.5-high',
	provider: 'github-copilot',
	generatedAt: '2026-04-25',
};

function withCurrentGeneration(puzzle: PuzzleDraft): PuzzleDraft {
	return { ...puzzle, generation: CURRENT_GENERATION };
}

export const REVIEW_STANDARD_BATCH_F: PuzzleDraft[] = [
	{
		solution: [
			{ word: 'Spoon', emoji: '🥄' },
			{ word: 'Soup', emoji: '🍲' },
			{ word: 'Crouton', emoji: '🥖' },
			{ word: 'Whisk', emoji: '🥣' },
			{ word: 'Egg', emoji: '🥚' },
			{ word: 'Toast', emoji: '🍞' },
			{ word: 'Flour', emoji: '🌾' },
			{ word: 'Roll', emoji: '🥐' },
			{ word: 'Jam', emoji: '🍓' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A soup spoon is made for eating soup.' },
			{ from: 1, to: 2, clue: 'Croutons are often served on top of soup.' },
			{ from: 3, to: 4, clue: 'A whisk beats an egg.' },
			{ from: 4, to: 5, clue: 'Egg on toast is a common dish.' },
			{ from: 6, to: 7, clue: 'A roll is baked from flour.' },
			{ from: 7, to: 8, clue: 'Jam is commonly spread on a roll.' },
			{ from: 0, to: 3, clue: 'A spoon and a whisk are both kitchen utensils.' },
			{ from: 3, to: 6, clue: 'A whisk blends flour into a mixture.' },
			{ from: 1, to: 4, clue: 'Egg can thicken or enrich a bowl of soup.' },
			{ from: 4, to: 7, clue: 'An egg roll is a familiar food.' },
			{ from: 2, to: 5, clue: 'A crouton is made from toasted bread.' },
			{ from: 5, to: 8, clue: 'Jam is commonly spread on toast.' },
		],
	},
	{
		solution: [
			{ word: 'Sea', emoji: '🌊' },
			{ word: 'Green', emoji: '🟩' },
			{ word: 'Signal', emoji: '🚦' },
			{ word: 'Bed', emoji: '🛏️' },
			{ word: 'Room', emoji: '🚪' },
			{ word: 'Service', emoji: '🛎️' },
			{ word: 'Flower', emoji: '🌸' },
			{ word: 'Show', emoji: '🎭' },
			{ word: 'Business', emoji: '💼' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Sea green is a blue-green color named for ocean water.' },
			{ from: 1, to: 2, clue: 'A green signal means permission to go.' },
			{ from: 3, to: 4, clue: 'A bedroom is the room where the bed belongs.' },
			{ from: 4, to: 5, clue: 'Room service brings the tray to the door.' },
			{ from: 6, to: 7, clue: 'A flower show displays blooms for judges and visitors.' },
			{ from: 7, to: 8, clue: 'Show business is the world of stage and screen.' },
			{ from: 0, to: 3, clue: 'The seabed is the ground beneath the sea.' },
			{ from: 3, to: 6, clue: 'A flower bed is planted with flowers.' },
			{ from: 1, to: 4, clue: 'A green room waits just offstage.' },
			{ from: 4, to: 7, clue: 'A showroom is a room where products are displayed.' },
			{ from: 2, to: 5, clue: 'A signal service sends notices or alerts.' },
			{ from: 5, to: 8, clue: 'A service business sells help rather than goods.' },
		],
	},
	{
		solution: [
			{ word: 'Air', emoji: '✈️' },
			{ word: 'Port', emoji: '⚓' },
			{ word: 'Authority', emoji: '🏛️' },
			{ word: 'Fare', emoji: '💵' },
			{ word: 'Gate', emoji: '🚪' },
			{ word: 'Toll', emoji: '🪙' },
			{ word: 'Train', emoji: '🚆' },
			{ word: 'Signal', emoji: '🚦' },
			{ word: 'Lane', emoji: '🛣️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'An airport is a port for air travel.' },
			{ from: 1, to: 2, clue: 'A port authority manages a port.' },
			{ from: 3, to: 4, clue: 'A fare gate opens after a rider pays.' },
			{ from: 4, to: 5, clue: 'A toll gate controls paid entry.' },
			{ from: 6, to: 7, clue: 'A train signal tells trains when to stop or go.' },
			{ from: 7, to: 8, clue: 'A lane signal shows whether a traffic lane is open.' },
			{ from: 0, to: 3, clue: 'Airfare is the price of air travel.' },
			{ from: 3, to: 6, clue: 'A train fare is the price of a train ride.' },
			{ from: 1, to: 4, clue: 'A port gate controls entry to a port.' },
			{ from: 4, to: 7, clue: 'A gate signal warns when a gate is closing.' },
			{ from: 2, to: 5, clue: 'A toll authority manages toll collection.' },
			{ from: 5, to: 8, clue: 'A toll lane is a lane where drivers pay a toll.' },
		],
	},
	{
		solution: [
			{ word: 'Stamp', emoji: '🏷️' },
			{ word: 'Envelope', emoji: '✉️' },
			{ word: 'Flap', emoji: '📨' },
			{ word: 'Lamp', emoji: '💡' },
			{ word: 'Stand', emoji: '🧍' },
			{ word: 'Folder', emoji: '📁' },
			{ word: 'Plug', emoji: '🔌' },
			{ word: 'Keyboard', emoji: '⌨️' },
			{ word: 'Tab', emoji: '🔖' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A stamp is placed on an envelope for postage.' },
			{ from: 1, to: 2, clue: 'An envelope has a flap that folds closed.' },
			{ from: 3, to: 4, clue: 'A lamp stand supports a lamp.' },
			{ from: 4, to: 5, clue: 'A stand can hold folders upright.' },
			{ from: 6, to: 7, clue: 'A wired keyboard can use a plug.' },
			{ from: 7, to: 8, clue: 'Tab is a key on a keyboard.' },
			{ from: 0, to: 3, clue: 'Stamp and lamp rhyme.' },
			{ from: 3, to: 6, clue: 'A lamp uses a plug for power.' },
			{ from: 1, to: 4, clue: 'An envelope can rest upright in a desk stand.' },
			{ from: 4, to: 7, clue: 'A keyboard stand raises a keyboard.' },
			{ from: 2, to: 5, clue: 'A folder can have a flap that folds over its contents.' },
			{ from: 5, to: 8, clue: 'A folder tab helps identify the folder.' },
		],
	},
	{
		solution: [
			{ word: 'Wood', emoji: '🪵' },
			{ word: 'Glue', emoji: '🧴' },
			{ word: 'Tube', emoji: '🧪' },
			{ word: 'Nail', emoji: '🔩' },
			{ word: 'Gun', emoji: '🛠️' },
			{ word: 'Caulk', emoji: '🛁' },
			{ word: 'Point', emoji: '📍' },
			{ word: 'Staple', emoji: '📎' },
			{ word: 'Strip', emoji: '📏' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Wood glue bonds wooden pieces.' },
			{ from: 1, to: 2, clue: 'Glue is often sold in a squeeze tube.' },
			{ from: 3, to: 4, clue: 'A nail gun drives nails.' },
			{ from: 4, to: 5, clue: 'A caulk gun dispenses caulk.' },
			{ from: 6, to: 7, clue: 'A staple has sharp points.' },
			{ from: 7, to: 8, clue: 'A staple strip is a joined row of staples.' },
			{ from: 0, to: 3, clue: 'A nail fastens into wood.' },
			{ from: 3, to: 6, clue: 'The point is the sharp end of a nail.' },
			{ from: 1, to: 4, clue: 'A glue gun heats and dispenses glue.' },
			{ from: 4, to: 7, clue: 'A staple gun drives staples.' },
			{ from: 2, to: 5, clue: 'Caulk is commonly packaged in a tube.' },
			{ from: 5, to: 8, clue: 'A caulk strip seals a gap.' },
		],
	},
	{
		solution: [
			{ word: 'Shed', emoji: '🛖' },
			{ word: 'Tool', emoji: '🛠️' },
			{ word: 'Belt', emoji: '👖' },
			{ word: 'Door', emoji: '🚪' },
			{ word: 'Hook', emoji: '🪝' },
			{ word: 'Loop', emoji: '➰' },
			{ word: 'Latch', emoji: '🔒' },
			{ word: 'Lock', emoji: '🔐' },
			{ word: 'Cable', emoji: '🔌' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A tool shed stores yard tools.' },
			{ from: 1, to: 2, clue: 'A tool belt keeps small tools at your waist.' },
			{ from: 3, to: 4, clue: 'A door hook hangs on or fastens to a door.' },
			{ from: 4, to: 5, clue: 'Hook and loop fasteners press together and peel apart.' },
			{ from: 6, to: 7, clue: 'A latch lock secures a gate, shed, or cabinet.' },
			{ from: 7, to: 8, clue: 'A cable lock loops a cable through something you want secured.' },
			{ from: 0, to: 3, clue: 'A shed door opens into the storage space.' },
			{ from: 3, to: 6, clue: 'A door latch catches the door shut.' },
			{ from: 1, to: 4, clue: 'A tool hook holds a tool on a wall or rack.' },
			{ from: 4, to: 7, clue: 'A hook lock uses a hooked bolt to lock into place.' },
			{ from: 2, to: 5, clue: 'A belt loop holds a belt in place.' },
			{ from: 5, to: 8, clue: 'A cable loop is a loop made from cable.' },
		],
	},
	{
		solution: [
			{ word: 'Tray', emoji: '📥' },
			{ word: 'Card', emoji: '🃏' },
			{ word: 'Pip', emoji: '⚫' },
			{ word: 'Token', emoji: '🔘' },
			{ word: 'Box', emoji: '📦' },
			{ word: 'Domino', emoji: '🁣' },
			{ word: 'Bag', emoji: '🛍️' },
			{ word: 'Chip', emoji: '🔴' },
			{ word: 'Rack', emoji: '🧰' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A card tray keeps cards stacked between turns.' },
			{ from: 1, to: 2, clue: 'Number cards use pips to show their suit and value.' },
			{ from: 3, to: 4, clue: 'A token box stores counters between plays.' },
			{ from: 4, to: 5, clue: 'A domino box keeps dominoes together between games.' },
			{ from: 6, to: 7, clue: 'A bag can hold chips for blind draws.' },
			{ from: 7, to: 8, clue: 'A chip rack keeps game chips sorted in rows.' },
			{ from: 0, to: 3, clue: 'A token tray keeps counters from scattering.' },
			{ from: 3, to: 6, clue: 'A token bag hides counters until they are drawn.' },
			{ from: 1, to: 4, clue: 'A card box protects a deck between games.' },
			{ from: 4, to: 7, clue: 'A chip box stores loose game chips.' },
			{ from: 2, to: 5, clue: 'Dominoes use pips to show their values.' },
			{ from: 5, to: 8, clue: 'A domino rack holds a player’s dominoes upright.' },
		],
	},
	{
		solution: [
			{ word: 'Sky', emoji: '🌤️' },
			{ word: 'Thunder', emoji: '🔊' },
			{ word: 'Shower', emoji: '🌦️' },
			{ word: 'Hail', emoji: '🧊' },
			{ word: 'Storm', emoji: '⛈️' },
			{ word: 'Rain', emoji: '🌧️' },
			{ word: 'Pellet', emoji: '⚪' },
			{ word: 'Snow', emoji: '❄️' },
			{ word: 'Sleet', emoji: '🌨️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Thunder is heard in the sky.' },
			{ from: 1, to: 2, clue: 'A thundershower is a shower with thunder.' },
			{ from: 3, to: 4, clue: 'A hailstorm is a storm that drops hail.' },
			{ from: 4, to: 5, clue: 'A rainstorm is a storm with rain.' },
			{ from: 6, to: 7, clue: 'Snow pellets are rounded grains of snow.' },
			{ from: 7, to: 8, clue: 'Snow and sleet are frozen precipitation.' },
			{ from: 0, to: 3, clue: 'Hail falls from the sky.' },
			{ from: 3, to: 6, clue: 'Hail pellets are small balls of hail.' },
			{ from: 1, to: 4, clue: 'A thunderstorm is a storm with thunder.' },
			{ from: 4, to: 7, clue: 'A snowstorm is a storm with snow.' },
			{ from: 2, to: 5, clue: 'A rain shower is a short fall of rain.' },
			{ from: 5, to: 8, clue: 'Sleet is frozen rain.' },
		],
	},
].map(withCurrentGeneration);

export const REVIEW_HARD_BATCH_C: PuzzleDraft[] = [
	{
		solution: [
			{ word: 'Check', emoji: '✅' },
			{ word: 'Rain', emoji: '🌧️' },
			{ word: 'Slicker', emoji: '🧥' },
			{ word: 'Mark', emoji: '✔️' },
			{ word: 'Down', emoji: '⬇️' },
			{ word: 'Vest', emoji: '🎽' },
			{ word: 'Quill', emoji: '🖋️' },
			{ word: 'Feather', emoji: '🪶' },
			{ word: 'Leather', emoji: '👞' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'Deferred plans can take this wet promise.' },
			{ from: 1, to: 2, clue: 'A rain slicker is outerwear for wet weather.' },
			{ from: 3, to: 4, clue: 'A markdown is a price cut on the tag.' },
			{ from: 4, to: 5, clue: 'A down vest is a warm filled layer.' },
			{ from: 6, to: 7, clue: 'A quill begins as a feather.' },
			{ from: 7, to: 8, clue: 'Feather and leather rhyme cleanly.' },
			{ from: 0, to: 3, clue: 'A check mark is a tick on the page.' },
			{ from: 3, to: 6, clue: 'A quill makes marks on paper.' },
			{ from: 1, to: 4, clue: 'Rain can pour down from the sky.' },
			{ from: 4, to: 7, clue: 'Down is the soft feather used as filling.' },
			{ from: 2, to: 5, clue: 'Upper-body outerwear can shed rain or warm the core.' },
			{ from: 5, to: 8, clue: 'A leather vest is a tough hide layer.' },
		],
	},
	{
		solution: [
			{ word: 'Press', emoji: '📰' },
			{ word: 'Release', emoji: '🔓' },
			{ word: 'Date', emoji: '📅' },
			{ word: 'Charge', emoji: '⚡' },
			{ word: 'Notice', emoji: '📢' },
			{ word: 'Court', emoji: '⚖️' },
			{ word: 'Card', emoji: '💳' },
			{ word: 'Board', emoji: '🪧' },
			{ word: 'Move', emoji: '➡️' },
		],
		edges: [
			{ from: 0, to: 1, clue: 'A press release is a public media statement.' },
			{ from: 1, to: 2, clue: 'A release date is the day something comes out.' },
			{ from: 3, to: 4, clue: 'A charge notice states a charge that must be answered or paid.' },
			{ from: 4, to: 5, clue: 'A court notice is an official message from a court.' },
			{ from: 6, to: 7, clue: 'Cardboard combines card and board into a stiff material.' },
			{ from: 7, to: 8, clue: 'A move is made on a board in games like chess.' },
			{ from: 0, to: 3, clue: 'To press charges is to formally accuse someone.' },
			{ from: 3, to: 6, clue: 'A charge card lets purchases be charged to an account.' },
			{ from: 1, to: 4, clue: 'A release notice announces that something has been made public.' },
			{ from: 4, to: 7, clue: 'A noticeboard is a board for posted notices.' },
			{ from: 2, to: 5, clue: 'A court date is when a legal matter is scheduled.' },
			{ from: 5, to: 8, clue: 'To move a court is to ask it for an order.' },
		],
	},
].map(withCurrentGeneration);