<svelte:head>
	<title>FAQ · Lextangle</title>
	<meta
		name="description"
		content="Answers about Lextangle: who made it, how word links work, what the flip and shift buttons do, when daily puzzles roll over, and more."
	/>
</svelte:head>

<article class="prose prose-sm dark:prose-invert max-w-none space-y-4 text-sm leading-relaxed text-(--text)">
	<h1 class="font-display text-2xl font-bold">FAQ</h1>

	<h2 class="font-display text-lg font-bold pt-2">Who made Lextangle?</h2>
	<p>
		Lextangle is built by <a class="underline hover:text-(--crayon-red)" href="https://benjamin-brady.github.io/" target="_blank" rel="noopener noreferrer">Ben Brady</a>,
		a solo developer who also makes <a class="underline hover:text-(--crayon-red)" href="https://redactle.net" target="_blank" rel="noopener noreferrer">Redactle</a>,
		<a class="underline hover:text-(--crayon-red)" href="https://wildguessr.com" target="_blank" rel="noopener noreferrer">Wild Guessr</a>,
		and a handful of other word and trivia games. If you want to support the work, the
		<a class="underline hover:text-(--crayon-red)" href="https://ko-fi.com/benbob" target="_blank" rel="noopener noreferrer">Buy Me a Coffee</a> link in the footer is the best way.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">How do I play?</h2>
	<p>
		Drag the nine words from the tray into the 3×3 grid so that every neighbouring pair forms a valid link.
		Hit <strong>check</strong> when you think you have it. Green means the tile is in the correct spot, red means it isn't.
		The <strong>how to play</strong> button in the top-right has an interactive walkthrough.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">What counts as a "word link"?</h2>
	<p>
		A link is any meaningful relationship between two words. Once you solve a puzzle, every link's explanation is revealed. Common types include:
	</p>
	<ul class="list-disc pl-5 space-y-1">
		<li><strong>Synonyms:</strong> <em>cab</em> ↔ <em>taxi</em></li>
		<li><strong>Compound words:</strong> <em>moon</em> ↔ <em>light</em> → moonlight</li>
		<li><strong>Category and member:</strong> <em>dog</em> ↔ <em>pet</em></li>
		<li><strong>Object and trait:</strong> <em>star</em> ↔ <em>bright</em></li>
		<li><strong>Common phrase:</strong> <em>rock</em> ↔ <em>solid</em></li>
		<li><strong>Action and target:</strong> <em>cast</em> ↔ <em>line</em></li>
	</ul>
	<p>
		Each puzzle has 12 links: 6 horizontal and 6 vertical. The <strong>links</strong> counter can run ahead of <strong>words</strong> because two tiles can satisfy a link without either being in its final spot.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">What do the flip and shift buttons do?</h2>
	<ul class="list-disc pl-5 space-y-1">
		<li><strong>Flip horizontal</strong> mirrors the grid left-to-right.</li>
		<li><strong>Flip vertical</strong> mirrors the grid top-to-bottom.</li>
		<li><strong>Shift right</strong> rotates each row one column to the right; the rightmost tile wraps around.</li>
		<li><strong>Shift down</strong> rotates each column one row downward; the bottom tile wraps around.</li>
	</ul>
	<p>
		These let you re-orient a near-solution without dragging every tile. They count as a single move for undo, and don't cost a check.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">When does the daily puzzle roll over?</h2>
	<p>
		At <strong>midnight UTC</strong>. That's 8pm ET (7pm during daylight saving), 5pm PT (4pm during daylight saving), 1am in London during winter, and 10am in Sydney. Progress is saved per puzzle, so if you're mid-game when the date flips you can keep solving. Yesterday's puzzle stays on your device until you solve or reset it.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">Is there an archive?</h2>
	<p>
		Not yet for past dailies, but <a class="underline hover:text-(--crayon-red)" href="/practice">practice mode</a> has dozens of standard and hard puzzles you can play any time. Solved puzzles are marked with a green check.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">How are puzzles made?</h2>
	<p>
		Each puzzle starts as a draft generated by an LLM, then gets reviewed and edited by hand before going into the daily rotation. Every clue is human-checked.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">Does my progress sync across devices?</h2>
	<p>
		No. Lextangle stores progress and streaks in your browser's local storage. Clearing site data or switching browsers will reset your history.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">I found a bad clue. What do I do?</h2>
	<p>
		After you solve a puzzle, hit the 👎 button to report it. There's a comment box to explain what felt off. Feedback genuinely shapes which puzzles get rotated out.
	</p>

	<h2 class="font-display text-lg font-bold pt-2">Where can I chat with other players?</h2>
	<p>
		The <a class="underline hover:text-(--crayon-red)" href="https://discord.gg/AWfvmFWBcA" target="_blank" rel="noopener noreferrer">Discord</a> is the place. Bug reports, theme suggestions, and daily puzzle gripes all welcome.
	</p>
</article>
